(function(e,f){if("object"===typeof exports&&"object"===typeof module)module.exports=f();else if("function"===typeof define&&define.amd)define(f);else{var h=f(),m;for(m in h)("object"===typeof exports?exports:e)[m]=h[m]}})(this,function(){return function(e){function f(m){if(h[m])return h[m].exports;var b=h[m]={exports:{},id:m,loaded:!1};e[m].call(b.exports,b,b.exports,f);b.loaded=!0;return b.exports}var h={};f.m=e;f.c=h;f.p="";return f(0)}([function(e,f,h){f.glMatrix=h(1);f.mat2=h(2);f.mat2d=h(3);
f.mat3=h(4);f.mat4=h(5);f.quat=h(6);f.vec2=h(9);f.vec3=h(7);f.vec4=h(8)},function(e,f){var h={EPSILON:1E-6};h.ARRAY_TYPE="undefined"!==typeof Float32Array?Float32Array:Array;h.RANDOM=Math.random;h.ENABLE_SIMD=!1;h.SIMD_AVAILABLE=h.ARRAY_TYPE===Float32Array&&"SIMD"in this;h.USE_SIMD=h.ENABLE_SIMD&&h.SIMD_AVAILABLE;h.setMatrixArrayType=function(b){h.ARRAY_TYPE=b};var m=Math.PI/180;h.toRadian=function(b){return b*m};e.exports=h},function(e,f,h){var m=h(1);f={create:function(){var b=new m.ARRAY_TYPE(4);
b[0]=1;b[1]=0;b[2]=0;b[3]=1;return b},clone:function(b){var a=new m.ARRAY_TYPE(4);a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];return a},copy:function(b,a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},identity:function(b){b[0]=1;b[1]=0;b[2]=0;b[3]=1;return b},transpose:function(b,a){if(b===a){var c=a[1];b[1]=a[2];b[2]=c}else b[0]=a[0],b[1]=a[2],b[2]=a[1],b[3]=a[3];return b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=c*g-n*d;if(!l)return null;l=1/l;b[0]=g*l;b[1]=-d*l;b[2]=-n*l;b[3]=c*l;
return b},adjoint:function(b,a){var c=a[0];b[0]=a[3];b[1]=-a[1];b[2]=-a[2];b[3]=c;return b},determinant:function(b){return b[0]*b[3]-b[2]*b[1]},multiply:function(b,a,c){var d=a[0],n=a[1],g=a[2];a=a[3];var l=c[0],k=c[1],r=c[2];c=c[3];b[0]=d*l+g*k;b[1]=n*l+a*k;b[2]=d*r+g*c;b[3]=n*r+a*c;return b}};f.mul=f.multiply;f.rotate=function(b,a,c){var d=a[0],n=a[1],g=a[2];a=a[3];var l=Math.sin(c);c=Math.cos(c);b[0]=d*c+g*l;b[1]=n*c+a*l;b[2]=d*-l+g*c;b[3]=n*-l+a*c;return b};f.scale=function(b,a,c){var d=a[1],
n=a[2],g=a[3],l=c[0];c=c[1];b[0]=a[0]*l;b[1]=d*l;b[2]=n*c;b[3]=g*c;return b};f.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);b[0]=d;b[1]=c;b[2]=-c;b[3]=d;return b};f.fromScaling=function(b,a){b[0]=a[0];b[1]=0;b[2]=0;b[3]=a[1];return b};f.str=function(b){return"mat2("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+")"};f.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2))};f.LDU=function(b,a,c,d){b[2]=d[2]/d[0];c[0]=d[0];c[1]=d[1];c[3]=d[3]-b[2]*
c[1];return[b,a,c]};e.exports=f},function(e,f,h){var m=h(1);f={create:function(){var b=new m.ARRAY_TYPE(6);b[0]=1;b[1]=0;b[2]=0;b[3]=1;b[4]=0;b[5]=0;return b},clone:function(b){var a=new m.ARRAY_TYPE(6);a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];return a},copy:function(b,a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];return b},identity:function(b){b[0]=1;b[1]=0;b[2]=0;b[3]=1;b[4]=0;b[5]=0;return b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=a[4],k=a[5],
r=c*g-d*n;if(!r)return null;r=1/r;b[0]=g*r;b[1]=-d*r;b[2]=-n*r;b[3]=c*r;b[4]=(n*k-g*l)*r;b[5]=(d*l-c*k)*r;return b},determinant:function(b){return b[0]*b[3]-b[1]*b[2]},multiply:function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4];a=a[5];var r=c[0],p=c[1],e=c[2],f=c[3],h=c[4];c=c[5];b[0]=d*r+g*p;b[1]=n*r+l*p;b[2]=d*e+g*f;b[3]=n*e+l*f;b[4]=d*h+g*c+k;b[5]=n*h+l*c+a;return b}};f.mul=f.multiply;f.rotate=function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4];a=a[5];var r=Math.sin(c);c=Math.cos(c);b[0]=
d*c+g*r;b[1]=n*c+l*r;b[2]=d*-r+g*c;b[3]=n*-r+l*c;b[4]=k;b[5]=a;return b};f.scale=function(b,a,c){var d=a[1],n=a[2],g=a[3],l=a[4],k=a[5],r=c[0];c=c[1];b[0]=a[0]*r;b[1]=d*r;b[2]=n*c;b[3]=g*c;b[4]=l;b[5]=k;return b};f.translate=function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4];a=a[5];var r=c[0];c=c[1];b[0]=d;b[1]=n;b[2]=g;b[3]=l;b[4]=d*r+g*c+k;b[5]=n*r+l*c+a;return b};f.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);b[0]=d;b[1]=c;b[2]=-c;b[3]=d;b[4]=0;b[5]=0;return b};f.fromScaling=
function(b,a){b[0]=a[0];b[1]=0;b[2]=0;b[3]=a[1];b[4]=0;b[5]=0;return b};f.fromTranslation=function(b,a){b[0]=1;b[1]=0;b[2]=0;b[3]=1;b[4]=a[0];b[5]=a[1];return b};f.str=function(b){return"mat2d("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+", "+b[4]+", "+b[5]+")"};f.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+1)};e.exports=f},function(e,f,h){var m=h(1);f={create:function(){var b=new m.ARRAY_TYPE(9);b[0]=1;b[1]=0;b[2]=
0;b[3]=0;b[4]=1;b[5]=0;b[6]=0;b[7]=0;b[8]=1;return b},fromMat4:function(b,a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b},clone:function(b){var a=new m.ARRAY_TYPE(9);a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];return a},copy:function(b,a){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},identity:function(b){b[0]=1;b[1]=0;b[2]=0;b[3]=0;b[4]=1;b[5]=
0;b[6]=0;b[7]=0;b[8]=1;return b},transpose:function(b,a){if(b===a){var c=a[1],d=a[2],n=a[5];b[1]=a[3];b[2]=a[6];b[3]=c;b[5]=a[7];b[6]=d;b[7]=n}else b[0]=a[0],b[1]=a[3],b[2]=a[6],b[3]=a[1],b[4]=a[4],b[5]=a[7],b[6]=a[2],b[7]=a[5],b[8]=a[8];return b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=a[4],k=a[5],r=a[6],p=a[7],e=a[8],f=e*l-k*p,h=-e*g+k*r,m=p*g-l*r,q=c*f+d*h+n*m;if(!q)return null;q=1/q;b[0]=f*q;b[1]=(-e*d+n*p)*q;b[2]=(k*d-n*l)*q;b[3]=h*q;b[4]=(e*c-n*r)*q;b[5]=(-k*c+n*g)*q;b[6]=m*q;
b[7]=(-p*c+d*r)*q;b[8]=(l*c-d*g)*q;return b},adjoint:function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=a[4],k=a[5],r=a[6],p=a[7],e=a[8];b[0]=l*e-k*p;b[1]=n*p-d*e;b[2]=d*k-n*l;b[3]=k*r-g*e;b[4]=c*e-n*r;b[5]=n*g-c*k;b[6]=g*p-l*r;b[7]=d*r-c*p;b[8]=c*l-d*g;return b},determinant:function(b){var a=b[3],c=b[4],d=b[5],n=b[6],g=b[7],l=b[8];return b[0]*(l*c-d*g)+b[1]*(-l*a+d*n)+b[2]*(g*a-c*n)},multiply:function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4],r=a[5],p=a[6],e=a[7];a=a[8];var f=c[0],h=c[1],m=c[2],
q=c[3],w=c[4],u=c[5],v=c[6],y=c[7];c=c[8];b[0]=f*d+h*l+m*p;b[1]=f*n+h*k+m*e;b[2]=f*g+h*r+m*a;b[3]=q*d+w*l+u*p;b[4]=q*n+w*k+u*e;b[5]=q*g+w*r+u*a;b[6]=v*d+y*l+c*p;b[7]=v*n+y*k+c*e;b[8]=v*g+y*r+c*a;return b}};f.mul=f.multiply;f.translate=function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4],r=a[5],p=a[6],e=a[7];a=a[8];var f=c[0];c=c[1];b[0]=d;b[1]=n;b[2]=g;b[3]=l;b[4]=k;b[5]=r;b[6]=f*d+c*l+p;b[7]=f*n+c*k+e;b[8]=f*g+c*r+a;return b};f.rotate=function(b,a,c){var d=a[0],n=a[1],g=a[2],l=a[3],k=a[4],r=a[5],
p=a[6],e=a[7];a=a[8];var f=Math.sin(c);c=Math.cos(c);b[0]=c*d+f*l;b[1]=c*n+f*k;b[2]=c*g+f*r;b[3]=c*l-f*d;b[4]=c*k-f*n;b[5]=c*r-f*g;b[6]=p;b[7]=e;b[8]=a;return b};f.scale=function(b,a,c){var d=c[0];c=c[1];b[0]=d*a[0];b[1]=d*a[1];b[2]=d*a[2];b[3]=c*a[3];b[4]=c*a[4];b[5]=c*a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b};f.fromTranslation=function(b,a){b[0]=1;b[1]=0;b[2]=0;b[3]=0;b[4]=1;b[5]=0;b[6]=a[0];b[7]=a[1];b[8]=1;return b};f.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);b[0]=d;b[1]=c;
b[2]=0;b[3]=-c;b[4]=d;b[5]=0;b[6]=0;b[7]=0;b[8]=1;return b};f.fromScaling=function(b,a){b[0]=a[0];b[1]=0;b[2]=0;b[3]=0;b[4]=a[1];b[5]=0;b[6]=0;b[7]=0;b[8]=1;return b};f.fromMat2d=function(b,a){b[0]=a[0];b[1]=a[1];b[2]=0;b[3]=a[2];b[4]=a[3];b[5]=0;b[6]=a[4];b[7]=a[5];b[8]=1;return b};f.fromQuat=function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=c+c,k=d+d,r=n+n,c=c*l,p=d*l,d=d*k,e=n*l,f=n*k,n=n*r,l=g*l,k=g*k,g=g*r;b[0]=1-d-n;b[3]=p-g;b[6]=e+k;b[1]=p+g;b[4]=1-c-n;b[7]=f-l;b[2]=e-k;b[5]=f+l;b[8]=1-c-d;return b};
f.normalFromMat4=function(b,a){var c=a[0],d=a[1],n=a[2],g=a[3],l=a[4],k=a[5],r=a[6],p=a[7],e=a[8],f=a[9],h=a[10],m=a[11],q=a[12],w=a[13],u=a[14],v=a[15],y=c*k-d*l,C=c*r-n*l,A=c*p-g*l,B=d*r-n*k,z=d*p-g*k,G=n*p-g*r,H=e*w-f*q,I=e*u-h*q,e=e*v-m*q,J=f*u-h*w,f=f*v-m*w,h=h*v-m*u,m=y*h-C*f+A*J+B*e-z*I+G*H;if(!m)return null;m=1/m;b[0]=(k*h-r*f+p*J)*m;b[1]=(r*e-l*h-p*I)*m;b[2]=(l*f-k*e+p*H)*m;b[3]=(n*f-d*h-g*J)*m;b[4]=(c*h-n*e+g*I)*m;b[5]=(d*e-c*f-g*H)*m;b[6]=(w*G-u*z+v*B)*m;b[7]=(u*A-q*G-v*C)*m;b[8]=(q*z-
w*A+v*y)*m;return b};f.str=function(b){return"mat3("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+", "+b[4]+", "+b[5]+", "+b[6]+", "+b[7]+", "+b[8]+")"};f.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+Math.pow(b[6],2)+Math.pow(b[7],2)+Math.pow(b[8],2))};e.exports=f},function(e,f,h){var m=h(1),b={scalar:{},SIMD:{},create:function(){var a=new m.ARRAY_TYPE(16);a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=
0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},clone:function(a){var c=new m.ARRAY_TYPE(16);c[0]=a[0];c[1]=a[1];c[2]=a[2];c[3]=a[3];c[4]=a[4];c[5]=a[5];c[6]=a[6];c[7]=a[7];c[8]=a[8];c[9]=a[9];c[10]=a[10];c[11]=a[11];c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c},copy:function(a,c){a[0]=c[0];a[1]=c[1];a[2]=c[2];a[3]=c[3];a[4]=c[4];a[5]=c[5];a[6]=c[6];a[7]=c[7];a[8]=c[8];a[9]=c[9];a[10]=c[10];a[11]=c[11];a[12]=c[12];a[13]=c[13];a[14]=c[14];a[15]=c[15];return a},identity:function(a){a[0]=
1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}};b.scalar.transpose=function(a,c){if(a===c){var d=c[1],b=c[2],g=c[3],l=c[6],k=c[7],r=c[11];a[1]=c[4];a[2]=c[8];a[3]=c[12];a[4]=d;a[6]=c[9];a[7]=c[13];a[8]=b;a[9]=l;a[11]=c[14];a[12]=g;a[13]=k;a[14]=r}else a[0]=c[0],a[1]=c[4],a[2]=c[8],a[3]=c[12],a[4]=c[1],a[5]=c[5],a[6]=c[9],a[7]=c[13],a[8]=c[2],a[9]=c[6],a[10]=c[10],a[11]=c[14],a[12]=c[3],a[13]=c[7],a[14]=c[11],a[15]=c[15];return a};
b.SIMD.transpose=function(a,c){var d,b,g,l,k,r,p;d=SIMD.Float32x4.load(c,0);b=SIMD.Float32x4.load(c,4);g=SIMD.Float32x4.load(c,8);l=SIMD.Float32x4.load(c,12);k=SIMD.Float32x4.shuffle(d,b,0,1,4,5);r=SIMD.Float32x4.shuffle(g,l,0,1,4,5);p=SIMD.Float32x4.shuffle(k,r,0,2,4,6);k=SIMD.Float32x4.shuffle(k,r,1,3,5,7);SIMD.Float32x4.store(a,0,p);SIMD.Float32x4.store(a,4,k);k=SIMD.Float32x4.shuffle(d,b,2,3,6,7);r=SIMD.Float32x4.shuffle(g,l,2,3,6,7);d=SIMD.Float32x4.shuffle(k,r,0,2,4,6);b=SIMD.Float32x4.shuffle(k,
r,1,3,5,7);SIMD.Float32x4.store(a,8,d);SIMD.Float32x4.store(a,12,b);return a};b.transpose=m.USE_SIMD?b.SIMD.transpose:b.scalar.transpose;b.scalar.invert=function(a,c){var d=c[0],b=c[1],g=c[2],l=c[3],k=c[4],r=c[5],p=c[6],e=c[7],f=c[8],h=c[9],m=c[10],q=c[11],w=c[12],u=c[13],v=c[14],y=c[15],C=d*r-b*k,A=d*p-g*k,B=d*e-l*k,z=b*p-g*r,G=b*e-l*r,H=g*e-l*p,I=f*u-h*w,J=f*v-m*w,K=f*y-q*w,L=h*v-m*u,M=h*y-q*u,N=m*y-q*v,E=C*N-A*M+B*L+z*K-G*J+H*I;if(!E)return null;E=1/E;a[0]=(r*N-p*M+e*L)*E;a[1]=(g*M-b*N-l*L)*E;
a[2]=(u*H-v*G+y*z)*E;a[3]=(m*G-h*H-q*z)*E;a[4]=(p*K-k*N-e*J)*E;a[5]=(d*N-g*K+l*J)*E;a[6]=(v*B-w*H-y*A)*E;a[7]=(f*H-m*B+q*A)*E;a[8]=(k*M-r*K+e*I)*E;a[9]=(b*K-d*M-l*I)*E;a[10]=(w*G-u*B+y*C)*E;a[11]=(h*B-f*G-q*C)*E;a[12]=(r*J-k*L-p*I)*E;a[13]=(d*L-b*J+g*I)*E;a[14]=(u*A-w*z-v*C)*E;a[15]=(f*z-h*A+m*C)*E;return a};b.SIMD.invert=function(a,c){var d,b,g,l,k,e,p,f,h;e=SIMD.Float32x4.load(c,0);p=SIMD.Float32x4.load(c,4);f=SIMD.Float32x4.load(c,8);h=SIMD.Float32x4.load(c,12);k=SIMD.Float32x4.shuffle(e,p,0,1,
4,5);b=SIMD.Float32x4.shuffle(f,h,0,1,4,5);d=SIMD.Float32x4.shuffle(k,b,0,2,4,6);b=SIMD.Float32x4.shuffle(b,k,1,3,5,7);k=SIMD.Float32x4.shuffle(e,p,2,3,6,7);l=SIMD.Float32x4.shuffle(f,h,2,3,6,7);g=SIMD.Float32x4.shuffle(k,l,0,2,4,6);l=SIMD.Float32x4.shuffle(l,k,1,3,5,7);k=SIMD.Float32x4.mul(g,l);k=SIMD.Float32x4.swizzle(k,1,0,3,2);e=SIMD.Float32x4.mul(b,k);p=SIMD.Float32x4.mul(d,k);k=SIMD.Float32x4.swizzle(k,2,3,0,1);e=SIMD.Float32x4.sub(SIMD.Float32x4.mul(b,k),e);p=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,
k),p);p=SIMD.Float32x4.swizzle(p,2,3,0,1);k=SIMD.Float32x4.mul(b,g);k=SIMD.Float32x4.swizzle(k,1,0,3,2);e=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,k),e);h=SIMD.Float32x4.mul(d,k);k=SIMD.Float32x4.swizzle(k,2,3,0,1);e=SIMD.Float32x4.sub(e,SIMD.Float32x4.mul(l,k));h=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,k),h);h=SIMD.Float32x4.swizzle(h,2,3,0,1);k=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(b,2,3,0,1),l);k=SIMD.Float32x4.swizzle(k,1,0,3,2);g=SIMD.Float32x4.swizzle(g,2,3,0,1);e=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,
k),e);f=SIMD.Float32x4.mul(d,k);k=SIMD.Float32x4.swizzle(k,2,3,0,1);e=SIMD.Float32x4.sub(e,SIMD.Float32x4.mul(g,k));f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,k),f);f=SIMD.Float32x4.swizzle(f,2,3,0,1);k=SIMD.Float32x4.mul(d,b);k=SIMD.Float32x4.swizzle(k,1,0,3,2);f=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,k),f);h=SIMD.Float32x4.sub(SIMD.Float32x4.mul(g,k),h);k=SIMD.Float32x4.swizzle(k,2,3,0,1);f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(l,k),f);h=SIMD.Float32x4.sub(h,SIMD.Float32x4.mul(g,k));k=SIMD.Float32x4.mul(d,
l);k=SIMD.Float32x4.swizzle(k,1,0,3,2);p=SIMD.Float32x4.sub(p,SIMD.Float32x4.mul(g,k));f=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,k),f);k=SIMD.Float32x4.swizzle(k,2,3,0,1);p=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,k),p);f=SIMD.Float32x4.sub(f,SIMD.Float32x4.mul(b,k));k=SIMD.Float32x4.mul(d,g);k=SIMD.Float32x4.swizzle(k,1,0,3,2);p=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,k),p);h=SIMD.Float32x4.sub(h,SIMD.Float32x4.mul(b,k));k=SIMD.Float32x4.swizzle(k,2,3,0,1);p=SIMD.Float32x4.sub(p,SIMD.Float32x4.mul(l,
k));h=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,k),h);d=SIMD.Float32x4.mul(d,e);d=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(d,2,3,0,1),d);d=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(d,1,0,3,2),d);k=SIMD.Float32x4.reciprocalApproximation(d);d=SIMD.Float32x4.sub(SIMD.Float32x4.add(k,k),SIMD.Float32x4.mul(d,SIMD.Float32x4.mul(k,k)));d=SIMD.Float32x4.swizzle(d,0,0,0,0);if(!d)return null;SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(d,e));SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(d,p));SIMD.Float32x4.store(a,
8,SIMD.Float32x4.mul(d,f));SIMD.Float32x4.store(a,12,SIMD.Float32x4.mul(d,h));return a};b.invert=m.USE_SIMD?b.SIMD.invert:b.scalar.invert;b.scalar.adjoint=function(a,c){var d=c[0],b=c[1],g=c[2],l=c[3],k=c[4],e=c[5],p=c[6],f=c[7],h=c[8],m=c[9],x=c[10],q=c[11],w=c[12],u=c[13],v=c[14],y=c[15];a[0]=e*(x*y-q*v)-m*(p*y-f*v)+u*(p*q-f*x);a[1]=-(b*(x*y-q*v)-m*(g*y-l*v)+u*(g*q-l*x));a[2]=b*(p*y-f*v)-e*(g*y-l*v)+u*(g*f-l*p);a[3]=-(b*(p*q-f*x)-e*(g*q-l*x)+m*(g*f-l*p));a[4]=-(k*(x*y-q*v)-h*(p*y-f*v)+w*(p*q-f*
x));a[5]=d*(x*y-q*v)-h*(g*y-l*v)+w*(g*q-l*x);a[6]=-(d*(p*y-f*v)-k*(g*y-l*v)+w*(g*f-l*p));a[7]=d*(p*q-f*x)-k*(g*q-l*x)+h*(g*f-l*p);a[8]=k*(m*y-q*u)-h*(e*y-f*u)+w*(e*q-f*m);a[9]=-(d*(m*y-q*u)-h*(b*y-l*u)+w*(b*q-l*m));a[10]=d*(e*y-f*u)-k*(b*y-l*u)+w*(b*f-l*e);a[11]=-(d*(e*q-f*m)-k*(b*q-l*m)+h*(b*f-l*e));a[12]=-(k*(m*v-x*u)-h*(e*v-p*u)+w*(e*x-p*m));a[13]=d*(m*v-x*u)-h*(b*v-g*u)+w*(b*x-g*m);a[14]=-(d*(e*v-p*u)-k*(b*v-g*u)+w*(b*p-g*e));a[15]=d*(e*x-p*m)-k*(b*x-g*m)+h*(b*p-g*e);return a};b.SIMD.adjoint=
function(a,c){var d,b,g,l,k,e,p,f,h;d=SIMD.Float32x4.load(c,0);b=SIMD.Float32x4.load(c,4);g=SIMD.Float32x4.load(c,8);l=SIMD.Float32x4.load(c,12);p=SIMD.Float32x4.shuffle(d,b,0,1,4,5);e=SIMD.Float32x4.shuffle(g,l,0,1,4,5);k=SIMD.Float32x4.shuffle(p,e,0,2,4,6);e=SIMD.Float32x4.shuffle(e,p,1,3,5,7);p=SIMD.Float32x4.shuffle(d,b,2,3,6,7);b=SIMD.Float32x4.shuffle(g,l,2,3,6,7);d=SIMD.Float32x4.shuffle(p,b,0,2,4,6);b=SIMD.Float32x4.shuffle(b,p,1,3,5,7);p=SIMD.Float32x4.mul(d,b);p=SIMD.Float32x4.swizzle(p,
1,0,3,2);g=SIMD.Float32x4.mul(e,p);l=SIMD.Float32x4.mul(k,p);p=SIMD.Float32x4.swizzle(p,2,3,0,1);g=SIMD.Float32x4.sub(SIMD.Float32x4.mul(e,p),g);l=SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,p),l);l=SIMD.Float32x4.swizzle(l,2,3,0,1);p=SIMD.Float32x4.mul(e,d);p=SIMD.Float32x4.swizzle(p,1,0,3,2);g=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,p),g);h=SIMD.Float32x4.mul(k,p);p=SIMD.Float32x4.swizzle(p,2,3,0,1);g=SIMD.Float32x4.sub(g,SIMD.Float32x4.mul(b,p));h=SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,p),h);h=SIMD.Float32x4.swizzle(h,
2,3,0,1);p=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,2,3,0,1),b);p=SIMD.Float32x4.swizzle(p,1,0,3,2);d=SIMD.Float32x4.swizzle(d,2,3,0,1);g=SIMD.Float32x4.add(SIMD.Float32x4.mul(d,p),g);f=SIMD.Float32x4.mul(k,p);p=SIMD.Float32x4.swizzle(p,2,3,0,1);g=SIMD.Float32x4.sub(g,SIMD.Float32x4.mul(d,p));f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,p),f);f=SIMD.Float32x4.swizzle(f,2,3,0,1);p=SIMD.Float32x4.mul(k,e);p=SIMD.Float32x4.swizzle(p,1,0,3,2);f=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,p),f);h=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,
p),h);p=SIMD.Float32x4.swizzle(p,2,3,0,1);f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(b,p),f);h=SIMD.Float32x4.sub(h,SIMD.Float32x4.mul(d,p));p=SIMD.Float32x4.mul(k,b);p=SIMD.Float32x4.swizzle(p,1,0,3,2);l=SIMD.Float32x4.sub(l,SIMD.Float32x4.mul(d,p));f=SIMD.Float32x4.add(SIMD.Float32x4.mul(e,p),f);p=SIMD.Float32x4.swizzle(p,2,3,0,1);l=SIMD.Float32x4.add(SIMD.Float32x4.mul(d,p),l);f=SIMD.Float32x4.sub(f,SIMD.Float32x4.mul(e,p));p=SIMD.Float32x4.mul(k,d);p=SIMD.Float32x4.swizzle(p,1,0,3,2);l=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,
p),l);h=SIMD.Float32x4.sub(h,SIMD.Float32x4.mul(e,p));p=SIMD.Float32x4.swizzle(p,2,3,0,1);l=SIMD.Float32x4.sub(l,SIMD.Float32x4.mul(b,p));h=SIMD.Float32x4.add(SIMD.Float32x4.mul(e,p),h);SIMD.Float32x4.store(a,0,g);SIMD.Float32x4.store(a,4,l);SIMD.Float32x4.store(a,8,f);SIMD.Float32x4.store(a,12,h);return a};b.adjoint=m.USE_SIMD?b.SIMD.adjoint:b.scalar.adjoint;b.determinant=function(a){var c=a[0],d=a[1],b=a[2],g=a[3],l=a[4],k=a[5],e=a[6],f=a[7],h=a[8],m=a[9],t=a[10],x=a[11],q=a[12],w=a[13],u=a[14];
a=a[15];return(c*k-d*l)*(t*a-x*u)-(c*e-b*l)*(m*a-x*w)+(c*f-g*l)*(m*u-t*w)+(d*e-b*k)*(h*a-x*q)-(d*f-g*k)*(h*u-t*q)+(b*f-g*e)*(h*w-m*q)};b.SIMD.multiply=function(a,c,d){var b=SIMD.Float32x4.load(c,0),g=SIMD.Float32x4.load(c,4),l=SIMD.Float32x4.load(c,8);c=SIMD.Float32x4.load(c,12);var k=SIMD.Float32x4.load(d,0),k=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,1,1,1,1),g),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,
2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,3,3,3,3),c))));SIMD.Float32x4.store(a,0,k);k=SIMD.Float32x4.load(d,4);k=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,1,1,1,1),g),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,3,3,3,3),c))));SIMD.Float32x4.store(a,4,k);k=SIMD.Float32x4.load(d,8);k=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,
0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,1,1,1,1),g),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(k,3,3,3,3),c))));SIMD.Float32x4.store(a,8,k);d=SIMD.Float32x4.load(d,12);b=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,1,1,1,1),g),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,2,2,2,2),
l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,3,3,3,3),c))));SIMD.Float32x4.store(a,12,b);return a};b.scalar.multiply=function(a,c,d){var b=c[0],g=c[1],l=c[2],k=c[3],e=c[4],f=c[5],h=c[6],m=c[7],t=c[8],x=c[9],q=c[10],w=c[11],u=c[12],v=c[13],y=c[14];c=c[15];var C=d[0],A=d[1],B=d[2],z=d[3];a[0]=C*b+A*e+B*t+z*u;a[1]=C*g+A*f+B*x+z*v;a[2]=C*l+A*h+B*q+z*y;a[3]=C*k+A*m+B*w+z*c;C=d[4];A=d[5];B=d[6];z=d[7];a[4]=C*b+A*e+B*t+z*u;a[5]=C*g+A*f+B*x+z*v;a[6]=C*l+A*h+B*q+z*y;a[7]=C*k+A*m+B*w+z*c;C=d[8];A=d[9];B=
d[10];z=d[11];a[8]=C*b+A*e+B*t+z*u;a[9]=C*g+A*f+B*x+z*v;a[10]=C*l+A*h+B*q+z*y;a[11]=C*k+A*m+B*w+z*c;C=d[12];A=d[13];B=d[14];z=d[15];a[12]=C*b+A*e+B*t+z*u;a[13]=C*g+A*f+B*x+z*v;a[14]=C*l+A*h+B*q+z*y;a[15]=C*k+A*m+B*w+z*c;return a};b.multiply=m.USE_SIMD?b.SIMD.multiply:b.scalar.multiply;b.mul=b.multiply;b.scalar.translate=function(a,c,d){var b=d[0],g=d[1];d=d[2];var l,k,e,f,h,m,t,x,q,w,u,v;c===a?(a[12]=c[0]*b+c[4]*g+c[8]*d+c[12],a[13]=c[1]*b+c[5]*g+c[9]*d+c[13],a[14]=c[2]*b+c[6]*g+c[10]*d+c[14],a[15]=
c[3]*b+c[7]*g+c[11]*d+c[15]):(l=c[0],k=c[1],e=c[2],f=c[3],h=c[4],m=c[5],t=c[6],x=c[7],q=c[8],w=c[9],u=c[10],v=c[11],a[0]=l,a[1]=k,a[2]=e,a[3]=f,a[4]=h,a[5]=m,a[6]=t,a[7]=x,a[8]=q,a[9]=w,a[10]=u,a[11]=v,a[12]=l*b+h*g+q*d+c[12],a[13]=k*b+m*g+w*d+c[13],a[14]=e*b+t*g+u*d+c[14],a[15]=f*b+x*g+v*d+c[15]);return a};b.SIMD.translate=function(a,c,d){var b=SIMD.Float32x4.load(c,0),g=SIMD.Float32x4.load(c,4),l=SIMD.Float32x4.load(c,8),k=SIMD.Float32x4.load(c,12);d=SIMD.Float32x4(d[0],d[1],d[2],0);c!==a&&(a[0]=
c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11]);b=SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(d,0,0,0,0));g=SIMD.Float32x4.mul(g,SIMD.Float32x4.swizzle(d,1,1,1,1));l=SIMD.Float32x4.mul(l,SIMD.Float32x4.swizzle(d,2,2,2,2));c=SIMD.Float32x4.add(b,SIMD.Float32x4.add(g,SIMD.Float32x4.add(l,k)));SIMD.Float32x4.store(a,12,c);return a};b.translate=m.USE_SIMD?b.SIMD.translate:b.scalar.translate;b.scalar.scale=function(a,c,d){var b=d[0],
g=d[1];d=d[2];a[0]=c[0]*b;a[1]=c[1]*b;a[2]=c[2]*b;a[3]=c[3]*b;a[4]=c[4]*g;a[5]=c[5]*g;a[6]=c[6]*g;a[7]=c[7]*g;a[8]=c[8]*d;a[9]=c[9]*d;a[10]=c[10]*d;a[11]=c[11]*d;a[12]=c[12];a[13]=c[13];a[14]=c[14];a[15]=c[15];return a};b.SIMD.scale=function(a,c,d){var b;d=SIMD.Float32x4(d[0],d[1],d[2],0);b=SIMD.Float32x4.load(c,0);SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(d,0,0,0,0)));b=SIMD.Float32x4.load(c,4);SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(d,1,1,
1,1)));b=SIMD.Float32x4.load(c,8);SIMD.Float32x4.store(a,8,SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(d,2,2,2,2)));a[12]=c[12];a[13]=c[13];a[14]=c[14];a[15]=c[15];return a};b.scale=m.USE_SIMD?b.SIMD.scale:b.scalar.scale;b.rotate=function(a,c,d,b){var g=b[0],n=b[1];b=b[2];var k=Math.sqrt(g*g+n*n+b*b),e,f,h,D,t,x,q,w,u,v,y,C,A,B,z,G,H,I,J,K;if(Math.abs(k)<m.EPSILON)return null;k=1/k;g*=k;n*=k;b*=k;e=Math.sin(d);f=Math.cos(d);h=1-f;d=c[0];k=c[1];D=c[2];t=c[3];x=c[4];q=c[5];w=c[6];u=c[7];v=c[8];y=c[9];
C=c[10];A=c[11];B=g*g*h+f;z=n*g*h+b*e;G=b*g*h-n*e;H=g*n*h-b*e;I=n*n*h+f;J=b*n*h+g*e;K=g*b*h+n*e;g=n*b*h-g*e;n=b*b*h+f;a[0]=d*B+x*z+v*G;a[1]=k*B+q*z+y*G;a[2]=D*B+w*z+C*G;a[3]=t*B+u*z+A*G;a[4]=d*H+x*I+v*J;a[5]=k*H+q*I+y*J;a[6]=D*H+w*I+C*J;a[7]=t*H+u*I+A*J;a[8]=d*K+x*g+v*n;a[9]=k*K+q*g+y*n;a[10]=D*K+w*g+C*n;a[11]=t*K+u*g+A*n;c!==a&&(a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);return a};b.scalar.rotateX=function(a,c,d){var b=Math.sin(d);d=Math.cos(d);var g=c[4],l=c[5],k=c[6],e=c[7],f=c[8],h=c[9],
m=c[10],t=c[11];c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);a[4]=g*d+f*b;a[5]=l*d+h*b;a[6]=k*d+m*b;a[7]=e*d+t*b;a[8]=f*d-g*b;a[9]=h*d-l*b;a[10]=m*d-k*b;a[11]=t*d-e*b;return a};b.SIMD.rotateX=function(a,c,d){var b=SIMD.Float32x4.splat(Math.sin(d));d=SIMD.Float32x4.splat(Math.cos(d));c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var g=SIMD.Float32x4.load(c,4);c=SIMD.Float32x4.load(c,8);SIMD.Float32x4.store(a,
4,SIMD.Float32x4.add(SIMD.Float32x4.mul(g,d),SIMD.Float32x4.mul(c,b)));SIMD.Float32x4.store(a,8,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,d),SIMD.Float32x4.mul(g,b)));return a};b.rotateX=m.USE_SIMD?b.SIMD.rotateX:b.scalar.rotateX;b.scalar.rotateY=function(a,c,d){var b=Math.sin(d);d=Math.cos(d);var g=c[0],l=c[1],k=c[2],e=c[3],f=c[8],h=c[9],m=c[10],t=c[11];c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);a[0]=g*d-f*b;a[1]=l*d-h*b;a[2]=k*d-m*b;a[3]=e*d-t*
b;a[8]=g*b+f*d;a[9]=l*b+h*d;a[10]=k*b+m*d;a[11]=e*b+t*d;return a};b.SIMD.rotateY=function(a,c,d){var b=SIMD.Float32x4.splat(Math.sin(d));d=SIMD.Float32x4.splat(Math.cos(d));c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var g=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,8);SIMD.Float32x4.store(a,0,SIMD.Float32x4.sub(SIMD.Float32x4.mul(g,d),SIMD.Float32x4.mul(c,b)));SIMD.Float32x4.store(a,8,SIMD.Float32x4.add(SIMD.Float32x4.mul(g,b),SIMD.Float32x4.mul(c,
d)));return a};b.rotateY=m.USE_SIMD?b.SIMD.rotateY:b.scalar.rotateY;b.scalar.rotateZ=function(a,c,d){var b=Math.sin(d);d=Math.cos(d);var g=c[0],l=c[1],k=c[2],e=c[3],f=c[4],h=c[5],m=c[6],t=c[7];c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);a[0]=g*d+f*b;a[1]=l*d+h*b;a[2]=k*d+m*b;a[3]=e*d+t*b;a[4]=f*d-g*b;a[5]=h*d-l*b;a[6]=m*d-k*b;a[7]=t*d-e*b;return a};b.SIMD.rotateZ=function(a,c,b){var d=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));
c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var g=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,4);SIMD.Float32x4.store(a,0,SIMD.Float32x4.add(SIMD.Float32x4.mul(g,b),SIMD.Float32x4.mul(c,d)));SIMD.Float32x4.store(a,4,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,b),SIMD.Float32x4.mul(g,d)));return a};b.rotateZ=m.USE_SIMD?b.SIMD.rotateZ:b.scalar.rotateZ;b.fromTranslation=function(a,c){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=
0;a[9]=0;a[10]=1;a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a};b.fromScaling=function(a,c){a[0]=c[0];a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=c[1];a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=c[2];a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.fromRotation=function(a,c,b){var d=b[0],g=b[1];b=b[2];var l=Math.sqrt(d*d+g*g+b*b),k;if(Math.abs(l)<m.EPSILON)return null;l=1/l;d*=l;g*=l;b*=l;l=Math.sin(c);c=Math.cos(c);k=1-c;a[0]=d*d*k+c;a[1]=g*d*k+b*l;a[2]=b*d*k-g*l;a[3]=0;a[4]=d*g*k-b*l;a[5]=g*g*k+c;a[6]=
b*g*k+d*l;a[7]=0;a[8]=d*b*k+g*l;a[9]=g*b*k-d*l;a[10]=b*b*k+c;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.fromXRotation=function(a,c){var b=Math.sin(c),n=Math.cos(c);a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=n;a[6]=b;a[7]=0;a[8]=0;a[9]=-b;a[10]=n;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.fromYRotation=function(a,c){var b=Math.sin(c),n=Math.cos(c);a[0]=n;a[1]=0;a[2]=-b;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=b;a[9]=0;a[10]=n;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.fromZRotation=
function(a,c){var b=Math.sin(c),n=Math.cos(c);a[0]=n;a[1]=b;a[2]=0;a[3]=0;a[4]=-b;a[5]=n;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.fromRotationTranslation=function(a,c,b){var d=c[0],g=c[1],l=c[2],k=c[3],e=d+d,f=g+g,h=l+l;c=d*e;var m=d*f,d=d*h,t=g*f,g=g*h,l=l*h,e=k*e,f=k*f,k=k*h;a[0]=1-(t+l);a[1]=m+k;a[2]=d-f;a[3]=0;a[4]=m-k;a[5]=1-(c+l);a[6]=g+e;a[7]=0;a[8]=d+f;a[9]=g-e;a[10]=1-(c+t);a[11]=0;a[12]=b[0];a[13]=b[1];a[14]=b[2];a[15]=1;return a};b.fromRotationTranslationScale=
function(a,c,b,n){var d=c[0],l=c[1],k=c[2],e=c[3],f=d+d,h=l+l,m=k+k;c=d*f;var t=d*h,d=d*m,x=l*h,l=l*m,k=k*m,f=e*f,h=e*h,e=e*m,m=n[0],q=n[1];n=n[2];a[0]=(1-(x+k))*m;a[1]=(t+e)*m;a[2]=(d-h)*m;a[3]=0;a[4]=(t-e)*q;a[5]=(1-(c+k))*q;a[6]=(l+f)*q;a[7]=0;a[8]=(d+h)*n;a[9]=(l-f)*n;a[10]=(1-(c+x))*n;a[11]=0;a[12]=b[0];a[13]=b[1];a[14]=b[2];a[15]=1;return a};b.fromRotationTranslationScaleOrigin=function(a,c,b,n,g){var d=c[0],k=c[1],e=c[2],f=c[3],h=d+d,m=k+k,t=e+e;c=d*h;var x=d*m,d=d*t,q=k*m,k=k*t,e=e*t,h=f*
h,m=f*m,f=f*t,t=n[0],w=n[1];n=n[2];var u=g[0],v=g[1];g=g[2];a[0]=(1-(q+e))*t;a[1]=(x+f)*t;a[2]=(d-m)*t;a[3]=0;a[4]=(x-f)*w;a[5]=(1-(c+e))*w;a[6]=(k+h)*w;a[7]=0;a[8]=(d+m)*n;a[9]=(k-h)*n;a[10]=(1-(c+q))*n;a[11]=0;a[12]=b[0]+u-(a[0]*u+a[4]*v+a[8]*g);a[13]=b[1]+v-(a[1]*u+a[5]*v+a[9]*g);a[14]=b[2]+g-(a[2]*u+a[6]*v+a[10]*g);a[15]=1;return a};b.fromQuat=function(a,c){var b=c[0],n=c[1],g=c[2],l=c[3],k=b+b,e=n+n,f=g+g,b=b*k,h=n*k,n=n*e,m=g*k,t=g*e,g=g*f,k=l*k,e=l*e,l=l*f;a[0]=1-n-g;a[1]=h+l;a[2]=m-e;a[3]=
0;a[4]=h-l;a[5]=1-b-g;a[6]=t+k;a[7]=0;a[8]=m+e;a[9]=t-k;a[10]=1-b-n;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};b.frustum=function(a,c,b,n,g,l,k){var d=1/(b-c),e=1/(g-n),f=1/(l-k);a[0]=2*l*d;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=2*l*e;a[6]=0;a[7]=0;a[8]=(b+c)*d;a[9]=(g+n)*e;a[10]=(k+l)*f;a[11]=-1;a[12]=0;a[13]=0;a[14]=k*l*2*f;a[15]=0;return a};b.perspective=function(a,c,b,n,g){c=1/Math.tan(c/2);var d=1/(n-g);a[0]=c/b;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=c;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=(g+n)*d;a[11]=
-1;a[12]=0;a[13]=0;a[14]=2*g*n*d;a[15]=0;return a};b.perspectiveFromFieldOfView=function(a,c,b,n){var d=Math.tan(c.upDegrees*Math.PI/180),l=Math.tan(c.downDegrees*Math.PI/180),k=Math.tan(c.leftDegrees*Math.PI/180);c=Math.tan(c.rightDegrees*Math.PI/180);var e=2/(k+c),f=2/(d+l);a[0]=e;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=f;a[6]=0;a[7]=0;a[8]=-((k-c)*e*.5);a[9]=(d-l)*f*.5;a[10]=n/(b-n);a[11]=-1;a[12]=0;a[13]=0;a[14]=n*b/(b-n);a[15]=0;return a};b.ortho=function(a,c,b,n,g,l,k){var d=1/(c-b),e=1/(n-g),f=1/
(l-k);a[0]=-2*d;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=-2*e;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=2*f;a[11]=0;a[12]=(c+b)*d;a[13]=(g+n)*e;a[14]=(k+l)*f;a[15]=1;return a};b.lookAt=function(a,c,d,n){var g,l,e,f,h,F,D,t,x=c[0],q=c[1];c=c[2];e=n[0];f=n[1];l=n[2];D=d[0];n=d[1];g=d[2];if(Math.abs(x-D)<m.EPSILON&&Math.abs(q-n)<m.EPSILON&&Math.abs(c-g)<m.EPSILON)return b.identity(a);d=x-D;n=q-n;D=c-g;t=1/Math.sqrt(d*d+n*n+D*D);d*=t;n*=t;D*=t;g=f*D-l*n;l=l*d-e*D;e=e*n-f*d;(t=Math.sqrt(g*g+l*l+e*e))?(t=1/t,g*=t,l*=t,
e*=t):e=l=g=0;f=n*e-D*l;h=D*g-d*e;F=d*l-n*g;(t=Math.sqrt(f*f+h*h+F*F))?(t=1/t,f*=t,h*=t,F*=t):F=h=f=0;a[0]=g;a[1]=f;a[2]=d;a[3]=0;a[4]=l;a[5]=h;a[6]=n;a[7]=0;a[8]=e;a[9]=F;a[10]=D;a[11]=0;a[12]=-(g*x+l*q+e*c);a[13]=-(f*x+h*q+F*c);a[14]=-(d*x+n*q+D*c);a[15]=1;return a};b.str=function(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"};b.frob=function(a){return Math.sqrt(Math.pow(a[0],
2)+Math.pow(a[1],2)+Math.pow(a[2],2)+Math.pow(a[3],2)+Math.pow(a[4],2)+Math.pow(a[5],2)+Math.pow(a[6],2)+Math.pow(a[7],2)+Math.pow(a[8],2)+Math.pow(a[9],2)+Math.pow(a[10],2)+Math.pow(a[11],2)+Math.pow(a[12],2)+Math.pow(a[13],2)+Math.pow(a[14],2)+Math.pow(a[15],2))};e.exports=b},function(e,f,h){var m=h(1),b=h(4),a=h(7);f=h(8);var c={create:function(){var a=new m.ARRAY_TYPE(4);a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a}};c.rotationTo=function(){var b=a.create(),n=a.fromValues(1,0,0),g=a.fromValues(0,1,0);
return function(d,e,f){var l=a.dot(e,f);if(-.999999>l)return a.cross(b,n,e),1E-6>a.length(b)&&a.cross(b,g,e),a.normalize(b,b),c.setAxisAngle(d,b,Math.PI),d;if(.999999<l)return d[0]=0,d[1]=0,d[2]=0,d[3]=1,d;a.cross(b,e,f);d[0]=b[0];d[1]=b[1];d[2]=b[2];d[3]=1+l;return c.normalize(d,d)}}();c.setAxes=function(){var a=b.create();return function(b,d,e,k){a[0]=e[0];a[3]=e[1];a[6]=e[2];a[1]=k[0];a[4]=k[1];a[7]=k[2];a[2]=-d[0];a[5]=-d[1];a[8]=-d[2];return c.normalize(b,c.fromMat3(b,a))}}();c.clone=f.clone;
c.fromValues=f.fromValues;c.copy=f.copy;c.set=f.set;c.identity=function(a){a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a};c.setAxisAngle=function(a,c,b){b*=.5;var d=Math.sin(b);a[0]=d*c[0];a[1]=d*c[1];a[2]=d*c[2];a[3]=Math.cos(b);return a};c.add=f.add;c.multiply=function(a,c,b){var d=c[0],g=c[1],n=c[2];c=c[3];var e=b[0],f=b[1],h=b[2];b=b[3];a[0]=d*b+c*e+g*h-n*f;a[1]=g*b+c*f+n*e-d*h;a[2]=n*b+c*h+d*f-g*e;a[3]=c*b-d*e-g*f-n*h;return a};c.mul=c.multiply;c.scale=f.scale;c.rotateX=function(a,c,b){b*=.5;var d=c[0],
g=c[1],n=c[2];c=c[3];var e=Math.sin(b);b=Math.cos(b);a[0]=d*b+c*e;a[1]=g*b+n*e;a[2]=n*b-g*e;a[3]=c*b-d*e;return a};c.rotateY=function(a,c,b){b*=.5;var d=c[0],g=c[1],n=c[2];c=c[3];var e=Math.sin(b);b=Math.cos(b);a[0]=d*b-n*e;a[1]=g*b+c*e;a[2]=n*b+d*e;a[3]=c*b-g*e;return a};c.rotateZ=function(a,c,b){b*=.5;var d=c[0],g=c[1],e=c[2];c=c[3];var n=Math.sin(b);b=Math.cos(b);a[0]=d*b+g*n;a[1]=g*b-d*n;a[2]=e*b+c*n;a[3]=c*b-e*n;return a};c.calculateW=function(a,c){var b=c[0],d=c[1],e=c[2];a[0]=b;a[1]=d;a[2]=
e;a[3]=Math.sqrt(Math.abs(1-b*b-d*d-e*e));return a};c.dot=f.dot;c.lerp=f.lerp;c.slerp=function(a,c,b,e){var d=c[0],g=c[1],n=c[2];c=c[3];var l=b[0],f=b[1],h=b[2];b=b[3];var m,q,w;q=d*l+g*f+n*h+c*b;0>q&&(q=-q,l=-l,f=-f,h=-h,b=-b);1E-6<1-q?(m=Math.acos(q),w=Math.sin(m),q=Math.sin((1-e)*m)/w,e=Math.sin(e*m)/w):q=1-e;a[0]=q*d+e*l;a[1]=q*g+e*f;a[2]=q*n+e*h;a[3]=q*c+e*b;return a};c.sqlerp=function(){var a=c.create(),b=c.create();return function(d,e,n,f,h,m){c.slerp(a,e,h,m);c.slerp(b,n,f,m);c.slerp(d,a,
b,2*m*(1-m));return d}}();c.invert=function(a,c){var b=c[0],d=c[1],e=c[2],n=c[3],f=b*b+d*d+e*e+n*n,f=f?1/f:0;a[0]=-b*f;a[1]=-d*f;a[2]=-e*f;a[3]=n*f;return a};c.conjugate=function(a,c){a[0]=-c[0];a[1]=-c[1];a[2]=-c[2];a[3]=c[3];return a};c.length=f.length;c.len=c.length;c.squaredLength=f.squaredLength;c.sqrLen=c.squaredLength;c.normalize=f.normalize;c.fromMat3=function(a,c){var b=c[0]+c[4]+c[8];if(0<b)b=Math.sqrt(b+1),a[3]=.5*b,b=.5/b,a[0]=(c[5]-c[7])*b,a[1]=(c[6]-c[2])*b,a[2]=(c[1]-c[3])*b;else{var d=
0;c[4]>c[0]&&(d=1);c[8]>c[3*d+d]&&(d=2);var e=(d+1)%3,n=(d+2)%3,b=Math.sqrt(c[3*d+d]-c[3*e+e]-c[3*n+n]+1);a[d]=.5*b;b=.5/b;a[3]=(c[3*e+n]-c[3*n+e])*b;a[e]=(c[3*e+d]+c[3*d+e])*b;a[n]=(c[3*n+d]+c[3*d+n])*b}return a};c.str=function(a){return"quat("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};e.exports=c},function(e,f,h){var m=h(1),b={create:function(){var a=new m.ARRAY_TYPE(3);a[0]=0;a[1]=0;a[2]=0;return a},clone:function(a){var c=new m.ARRAY_TYPE(3);c[0]=a[0];c[1]=a[1];c[2]=a[2];return c},fromValues:function(a,
c,b){var d=new m.ARRAY_TYPE(3);d[0]=a;d[1]=c;d[2]=b;return d},copy:function(a,c){a[0]=c[0];a[1]=c[1];a[2]=c[2];return a},set:function(a,c,b,e){a[0]=c;a[1]=b;a[2]=e;return a},add:function(a,c,b){a[0]=c[0]+b[0];a[1]=c[1]+b[1];a[2]=c[2]+b[2];return a},subtract:function(a,c,b){a[0]=c[0]-b[0];a[1]=c[1]-b[1];a[2]=c[2]-b[2];return a}};b.sub=b.subtract;b.multiply=function(a,c,b){a[0]=c[0]*b[0];a[1]=c[1]*b[1];a[2]=c[2]*b[2];return a};b.mul=b.multiply;b.divide=function(a,c,b){a[0]=c[0]/b[0];a[1]=c[1]/b[1];
a[2]=c[2]/b[2];return a};b.div=b.divide;b.min=function(a,c,b){a[0]=Math.min(c[0],b[0]);a[1]=Math.min(c[1],b[1]);a[2]=Math.min(c[2],b[2]);return a};b.max=function(a,c,b){a[0]=Math.max(c[0],b[0]);a[1]=Math.max(c[1],b[1]);a[2]=Math.max(c[2],b[2]);return a};b.scale=function(a,c,b){a[0]=c[0]*b;a[1]=c[1]*b;a[2]=c[2]*b;return a};b.scaleAndAdd=function(a,c,b,e){a[0]=c[0]+b[0]*e;a[1]=c[1]+b[1]*e;a[2]=c[2]+b[2]*e;return a};b.distance=function(a,c){var b=c[0]-a[0],e=c[1]-a[1],g=c[2]-a[2];return Math.sqrt(b*
b+e*e+g*g)};b.dist=b.distance;b.squaredDistance=function(a,c){var b=c[0]-a[0],e=c[1]-a[1],g=c[2]-a[2];return b*b+e*e+g*g};b.sqrDist=b.squaredDistance;b.length=function(a){var c=a[0],b=a[1];a=a[2];return Math.sqrt(c*c+b*b+a*a)};b.len=b.length;b.squaredLength=function(a){var c=a[0],b=a[1];a=a[2];return c*c+b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,c){a[0]=-c[0];a[1]=-c[1];a[2]=-c[2];return a};b.inverse=function(a,c){a[0]=1/c[0];a[1]=1/c[1];a[2]=1/c[2];return a};b.normalize=function(a,c){var b=
c[0],e=c[1],g=c[2],b=b*b+e*e+g*g;0<b&&(b=1/Math.sqrt(b),a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b);return a};b.dot=function(a,c){return a[0]*c[0]+a[1]*c[1]+a[2]*c[2]};b.cross=function(a,c,b){var d=c[0],e=c[1];c=c[2];var f=b[0],k=b[1];b=b[2];a[0]=e*b-c*k;a[1]=c*f-d*b;a[2]=d*k-e*f;return a};b.lerp=function(a,c,b,e){var d=c[0],f=c[1];c=c[2];a[0]=d+e*(b[0]-d);a[1]=f+e*(b[1]-f);a[2]=c+e*(b[2]-c);return a};b.hermite=function(a,c,b,e,g,f){var d=f*f,n=d*(2*f-3)+1,l=d*(f-2)+f,h=d*(f-1);f=d*(3-2*f);a[0]=c[0]*n+b[0]*
l+e[0]*h+g[0]*f;a[1]=c[1]*n+b[1]*l+e[1]*h+g[1]*f;a[2]=c[2]*n+b[2]*l+e[2]*h+g[2]*f;return a};b.bezier=function(a,c,b,e,g,f){var d=1-f,n=d*d,l=f*f,h=n*d,n=3*f*n,d=3*l*d;f*=l;a[0]=c[0]*h+b[0]*n+e[0]*d+g[0]*f;a[1]=c[1]*h+b[1]*n+e[1]*d+g[1]*f;a[2]=c[2]*h+b[2]*n+e[2]*d+g[2]*f;return a};b.random=function(a,c){c=c||1;var b=2*m.RANDOM()*Math.PI,e=2*m.RANDOM()-1,g=Math.sqrt(1-e*e)*c;a[0]=Math.cos(b)*g;a[1]=Math.sin(b)*g;a[2]=e*c;return a};b.transformMat4=function(a,c,b){var d=c[0],e=c[1];c=c[2];var f=b[3]*
d+b[7]*e+b[11]*c+b[15],f=f||1;a[0]=(b[0]*d+b[4]*e+b[8]*c+b[12])/f;a[1]=(b[1]*d+b[5]*e+b[9]*c+b[13])/f;a[2]=(b[2]*d+b[6]*e+b[10]*c+b[14])/f;return a};b.transformMat3=function(a,c,b){var d=c[0],e=c[1];c=c[2];a[0]=d*b[0]+e*b[3]+c*b[6];a[1]=d*b[1]+e*b[4]+c*b[7];a[2]=d*b[2]+e*b[5]+c*b[8];return a};b.transformQuat=function(a,c,b){var d=c[0],e=c[1],f=c[2];c=b[0];var k=b[1],h=b[2];b=b[3];var m=b*d+k*f-h*e,F=b*e+h*d-c*f,D=b*f+c*e-k*d,d=-c*d-k*e-h*f;a[0]=m*b+d*-c+F*-h-D*-k;a[1]=F*b+d*-k+D*-c-m*-h;a[2]=D*b+
d*-h+m*-k-F*-c;return a};b.rotateX=function(a,b,d,e){var c=[],f=[];c[0]=b[0]-d[0];c[1]=b[1]-d[1];c[2]=b[2]-d[2];f[0]=c[0];f[1]=c[1]*Math.cos(e)-c[2]*Math.sin(e);f[2]=c[1]*Math.sin(e)+c[2]*Math.cos(e);a[0]=f[0]+d[0];a[1]=f[1]+d[1];a[2]=f[2]+d[2];return a};b.rotateY=function(a,b,d,e){var c=[],f=[];c[0]=b[0]-d[0];c[1]=b[1]-d[1];c[2]=b[2]-d[2];f[0]=c[2]*Math.sin(e)+c[0]*Math.cos(e);f[1]=c[1];f[2]=c[2]*Math.cos(e)-c[0]*Math.sin(e);a[0]=f[0]+d[0];a[1]=f[1]+d[1];a[2]=f[2]+d[2];return a};b.rotateZ=function(a,
b,d,e){var c=[],f=[];c[0]=b[0]-d[0];c[1]=b[1]-d[1];c[2]=b[2]-d[2];f[0]=c[0]*Math.cos(e)-c[1]*Math.sin(e);f[1]=c[0]*Math.sin(e)+c[1]*Math.cos(e);f[2]=c[2];a[0]=f[0]+d[0];a[1]=f[1]+d[1];a[2]=f[2]+d[2];return a};b.forEach=function(){var a=b.create();return function(b,d,e,f,h,k){d||(d=3);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;e<f;e+=d)a[0]=b[e],a[1]=b[e+1],a[2]=b[e+2],h(a,a,k),b[e]=a[0],b[e+1]=a[1],b[e+2]=a[2];return b}}();b.angle=function(a,c){var d=b.fromValues(a[0],a[1],a[2]),e=b.fromValues(c[0],
c[1],c[2]);b.normalize(d,d);b.normalize(e,e);d=b.dot(d,e);return 1<d?0:Math.acos(d)};b.str=function(a){return"vec3("+a[0]+", "+a[1]+", "+a[2]+")"};e.exports=b},function(e,f,h){var m=h(1),b={create:function(){var a=new m.ARRAY_TYPE(4);a[0]=0;a[1]=0;a[2]=0;a[3]=0;return a},clone:function(a){var b=new m.ARRAY_TYPE(4);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},fromValues:function(a,b,d,e){var c=new m.ARRAY_TYPE(4);c[0]=a;c[1]=b;c[2]=d;c[3]=e;return c},copy:function(a,b){a[0]=b[0];a[1]=b[1];a[2]=
b[2];a[3]=b[3];return a},set:function(a,b,d,e,f){a[0]=b;a[1]=d;a[2]=e;a[3]=f;return a},add:function(a,b,d){a[0]=b[0]+d[0];a[1]=b[1]+d[1];a[2]=b[2]+d[2];a[3]=b[3]+d[3];return a},subtract:function(a,b,d){a[0]=b[0]-d[0];a[1]=b[1]-d[1];a[2]=b[2]-d[2];a[3]=b[3]-d[3];return a}};b.sub=b.subtract;b.multiply=function(a,b,d){a[0]=b[0]*d[0];a[1]=b[1]*d[1];a[2]=b[2]*d[2];a[3]=b[3]*d[3];return a};b.mul=b.multiply;b.divide=function(a,b,d){a[0]=b[0]/d[0];a[1]=b[1]/d[1];a[2]=b[2]/d[2];a[3]=b[3]/d[3];return a};b.div=
b.divide;b.min=function(a,b,d){a[0]=Math.min(b[0],d[0]);a[1]=Math.min(b[1],d[1]);a[2]=Math.min(b[2],d[2]);a[3]=Math.min(b[3],d[3]);return a};b.max=function(a,b,d){a[0]=Math.max(b[0],d[0]);a[1]=Math.max(b[1],d[1]);a[2]=Math.max(b[2],d[2]);a[3]=Math.max(b[3],d[3]);return a};b.scale=function(a,b,d){a[0]=b[0]*d;a[1]=b[1]*d;a[2]=b[2]*d;a[3]=b[3]*d;return a};b.scaleAndAdd=function(a,b,d,e){a[0]=b[0]+d[0]*e;a[1]=b[1]+d[1]*e;a[2]=b[2]+d[2]*e;a[3]=b[3]+d[3]*e;return a};b.distance=function(a,b){var c=b[0]-
a[0],e=b[1]-a[1],f=b[2]-a[2],h=b[3]-a[3];return Math.sqrt(c*c+e*e+f*f+h*h)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1],f=b[2]-a[2],h=b[3]-a[3];return c*c+e*e+f*f+h*h};b.sqrDist=b.squaredDistance;b.length=function(a){var b=a[0],d=a[1],e=a[2];a=a[3];return Math.sqrt(b*b+d*d+e*e+a*a)};b.len=b.length;b.squaredLength=function(a){var b=a[0],d=a[1],e=a[2];a=a[3];return b*b+d*d+e*e+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){a[0]=-b[0];a[1]=-b[1];a[2]=-b[2];a[3]=
-b[3];return a};b.inverse=function(a,b){a[0]=1/b[0];a[1]=1/b[1];a[2]=1/b[2];a[3]=1/b[3];return a};b.normalize=function(a,b){var c=b[0],e=b[1],f=b[2],h=b[3],k=c*c+e*e+f*f+h*h;0<k&&(k=1/Math.sqrt(k),a[0]=c*k,a[1]=e*k,a[2]=f*k,a[3]=h*k);return a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};b.lerp=function(a,b,d,e){var c=b[0],f=b[1],h=b[2];b=b[3];a[0]=c+e*(d[0]-c);a[1]=f+e*(d[1]-f);a[2]=h+e*(d[2]-h);a[3]=b+e*(d[3]-b);return a};b.random=function(a,c){c=c||1;a[0]=m.RANDOM();a[1]=
m.RANDOM();a[2]=m.RANDOM();a[3]=m.RANDOM();b.normalize(a,a);b.scale(a,a,c);return a};b.transformMat4=function(a,b,d){var c=b[0],e=b[1],f=b[2];b=b[3];a[0]=d[0]*c+d[4]*e+d[8]*f+d[12]*b;a[1]=d[1]*c+d[5]*e+d[9]*f+d[13]*b;a[2]=d[2]*c+d[6]*e+d[10]*f+d[14]*b;a[3]=d[3]*c+d[7]*e+d[11]*f+d[15]*b;return a};b.transformQuat=function(a,b,d){var c=b[0],e=b[1],f=b[2],h=d[0],m=d[1],p=d[2];d=d[3];var F=d*c+m*f-p*e,D=d*e+p*c-h*f,t=d*f+h*e-m*c,c=-h*c-m*e-p*f;a[0]=F*d+c*-h+D*-p-t*-m;a[1]=D*d+c*-m+t*-h-F*-p;a[2]=t*d+c*
-p+F*-m-D*-h;a[3]=b[3];return a};b.forEach=function(){var a=b.create();return function(b,d,e,f,h,k){d||(d=4);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;e<f;e+=d)a[0]=b[e],a[1]=b[e+1],a[2]=b[e+2],a[3]=b[e+3],h(a,a,k),b[e]=a[0],b[e+1]=a[1],b[e+2]=a[2],b[e+3]=a[3];return b}}();b.str=function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};e.exports=b},function(e,f,h){var m=h(1),b={create:function(){var a=new m.ARRAY_TYPE(2);a[0]=0;a[1]=0;return a},clone:function(a){var b=new m.ARRAY_TYPE(2);
b[0]=a[0];b[1]=a[1];return b},fromValues:function(a,b){var c=new m.ARRAY_TYPE(2);c[0]=a;c[1]=b;return c},copy:function(a,b){a[0]=b[0];a[1]=b[1];return a},set:function(a,b,d){a[0]=b;a[1]=d;return a},add:function(a,b,d){a[0]=b[0]+d[0];a[1]=b[1]+d[1];return a},subtract:function(a,b,d){a[0]=b[0]-d[0];a[1]=b[1]-d[1];return a}};b.sub=b.subtract;b.multiply=function(a,b,d){a[0]=b[0]*d[0];a[1]=b[1]*d[1];return a};b.mul=b.multiply;b.divide=function(a,b,d){a[0]=b[0]/d[0];a[1]=b[1]/d[1];return a};b.div=b.divide;
b.min=function(a,b,d){a[0]=Math.min(b[0],d[0]);a[1]=Math.min(b[1],d[1]);return a};b.max=function(a,b,d){a[0]=Math.max(b[0],d[0]);a[1]=Math.max(b[1],d[1]);return a};b.scale=function(a,b,d){a[0]=b[0]*d;a[1]=b[1]*d;return a};b.scaleAndAdd=function(a,b,d,e){a[0]=b[0]+d[0]*e;a[1]=b[1]+d[1]*e;return a};b.distance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1];return Math.sqrt(c*c+e*e)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1];return c*c+e*e};b.sqrDist=b.squaredDistance;b.length=
function(a){var b=a[0];a=a[1];return Math.sqrt(b*b+a*a)};b.len=b.length;b.squaredLength=function(a){var b=a[0];a=a[1];return b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){a[0]=-b[0];a[1]=-b[1];return a};b.inverse=function(a,b){a[0]=1/b[0];a[1]=1/b[1];return a};b.normalize=function(a,b){var c=b[0],e=b[1],c=c*c+e*e;0<c&&(c=1/Math.sqrt(c),a[0]=b[0]*c,a[1]=b[1]*c);return a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]};b.cross=function(a,b,d){b=b[0]*d[1]-b[1]*d[0];a[0]=a[1]=0;a[2]=b;return a};
b.lerp=function(a,b,d,e){var c=b[0];b=b[1];a[0]=c+e*(d[0]-c);a[1]=b+e*(d[1]-b);return a};b.random=function(a,b){b=b||1;var c=2*m.RANDOM()*Math.PI;a[0]=Math.cos(c)*b;a[1]=Math.sin(c)*b;return a};b.transformMat2=function(a,b,d){var c=b[0];b=b[1];a[0]=d[0]*c+d[2]*b;a[1]=d[1]*c+d[3]*b;return a};b.transformMat2d=function(a,b,d){var c=b[0];b=b[1];a[0]=d[0]*c+d[2]*b+d[4];a[1]=d[1]*c+d[3]*b+d[5];return a};b.transformMat3=function(a,b,d){var c=b[0];b=b[1];a[0]=d[0]*c+d[3]*b+d[6];a[1]=d[1]*c+d[4]*b+d[7];return a};
b.transformMat4=function(a,b,d){var c=b[0];b=b[1];a[0]=d[0]*c+d[4]*b+d[12];a[1]=d[1]*c+d[5]*b+d[13];return a};b.forEach=function(){var a=b.create();return function(b,d,e,f,h,k){d||(d=2);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;e<f;e+=d)a[0]=b[e],a[1]=b[e+1],h(a,a,k),b[e]=a[0],b[e+1]=a[1];return b}}();b.str=function(a){return"vec2("+a[0]+", "+a[1]+")"};e.exports=b}])});
var gl,Program,Buffer,indexBuffer,indexBufferLength,skyboxBuffer,skyboxProgram,cubemap_texture,terrainProgram,terrainBuffer,terrainIndexBuffer,terrainIndexBufferLength,terrainTexture,terrainDepthmapTexture;window.loadCounter=0;
var scale=.02,orbitDistance=17*scale,zoom=45,camera,object_axys={right:[1,0,0],up:[0,1,0],forward:[0,0,1]},camera_axys={right:[1,0,0],up:[0,1,0],forward:[0,0,1]},aircraft_position=[0,250,0],diffuse_texture,projection=mat4.create(),model=mat4.create(),view=mat4.create(),multiPurposeBuffer=[0,0,0],init=!1,heldkeys={lefta:!1,righta:!1,upa:!1,downa:!1,shift:!1},speedDiv,text;
function webGLStart(){var e=document.getElementById("canvas");e.width=window.innerWidth;e.height=window.innerHeight;speedDiv=document.createElement("div");speedDiv.id="speed";text=document.createTextNode("200");speedDiv.appendChild(text);document.body.appendChild(speedDiv);window.addEventListener("keydown",keypressed);window.addEventListener("keyup",keyrelease);var f=["webgl","experimental-webgl","webkit-3d","mozwebgl"],h;for(h in f)try{if((gl=e.getContext(f[h],{stencil:!0}))&&"function"==typeof gl.getParameter)break}catch(a){}null==
gl&&alert("could not initialize webGL");Program=getShader("vertex","fragment",!1);Program.a1=gl.getAttribLocation(Program,"pos");Program.a2=gl.getAttribLocation(Program,"normal");Program.a3=gl.getAttribLocation(Program,"uv");Program.projection=gl.getUniformLocation(Program,"projection");Program.model=gl.getUniformLocation(Program,"model");Program.scale=gl.getUniformLocation(Program,"scale");Program.view=gl.getUniformLocation(Program,"view");Program.diffuse=gl.getUniformLocation(Program,"diffuse");
Program.skybox=gl.getUniformLocation(Program,"skybox");Program.eyepos=gl.getUniformLocation(Program,"eyepos");displayQuadProgramInit();godRayProgramInit();radialBlurProgramInit();initOffscreenFBO();initPingPongFBOs();initMainFBO();Buffer=gl.createBuffer();indexBuffer=gl.createBuffer();terrainBuffer=gl.createBuffer();terrainIndexBuffer=gl.createBuffer();var m=new XMLHttpRequest;m.onreadystatechange=function(a,b){return function(){if(4==m.readyState&&200==m.status){var c=JSON.parse(m.responseText);
indexBufferLength=loadModelToBuffer(a,b,c)}}}(Buffer,indexBuffer);m.open("GET","untitled3.json",!0);m.send();var b=new XMLHttpRequest;b.onreadystatechange=function(a,c){return function(){if(4==b.readyState&&200==b.status){var d=JSON.parse(b.responseText);terrainIndexBufferLength=loadModelToBufferTBN(a,c,d)}}}(terrainBuffer,terrainIndexBuffer);b.open("GET","terrain3.json",!0);b.send();skyboxProgram=getShader("skyboxvertex","skyboxfragment",!1);skyboxProgram.a1=gl.getAttribLocation(skyboxProgram,"pos");
skyboxProgram.projection=gl.getUniformLocation(skyboxProgram,"projection");skyboxProgram.model=gl.getUniformLocation(skyboxProgram,"model");skyboxProgram.view=gl.getUniformLocation(skyboxProgram,"view");skyboxProgram.cubeMap=gl.getUniformLocation(skyboxProgram,"cubeMap");cubevertices=[-3,3,-3,-3,-3,-3,3,-3,-3,3,-3,-3,3,3,-3,-3,3,-3,-3,-3,3,-3,-3,-3,-3,3,-3,-3,3,-3,-3,3,3,-3,-3,3,3,-3,-3,3,-3,3,3,3,3,3,3,3,3,3,-3,3,-3,-3,-3,-3,3,-3,3,3,3,3,3,3,3,3,3,-3,3,-3,-3,3,-3,3,-3,3,3,-3,3,3,3,3,3,3,-3,3,3,-3,
3,-3,-3,-3,-3,-3,-3,3,3,-3,-3,3,-3,-3,-3,-3,3,3,-3,3];skyboxBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,skyboxBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(cubevertices),gl.STATIC_DRAW);terrainProgram=getShader("terrainvertex","terrainfragment",!1);terrainProgram.a1=gl.getAttribLocation(terrainProgram,"pos");terrainProgram.a2=gl.getAttribLocation(terrainProgram,"normal");terrainProgram.a3=gl.getAttribLocation(terrainProgram,"tangents");terrainProgram.a4=gl.getAttribLocation(terrainProgram,
"bitangents");terrainProgram.a5=gl.getAttribLocation(terrainProgram,"coord");terrainProgram.projection=gl.getUniformLocation(terrainProgram,"projection");terrainProgram.model=gl.getUniformLocation(terrainProgram,"model");terrainProgram.view=gl.getUniformLocation(terrainProgram,"view");terrainProgram.terrain=gl.getUniformLocation(terrainProgram,"terrain");terrainProgram.depthmap=gl.getUniformLocation(terrainProgram,"depthmap");terrainProgram.aircraftpos=gl.getUniformLocation(terrainProgram,"aircraftpos");
terrainProgram.skybox=gl.getUniformLocation(terrainProgram,"skybox");terrainProgram.eyepos=gl.getUniformLocation(terrainProgram,"eyepos");terrainTexture=getTexture("Crop_Fields.jpg");terrainDepthmapTexture=getTexture("depthmap2.jpg");cubemap_texture=cubeMapTexture();diffuse_texture=getTexture("p1.png");requestAnimationFrame(draw)}var then=0;
function draw(e){requestAnimationFrame(draw);2==window.loadCounter&&initAudio();if(!(2>window.loadCounter)){if(heldkeys.shift){var f=1-(100*speed-200)/2300;Math.pow(f,2);speed+=25>speed?.1*f:0;3==window.loadCounter&&biquadFilter&&(f=(speed-1.9)/23,biquadFilter.frequency.value=9440-9300*f,gainNode.gain.value=.7+.3*f)}heldkeys.shift||(speed-=.01*speed,speed=2>speed?2:speed,3==window.loadCounter&&biquadFilter&&(f=(speed-1.9)/23,biquadFilter.frequency.value=9440-9300*f,gainNode.gain.value=.7+.3*f));heldkeys.righta&&
(forceRight+=.045,forceRight=1<forceRight?1:forceRight,rotate(1));heldkeys.lefta&&(forceLeft+=.045,forceLeft=1<forceLeft?1:forceLeft,rotate(0));heldkeys.upa&&rotatepitch(0);heldkeys.downa&&rotatepitch(1);0<forceRight&&!heldkeys.righta&&(forceRight-=.075,forceRight=0>forceRight?0:forceRight,rotate(1));0<forceLeft&&!heldkeys.lefta&&(forceLeft-=.075,forceLeft=0>forceLeft?0:forceLeft,rotate(0));f="spd\u00a0\u00a0";10<=speed&&(f="spd ");text.nodeValue=f+(100*speed).toFixed(0);aircraft_position[0]+=-object_axys.forward[0]*
speed;aircraft_position[1]+=-object_axys.forward[1]*speed;aircraft_position[2]+=-object_axys.forward[2]*speed;alignCameraz(e);then=.001*e;mat4.identity(model);mat4.identity(view);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,1,10);gl.bindFramebuffer(gl.FRAMEBUFFER,MainFBO);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.useProgram(skyboxProgram);gl.bindBuffer(gl.ARRAY_BUFFER,skyboxBuffer);gl.enableVertexAttribArray(skyboxProgram.a1);
e=Float32Array.BYTES_PER_ELEMENT;gl.vertexAttribPointer(skyboxProgram.a1,3,gl.FLOAT,!1,0*e,0*e);gl.uniformMatrix4fv(skyboxProgram.projection,!1,projection);gl.uniformMatrix4fv(skyboxProgram.model,!1,model);gl.uniformMatrix4fv(skyboxProgram.view,!1,lookAt);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_CUBE_MAP,cubemap_texture);gl.uniform1i(skyboxProgram.cubeMap,0);gl.drawArrays(gl.TRIANGLES,0,36);mat4.identity(model);mat4.identity(view);gl.enable(gl.DEPTH_TEST);gl.useProgram(terrainProgram);
gl.bindBuffer(gl.ARRAY_BUFFER,terrainBuffer);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,terrainIndexBuffer);gl.enableVertexAttribArray(terrainProgram.a1);gl.enableVertexAttribArray(terrainProgram.a2);gl.enableVertexAttribArray(terrainProgram.a3);gl.enableVertexAttribArray(terrainProgram.a4);gl.enableVertexAttribArray(terrainProgram.a5);gl.vertexAttribPointer(terrainProgram.a1,3,gl.FLOAT,!1,14*e,0*e);gl.vertexAttribPointer(terrainProgram.a2,3,gl.FLOAT,!1,14*e,3*e);gl.vertexAttribPointer(terrainProgram.a3,
3,gl.FLOAT,!1,14*e,6*e);gl.vertexAttribPointer(terrainProgram.a4,3,gl.FLOAT,!1,14*e,9*e);gl.vertexAttribPointer(terrainProgram.a5,2,gl.FLOAT,!1,14*e,12*e);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,2,3E5);mat4.translate(model,model,[0,-aircraft_position[1]-14E3,0]);mat4.scale(model,model,[3E5,3E5,3E5]);gl.uniformMatrix4fv(terrainProgram.projection,!1,projection);gl.uniformMatrix4fv(terrainProgram.model,!1,model);gl.uniformMatrix4fv(terrainProgram.view,!1,lookAt);gl.activeTexture(gl.TEXTURE0);
gl.bindTexture(gl.TEXTURE_2D,terrainTexture);gl.uniform1i(terrainProgram.terrain,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_CUBE_MAP,cubemap_texture);gl.uniform1i(terrainProgram.skybox,1);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,terrainDepthmapTexture);gl.uniform1i(terrainProgram.depthmap,2);gl.uniform3f(terrainProgram.aircraftpos,aircraft_position[0],aircraft_position[1],aircraft_position[2]);gl.uniform3f(terrainProgram.eyepos,0-slantedDirection[0]*orbitDistance,
0-slantedDirection[1]*orbitDistance,0-slantedDirection[2]*orbitDistance);gl.drawElements(gl.TRIANGLES,terrainIndexBufferLength,gl.UNSIGNED_SHORT,0);mat4.identity(model);mat4.identity(view);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,.1,100);gl.enable(gl.DEPTH_TEST);gl.useProgram(Program);gl.bindBuffer(gl.ARRAY_BUFFER,Buffer);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.enableVertexAttribArray(Program.a1);gl.enableVertexAttribArray(Program.a2);gl.enableVertexAttribArray(Program.a3);
gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,8*e,0*e);gl.vertexAttribPointer(Program.a2,3,gl.FLOAT,!1,8*e,3*e);gl.vertexAttribPointer(Program.a3,2,gl.FLOAT,!1,8*e,6*e);e=new glMatrix.ARRAY_TYPE(16);e[0]=object_axys.right[0];e[1]=object_axys.up[0];e[2]=object_axys.forward[0];e[3]=0;e[4]=object_axys.right[1];e[5]=object_axys.up[1];e[6]=object_axys.forward[1];e[7]=0;e[8]=object_axys.right[2];e[9]=object_axys.up[2];e[10]=object_axys.forward[2];e[11]=0;e[12]=0;e[13]=0;e[14]=0;e[15]=1;mat4.transpose(e,
e);mat4.scale(model,model,[scale,scale,scale]);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,e);gl.uniformMatrix4fv(Program.scale,!1,model);gl.uniformMatrix4fv(Program.view,!1,lookAt);gl.uniform3f(Program.eyepos,0-slantedDirection[0]*orbitDistance,0-slantedDirection[1]*orbitDistance,0-slantedDirection[2]*orbitDistance);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,diffuse_texture);gl.uniform1i(Program.diffuse,0);gl.activeTexture(gl.TEXTURE1);
gl.bindTexture(gl.TEXTURE_2D,cubemap_texture);gl.uniform1i(Program.skybox,1);gl.drawElements(gl.TRIANGLES,indexBufferLength,gl.UNSIGNED_SHORT,0);mat4.identity(model);mat4.identity(view);drawGodRays();displayLightFBOinQuad()}}
function getTexture(e){var f=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,f);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.bindTexture(gl.TEXTURE_2D,null);var h=new Image;h.onload=function(e,b){return function(){gl.bindTexture(gl.TEXTURE_2D,e);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,
!1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,b);gl.generateMipmap(gl.TEXTURE_2D);gl.bindTexture(gl.TEXTURE_2D,null)}}(f,h);h.src=e;return f}var speed=2;function keypressed(e){37==e.keyCode&&(heldkeys.righta=!0);39==e.keyCode&&(heldkeys.lefta=!0);38==e.keyCode&&(heldkeys.upa=!0);40==e.keyCode&&(heldkeys.downa=!0);16==e.keyCode&&(heldkeys.shift=!0)}quadraticPitchFloat=quadraticBankFloat=.01;
function keyrelease(e){37==e.keyCode&&(heldkeys.righta=!1);39==e.keyCode&&(heldkeys.lefta=!1);38==e.keyCode&&(heldkeys.upa=!1);40==e.keyCode&&(heldkeys.downa=!1);16==e.keyCode&&(heldkeys.shift=!1)}var forceRight=0,forceLeft=0;
function rotate(e){var f=.034*Math.pow(1==e?forceRight:forceLeft,1.2);0==e&&(f=-f);e=quat.create();var h=vec3.fromValues(object_axys.forward[0],object_axys.forward[1],object_axys.forward[2]),m=vec3.fromValues(object_axys.right[0],object_axys.right[1],object_axys.right[2]),b=vec3.fromValues(object_axys.up[0],object_axys.up[1],object_axys.up[2]);quat.setAxisAngle(e,h,f);vec3.transformQuat(b,b,e);vec3.transformQuat(m,m,e);vec3.normalize(b,b);vec3.normalize(m,m);object_axys.up[0]=b[0];object_axys.up[1]=
b[1];object_axys.up[2]=b[2];object_axys.right[0]=m[0];object_axys.right[1]=m[1];object_axys.right[2]=m[2]}
function rotatepitch(e){var f=.017;0==e&&(f=-f);e=quat.create();var h=vec3.fromValues(object_axys.forward[0],object_axys.forward[1],object_axys.forward[2]),m=vec3.fromValues(object_axys.right[0],object_axys.right[1],object_axys.right[2]),b=vec3.fromValues(object_axys.up[0],object_axys.up[1],object_axys.up[2]);quat.setAxisAngle(e,m,f);vec3.transformQuat(h,h,e);vec3.transformQuat(b,b,e);vec3.normalize(h,h);vec3.normalize(b,b);object_axys.forward[0]=h[0];object_axys.forward[1]=h[1];object_axys.forward[2]=
h[2];object_axys.up[0]=b[0];object_axys.up[1]=b[1];object_axys.up[2]=b[2]}var lookAt=mat4.create(),aircraft_dir=[0,0,0],aircraft_up=[0,0,0],aircraft_lookat=[0,0,0],rotator=0,slantedDirection=[0,0,0];
function alignCamera(e){aircraft_dir[0]=-object_axys.forward[0];aircraft_dir[1]=-object_axys.forward[1];aircraft_dir[2]=-object_axys.forward[2];aircraft_up[0]=object_axys.up[0];aircraft_up[1]=object_axys.up[1];aircraft_up[2]=object_axys.up[2];slantedDirection[0]=aircraft_dir[0]-.07*aircraft_up[0];slantedDirection[1]=aircraft_dir[1]-.07*aircraft_up[1];slantedDirection[2]=aircraft_dir[2]-.07*aircraft_up[2];vec3.normalize(slantedDirection,slantedDirection);e=new glMatrix.ARRAY_TYPE(16);e[0]=object_axys.right[0];
e[1]=object_axys.up[0];e[2]=object_axys.forward[0];e[3]=aircraft_position[0]-slantedDirection[0]*orbitDistance;e[4]=object_axys.right[1];e[5]=object_axys.up[1];e[6]=object_axys.forward[1];e[7]=aircraft_position[1]-slantedDirection[1]*orbitDistance;e[8]=object_axys.right[2];e[9]=object_axys.up[2];e[10]=object_axys.forward[2];e[11]=aircraft_position[2]-slantedDirection[2]*orbitDistance;e[12]=0;e[13]=0;e[14]=0;e[15]=1;mat4.transpose(e,e);var f=mat4.create();rotator+=.0032;var h=[0,0,-1];vec3.rotateY(h,
h,[0,0,0],rotator);var m=[-slantedDirection[0],-slantedDirection[1],-slantedDirection[2]],b=quat.create();quat.setAxisAngle(b,object_axys.up,rotator);vec3.transformQuat(m,m,b);h[0]*=orbitDistance;h[1]*=orbitDistance;h[2]*=orbitDistance;mat4.identity(lookAt);mat4.invert(f,e);mat4.multiply(lookAt,lookAt,f)}
function alignCameraz(e){e=[object_axys.up[0]-camera_axys.up[0],object_axys.up[1]-camera_axys.up[1],object_axys.up[2]-camera_axys.up[2]];camera_axys.up[0]+=.1*e[0];camera_axys.up[1]+=.1*e[1];camera_axys.up[2]+=.1*e[2];e=[object_axys.forward[0]-camera_axys.forward[0],object_axys.forward[1]-camera_axys.forward[1],object_axys.forward[2]-camera_axys.forward[2]];camera_axys.forward[0]+=.1*e[0];camera_axys.forward[1]+=.1*e[1];camera_axys.forward[2]+=.1*e[2];e=[object_axys.right[0]-camera_axys.right[0],
object_axys.right[1]-camera_axys.right[1],object_axys.right[2]-camera_axys.right[2]];camera_axys.right[0]+=.1*e[0];camera_axys.right[1]+=.1*e[1];camera_axys.right[2]+=.1*e[2];e=new glMatrix.ARRAY_TYPE(16);e[0]=camera_axys.right[0];e[1]=camera_axys.up[0];e[2]=camera_axys.forward[0];e[3]=0;e[4]=camera_axys.right[1];e[5]=camera_axys.up[1];e[6]=camera_axys.forward[1];e[7]=0;e[8]=camera_axys.right[2];e[9]=camera_axys.up[2];e[10]=camera_axys.forward[2];e[11]=0;e[12]=0;e[13]=0;e[14]=0;e[15]=1;mat4.transpose(e,
e);var f=mat4.create();mat4.invert(f,e);e=mat4.create();mat4.translate(e,e,[0,0,-orbitDistance]);mat4.multiply(e,e,f);var f=quat.create(),h=[0,0,-1];quat.setAxisAngle(f,[1,0,0],-.17);vec3.transformQuat(h,h,f);slantedDirection[0]=-camera_axys.forward[0];slantedDirection[1]=-camera_axys.forward[1];slantedDirection[2]=-camera_axys.forward[2];quat.setAxisAngle(f,camera_axys.right,-.17);vec3.transformQuat(slantedDirection,slantedDirection,f);quat.setAxisAngle(f,[0,1,0],rotator);vec3.transformQuat(h,h,
f);vec3.scale(h,h,orbitDistance);quat.setAxisAngle(f,camera_axys.up,rotator);vec3.transformQuat(slantedDirection,slantedDirection,f);vec3.normalize(slantedDirection,slantedDirection);f=[0-h[0],0-h[1],-orbitDistance-h[2]];mat4.identity(lookAt);mat4.lookAt(lookAt,f,[0,0,-orbitDistance],[0,1,0]);mat4.multiply(lookAt,lookAt,e)}
function alertMat4(e){alert(e[0].toFixed(2)+" "+e[1].toFixed(2)+"  "+e[2].toFixed(2)+" "+e[3].toFixed(2)+"\n"+e[4].toFixed(2)+" "+e[5].toFixed(2)+"  "+e[6].toFixed(2)+" "+e[7].toFixed(2)+"\n"+e[8].toFixed(2)+" "+e[9].toFixed(2)+"  "+e[10].toFixed(2)+" "+e[11].toFixed(2)+"\n"+e[12].toFixed(2)+" "+e[13].toFixed(2)+"  "+e[14].toFixed(2)+" "+e[15].toFixed(2))}
function cubeMapTexture(){var e=gl.createTexture();gl.bindTexture(gl.TEXTURE_CUBE_MAP,e);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MAG_FILTER,gl.LINEAR_MIPMAP_LINEAR);for(var f=[["posx.png",gl.TEXTURE_CUBE_MAP_POSITIVE_X],["negx.png",gl.TEXTURE_CUBE_MAP_NEGATIVE_X],
["posy.png",gl.TEXTURE_CUBE_MAP_POSITIVE_Y],["negy.png",gl.TEXTURE_CUBE_MAP_NEGATIVE_Y],["posz.png",gl.TEXTURE_CUBE_MAP_POSITIVE_Z],["negz.png",gl.TEXTURE_CUBE_MAP_NEGATIVE_Z]],h=0,m=0;m<f.length;m++){var b=f[m][1],a=new Image;a.onload=function(a,b,e){return function(){gl.bindTexture(gl.TEXTURE_CUBE_MAP,a);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!1);gl.texImage2D(b,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,e);h++;6<=h&&gl.generateMipmap(gl.TEXTURE_CUBE_MAP)}}(e,b,a);a.src=f[m][0]}return e}
function loadModelToBuffer(e,f,h){for(var m=[],b=[],a=h.meshes.length,c=0,d=0;d<a;d++){for(var n=h.meshes[d].vertices.length,g=0,l=0;g<n;g+=3,l+=2)m.push(h.meshes[d].vertices[g+0],h.meshes[d].vertices[g+1],h.meshes[d].vertices[g+2],h.meshes[d].normals[g+0],h.meshes[d].normals[g+1],h.meshes[d].normals[g+2],h.meshes[d].texturecoords[0][l+0],h.meshes[d].texturecoords[0][l+1]);g=h.meshes[d].faces.length;for(l=0;l<g;l++){var k=h.meshes[d].faces[l];b.push(k[0]+c);b.push(k[1]+c);b.push(k[2]+c)}c+=n/3}gl.bindBuffer(gl.ARRAY_BUFFER,
e);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,f);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(b),gl.STATIC_DRAW);e=b.length;window.loadCounter++;return e}
function loadModelToBufferTBN(e,f,h){for(var m=[],b=[],a=h.meshes.length,c=0,d=0;d<a;d++){for(var n=h.meshes[d].vertices.length,g=0,l=0;g<n;g+=3,l+=2)m.push(h.meshes[d].vertices[g+0],h.meshes[d].vertices[g+1],h.meshes[d].vertices[g+2],h.meshes[d].normals[g+0],h.meshes[d].normals[g+1],h.meshes[d].normals[g+2],h.meshes[d].tangents[g+0],h.meshes[d].tangents[g+1],h.meshes[d].tangents[g+2],h.meshes[d].bitangents[g+0],h.meshes[d].bitangents[g+1],h.meshes[d].bitangents[g+2],h.meshes[d].texturecoords[0][l+
0],h.meshes[d].texturecoords[0][l+1]);g=h.meshes[d].faces.length;for(l=0;l<g;l++){var k=h.meshes[d].faces[l];b.push(k[0]+c);b.push(k[1]+c);b.push(k[2]+c)}c+=n/3}gl.bindBuffer(gl.ARRAY_BUFFER,e);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(m),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,f);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(b),gl.STATIC_DRAW);e=b.length;window.loadCounter++;return e}var MainFBO,MainFBOtexture;
function initMainFBO(){MainFBO=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,MainFBO);MainFBOtexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,MainFBOtexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,window.innerWidth,window.innerHeight,
0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,MainFBOtexture,0);var e=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,e);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,window.innerWidth,window.innerHeight);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,e);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindRenderbuffer(gl.RENDERBUFFER,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
var LightFBO,LightFBOtexture;
function initOffscreenFBO(){LightFBO=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,LightFBO);LightFBOtexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,LightFBOtexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,window.innerWidth/
2,window.innerHeight/2,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,LightFBOtexture,0);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}var pongFramebuffer,pingFramebuffer,pongFramebufferTexture,pingFramebufferTexture;
function initPingPongFBOs(){pongFramebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,pongFramebuffer);pongFramebufferTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,
0,gl.RGBA,window.innerWidth/2,window.innerHeight/2,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,pongFramebufferTexture,0);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);pingFramebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,pingFramebuffer);pingFramebufferTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,pingFramebufferTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);
gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,window.innerWidth/2,window.innerHeight/2,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,pingFramebufferTexture,0);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null)}
var displayQuadProgram,displayQuadBuffer;
function displayQuadProgramInit(){displayQuadProgram=getShader("displayquadvertex","displayquadfragment",!1);displayQuadProgram.a1=gl.getAttribLocation(displayQuadProgram,"pos");displayQuadProgram.texture=gl.getUniformLocation(displayQuadProgram,"texture");displayQuadProgram.unblurred=gl.getUniformLocation(displayQuadProgram,"unblurred");displayQuadBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,displayQuadBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,-1,1,0,1,-1,0,1,-1,0,
-1,1,0,1,1,0]),gl.STATIC_DRAW)}var godRayProgram,godRaySkyboxBuffer;
function godRayProgramInit(){godRayProgram=getShader("godrayvertex","godrayfragment",!1);godRayProgram.a1=gl.getAttribLocation(godRayProgram,"pos");godRayProgram.a2=gl.getAttribLocation(godRayProgram,"normal");godRayProgram.a3=gl.getAttribLocation(godRayProgram,"uv");godRayProgram.projection=gl.getUniformLocation(godRayProgram,"projection");godRayProgram.model=gl.getUniformLocation(godRayProgram,"model");godRayProgram.view=gl.getUniformLocation(godRayProgram,"view");godRayProgram.scale=gl.getUniformLocation(godRayProgram,
"scale");godRayProgram.texture=gl.getUniformLocation(godRayProgram,"texture");godRayProgram.pass=gl.getUniformLocation(godRayProgram,"pass");godRayProgram.cameraForward=gl.getUniformLocation(godRayProgram,"cameraForward");godRaySkyboxBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,godRaySkyboxBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-3,3,-3,0,0,0,0,0,-3,-3,-3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,3,3,-3,0,0,0,0,0,-3,3,-3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,-3,-3,-3,0,0,0,0,0,
-3,3,-3,0,0,0,0,0,-3,3,-3,0,0,0,0,0,-3,3,3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,3,-3,3,0,0,0,0,0,3,3,3,0,0,0,0,0,3,3,3,0,0,0,0,0,3,3,-3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,-3,3,3,0,0,0,0,0,3,3,3,0,0,0,0,0,3,3,3,0,0,0,0,0,3,-3,3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,-3,3,-3,0,0,0,0,0,3,3,-3,0,0,0,0,0,3,3,3,0,0,0,0,0,3,3,3,0,0,0,0,0,-3,3,3,0,0,0,0,0,-3,3,-3,0,0,0,0,0,-3,-3,-3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,3,-3,-3,0,0,0,0,0,-3,-3,3,0,0,0,0,0,3,-3,3,0,0,0,0,0]),gl.STATIC_DRAW)}
var radialBlurProgram;function radialBlurProgramInit(){radialBlurProgram=getShader("radialblurvertex","radialblurfragment",!1);radialBlurProgram.a1=gl.getAttribLocation(radialBlurProgram,"pos");radialBlurProgram.texture=gl.getUniformLocation(radialBlurProgram,"texture");radialBlurProgram.projection=gl.getUniformLocation(radialBlurProgram,"projection");radialBlurProgram.model=gl.getUniformLocation(radialBlurProgram,"model");radialBlurProgram.view=gl.getUniformLocation(radialBlurProgram,"view")}
function drawGodRays(){gl.bindFramebuffer(gl.FRAMEBUFFER,LightFBO);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);mat4.identity(model);mat4.identity(view);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,1,10);gl.disable(gl.DEPTH_TEST);gl.viewport(0,0,window.innerWidth/2,window.innerHeight/2);gl.useProgram(godRayProgram);gl.bindBuffer(gl.ARRAY_BUFFER,godRaySkyboxBuffer);gl.enableVertexAttribArray(godRayProgram.a1);gl.enableVertexAttribArray(godRayProgram.a2);
gl.enableVertexAttribArray(godRayProgram.a3);var e=Float32Array.BYTES_PER_ELEMENT;gl.vertexAttribPointer(godRayProgram.a1,3,gl.FLOAT,!1,8*e,0*e);gl.vertexAttribPointer(godRayProgram.a2,3,gl.FLOAT,!1,8*e,3*e);gl.vertexAttribPointer(godRayProgram.a3,2,gl.FLOAT,!1,8*e,6*e);gl.uniformMatrix4fv(godRayProgram.projection,!1,projection);gl.uniformMatrix4fv(godRayProgram.model,!1,model);gl.uniformMatrix4fv(godRayProgram.view,!1,lookAt);gl.uniform1f(godRayProgram.pass,0);gl.uniform3fv(godRayProgram.cameraForward,
camera_axys.forward);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_CUBE_MAP,cubemap_texture);gl.uniform1i(godRayProgram.skybox,0);gl.drawArrays(gl.TRIANGLES,0,36);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,.1,100);gl.bindBuffer(gl.ARRAY_BUFFER,Buffer);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,indexBuffer);gl.enableVertexAttribArray(godRayProgram.a1);gl.enableVertexAttribArray(godRayProgram.a2);gl.enableVertexAttribArray(godRayProgram.a3);gl.vertexAttribPointer(godRayProgram.a1,
3,gl.FLOAT,!1,8*e,0*e);gl.vertexAttribPointer(godRayProgram.a2,3,gl.FLOAT,!1,8*e,3*e);gl.vertexAttribPointer(godRayProgram.a3,2,gl.FLOAT,!1,8*e,6*e);var f=new glMatrix.ARRAY_TYPE(16);f[0]=object_axys.right[0];f[1]=object_axys.up[0];f[2]=object_axys.forward[0];f[3]=0;f[4]=object_axys.right[1];f[5]=object_axys.up[1];f[6]=object_axys.forward[1];f[7]=0;f[8]=object_axys.right[2];f[9]=object_axys.up[2];f[10]=object_axys.forward[2];f[11]=0;f[12]=0;f[13]=0;f[14]=0;f[15]=1;mat4.transpose(f,f);mat4.scale(model,
model,[scale,scale,scale]);gl.uniformMatrix4fv(godRayProgram.projection,!1,projection);gl.uniformMatrix4fv(godRayProgram.model,!1,f);gl.uniformMatrix4fv(godRayProgram.scale,!1,model);gl.uniformMatrix4fv(godRayProgram.view,!1,lookAt);gl.uniform1f(godRayProgram.pass,2);gl.drawElements(gl.TRIANGLES,indexBufferLength,gl.UNSIGNED_SHORT,0);for(f=0;6>f;f++)0==f%2?gl.bindFramebuffer(gl.FRAMEBUFFER,pongFramebuffer):gl.bindFramebuffer(gl.FRAMEBUFFER,pingFramebuffer),gl.useProgram(radialBlurProgram),gl.bindBuffer(gl.ARRAY_BUFFER,
displayQuadBuffer),gl.enableVertexAttribArray(radialBlurProgram.a1),gl.vertexAttribPointer(radialBlurProgram.a1,3,gl.FLOAT,!1,0*e,0*e),gl.activeTexture(gl.TEXTURE0),0==f?gl.bindTexture(gl.TEXTURE_2D,LightFBOtexture):0==f%2?gl.bindTexture(gl.TEXTURE_2D,pingFramebufferTexture):gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture),gl.uniform1i(radialBlurProgram.texture,0),gl.uniformMatrix4fv(radialBlurProgram.projection,!1,projection),gl.uniformMatrix4fv(radialBlurProgram.view,!1,lookAt),gl.drawArrays(gl.TRIANGLES,
0,6)}
function displayLightFBOinQuad(){gl.viewport(0,0,window.innerWidth,window.innerHeight);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(displayQuadProgram);gl.bindBuffer(gl.ARRAY_BUFFER,displayQuadBuffer);gl.enableVertexAttribArray(displayQuadProgram.a1);gl.vertexAttribPointer(displayQuadProgram.a1,3,gl.FLOAT,!1,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture);gl.uniform1i(displayQuadProgram.texture,0);
gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,MainFBOtexture);gl.uniform1i(displayQuadProgram.unblurred,1);gl.drawArrays(gl.TRIANGLES,0,6)}var biquadFilter,gainNode,audioContext;
function initAudio(){window.loadCounter=3;audioContext=new (window.AudioContext||window.webkitAudioContext);var e=new XMLHttpRequest;e.open("GET","flying.mp3",!0);e.responseType="arraybuffer";e.onload=function(){audioContext.decodeAudioData(e.response,function(e){var f=audioContext.createBufferSource();audioContext.createGain||(audioContext.createGain=audioContext.createGainNode);gainNode=audioContext.createGain();biquadFilter=audioContext.createBiquadFilter();biquadFilter.type="lowpass";biquadFilter.frequency.value=
9440;f.loop=!0;f.buffer=e;gainNode.gain.value=.7;f.connect(gainNode);gainNode.connect(biquadFilter);biquadFilter.connect(audioContext.destination);f.start(audioContext.currentTime,0)})};e.send()}function getShader(e,f,h){h?(e=retrieveShader(e,"vertex"),f=retrieveShader(f,"fragment")):(e=shader(e),f=shader(f));h=gl.createProgram();gl.attachShader(h,e);gl.attachShader(h,f);gl.linkProgram(h);return gl.getProgramParameter(h,gl.LINK_STATUS)?h:(alert("Could not initialise shaders"),null)}
function retrieveShader(e,f){}function shader(e){var f=document.getElementById(e);if(!f)return null;for(var h="",m=f.firstChild;m;)3==m.nodeType&&(h+=m.textContent),m=m.nextSibling;if("frag"==f.type)f=gl.createShader(gl.FRAGMENT_SHADER);else if("vert"==f.type)f=gl.createShader(gl.VERTEX_SHADER);else return null;gl.shaderSource(f,h);gl.compileShader(f);return gl.getShaderParameter(f,gl.COMPILE_STATUS)?f:(alert(gl.getShaderInfoLog(f)+"  "+e),null)};