!function(g,d){if("object"==typeof exports&&"object"==typeof module)module.exports=d();else if("function"==typeof define&&define.amd)define(d);else{var f=d(),m;for(m in f)("object"==typeof exports?exports:g)[m]=f[m]}}(this,function(){return function(g){function d(m){if(f[m])return f[m].exports;var b=f[m]={exports:{},id:m,loaded:!1};return g[m].call(b.exports,b,b.exports,d),b.loaded=!0,b.exports}var f={};return d.m=g,d.c=f,d.p="",d(0)}([function(g,d,f){d.glMatrix=f(1);d.mat2=f(2);d.mat2d=f(3);d.mat3=
f(4);d.mat4=f(5);d.quat=f(6);d.vec2=f(9);d.vec3=f(7);d.vec4=f(8)},function(g,d){var f={EPSILON:1E-6};f.ARRAY_TYPE="undefined"!=typeof Float32Array?Float32Array:Array;f.RANDOM=Math.random;f.ENABLE_SIMD=!1;f.SIMD_AVAILABLE=f.ARRAY_TYPE===Float32Array&&"SIMD"in this;f.USE_SIMD=f.ENABLE_SIMD&&f.SIMD_AVAILABLE;f.setMatrixArrayType=function(b){f.ARRAY_TYPE=b};var m=Math.PI/180;f.toRadian=function(b){return b*m};g.exports=f},function(g,d,f){var m=f(1);d={create:function(){var b=new m.ARRAY_TYPE(4);return b[0]=
1,b[1]=0,b[2]=0,b[3]=1,b},clone:function(b){var a=new m.ARRAY_TYPE(4);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b},transpose:function(b,a){if(b===a){var c=a[1];b[1]=a[2];b[2]=c}else b[0]=a[0],b[1]=a[2],b[2]=a[1],b[3]=a[3];return b},invert:function(b,a){var c=a[0],e=a[1],p=a[2],k=a[3],l=c*k-p*e;return l?(l=1/l,b[0]=k*l,b[1]=-e*l,b[2]=-p*l,b[3]=c*l,b):null},adjoint:function(b,
a){var c=a[0];return b[0]=a[3],b[1]=-a[1],b[2]=-a[2],b[3]=c,b},determinant:function(b){return b[0]*b[3]-b[2]*b[1]},multiply:function(b,a,c){var e=a[0],p=a[1],k=a[2];a=a[3];var l=c[0],h=c[1],t=c[2];c=c[3];return b[0]=e*l+k*h,b[1]=p*l+a*h,b[2]=e*t+k*c,b[3]=p*t+a*c,b}};d.mul=d.multiply;d.rotate=function(b,a,c){var e=a[0],p=a[1],k=a[2];a=a[3];var l=Math.sin(c);c=Math.cos(c);return b[0]=e*c+k*l,b[1]=p*c+a*l,b[2]=e*-l+k*c,b[3]=p*-l+a*c,b};d.scale=function(b,a,c){var e=a[1],p=a[2],k=a[3],l=c[0];c=c[1];return b[0]=
a[0]*l,b[1]=e*l,b[2]=p*c,b[3]=k*c,b};d.fromRotation=function(b,a){var c=Math.sin(a),e=Math.cos(a);return b[0]=e,b[1]=c,b[2]=-c,b[3]=e,b};d.fromScaling=function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=a[1],b};d.str=function(b){return"mat2("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+")"};d.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2))};d.LDU=function(b,a,c,e){return b[2]=e[2]/e[0],c[0]=e[0],c[1]=e[1],c[3]=e[3]-b[2]*c[1],[b,a,c]};g.exports=d},function(g,
d,f){var m=f(1);d={create:function(){var b=new m.ARRAY_TYPE(6);return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=0,b[5]=0,b},clone:function(b){var a=new m.ARRAY_TYPE(6);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[4]=b[4],a[5]=b[5],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=0,b[5]=0,b},invert:function(b,a){var c=a[0],e=a[1],p=a[2],k=a[3],l=a[4],h=a[5],t=c*k-e*p;return t?(t=1/t,b[0]=k*t,b[1]=-e*
t,b[2]=-p*t,b[3]=c*t,b[4]=(p*h-k*l)*t,b[5]=(e*l-c*h)*t,b):null},determinant:function(b){return b[0]*b[3]-b[1]*b[2]},multiply:function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4];a=a[5];var t=c[0],d=c[1],x=c[2],n=c[3],f=c[4];c=c[5];return b[0]=e*t+k*d,b[1]=p*t+l*d,b[2]=e*x+k*n,b[3]=p*x+l*n,b[4]=e*f+k*c+h,b[5]=p*f+l*c+a,b}};d.mul=d.multiply;d.rotate=function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4];a=a[5];var t=Math.sin(c);c=Math.cos(c);return b[0]=e*c+k*t,b[1]=p*c+l*t,b[2]=e*-t+k*c,b[3]=p*-t+
l*c,b[4]=h,b[5]=a,b};d.scale=function(b,a,c){var e=a[1],p=a[2],k=a[3],l=a[4],h=a[5],t=c[0];c=c[1];return b[0]=a[0]*t,b[1]=e*t,b[2]=p*c,b[3]=k*c,b[4]=l,b[5]=h,b};d.translate=function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4];a=a[5];var t=c[0];c=c[1];return b[0]=e,b[1]=p,b[2]=k,b[3]=l,b[4]=e*t+k*c+h,b[5]=p*t+l*c+a,b};d.fromRotation=function(b,a){var c=Math.sin(a),e=Math.cos(a);return b[0]=e,b[1]=c,b[2]=-c,b[3]=e,b[4]=0,b[5]=0,b};d.fromScaling=function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=a[1],
b[4]=0,b[5]=0,b};d.fromTranslation=function(b,a){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=a[0],b[5]=a[1],b};d.str=function(b){return"mat2d("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+", "+b[4]+", "+b[5]+")"};d.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+1)};g.exports=d},function(g,d,f){var m=f(1);d={create:function(){var b=new m.ARRAY_TYPE(9);return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b},
fromMat4:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[4],b[4]=a[5],b[5]=a[6],b[6]=a[8],b[7]=a[9],b[8]=a[10],b},clone:function(b){var a=new m.ARRAY_TYPE(9);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[4]=b[4],a[5]=b[5],a[6]=b[6],a[7]=b[7],a[8]=b[8],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b},transpose:function(b,
a){if(b===a){var c=a[1],e=a[2],p=a[5];b[1]=a[3];b[2]=a[6];b[3]=c;b[5]=a[7];b[6]=e;b[7]=p}else b[0]=a[0],b[1]=a[3],b[2]=a[6],b[3]=a[1],b[4]=a[4],b[5]=a[7],b[6]=a[2],b[7]=a[5],b[8]=a[8];return b},invert:function(b,a){var c=a[0],e=a[1],p=a[2],k=a[3],l=a[4],h=a[5],t=a[6],d=a[7],x=a[8],n=x*l-h*d,f=-x*k+h*t,g=d*k-l*t,q=c*n+e*f+p*g;return q?(q=1/q,b[0]=n*q,b[1]=(-x*e+p*d)*q,b[2]=(h*e-p*l)*q,b[3]=f*q,b[4]=(x*c-p*t)*q,b[5]=(-h*c+p*k)*q,b[6]=g*q,b[7]=(-d*c+e*t)*q,b[8]=(l*c-e*k)*q,b):null},adjoint:function(b,
a){var c=a[0],e=a[1],p=a[2],k=a[3],l=a[4],h=a[5],t=a[6],d=a[7],x=a[8];return b[0]=l*x-h*d,b[1]=p*d-e*x,b[2]=e*h-p*l,b[3]=h*t-k*x,b[4]=c*x-p*t,b[5]=p*k-c*h,b[6]=k*d-l*t,b[7]=e*t-c*d,b[8]=c*l-e*k,b},determinant:function(b){var a=b[3],c=b[4],e=b[5],p=b[6],k=b[7],l=b[8];return b[0]*(l*c-e*k)+b[1]*(-l*a+e*p)+b[2]*(k*a-c*p)},multiply:function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4],t=a[5],d=a[6],x=a[7];a=a[8];var n=c[0],f=c[1],g=c[2],q=c[3],m=c[4],r=c[5],v=c[6],y=c[7];c=c[8];return b[0]=n*e+f*l+g*
d,b[1]=n*p+f*h+g*x,b[2]=n*k+f*t+g*a,b[3]=q*e+m*l+r*d,b[4]=q*p+m*h+r*x,b[5]=q*k+m*t+r*a,b[6]=v*e+y*l+c*d,b[7]=v*p+y*h+c*x,b[8]=v*k+y*t+c*a,b}};d.mul=d.multiply;d.translate=function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4],t=a[5],d=a[6],x=a[7];a=a[8];var n=c[0];c=c[1];return b[0]=e,b[1]=p,b[2]=k,b[3]=l,b[4]=h,b[5]=t,b[6]=n*e+c*l+d,b[7]=n*p+c*h+x,b[8]=n*k+c*t+a,b};d.rotate=function(b,a,c){var e=a[0],p=a[1],k=a[2],l=a[3],h=a[4],t=a[5],d=a[6],x=a[7];a=a[8];var n=Math.sin(c);c=Math.cos(c);return b[0]=
c*e+n*l,b[1]=c*p+n*h,b[2]=c*k+n*t,b[3]=c*l-n*e,b[4]=c*h-n*p,b[5]=c*t-n*k,b[6]=d,b[7]=x,b[8]=a,b};d.scale=function(b,a,c){var e=c[0];c=c[1];return b[0]=e*a[0],b[1]=e*a[1],b[2]=e*a[2],b[3]=c*a[3],b[4]=c*a[4],b[5]=c*a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b};d.fromTranslation=function(b,a){return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=a[0],b[7]=a[1],b[8]=1,b};d.fromRotation=function(b,a){var c=Math.sin(a),e=Math.cos(a);return b[0]=e,b[1]=c,b[2]=0,b[3]=-c,b[4]=e,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b};d.fromScaling=
function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=0,b[4]=a[1],b[5]=0,b[6]=0,b[7]=0,b[8]=1,b};d.fromMat2d=function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=0,b[3]=a[2],b[4]=a[3],b[5]=0,b[6]=a[4],b[7]=a[5],b[8]=1,b};d.fromQuat=function(b,a){var c=a[0],e=a[1],p=a[2],k=a[3],l=c+c,h=e+e,t=p+p,c=c*l,d=e*l,e=e*h,x=p*l,n=p*h,p=p*t,l=k*l,h=k*h,k=k*t;return b[0]=1-e-p,b[3]=d-k,b[6]=x+h,b[1]=d+k,b[4]=1-c-p,b[7]=n-l,b[2]=x-h,b[5]=n+l,b[8]=1-c-e,b};d.normalFromMat4=function(b,a){var c=a[0],e=a[1],p=a[2],k=a[3],l=
a[4],h=a[5],t=a[6],d=a[7],x=a[8],n=a[9],f=a[10],g=a[11],q=a[12],m=a[13],r=a[14],v=a[15],y=c*h-e*l,A=c*t-p*l,z=c*d-k*l,C=e*t-p*h,B=e*d-k*h,H=p*d-k*t,I=x*m-n*q,J=x*r-f*q,x=x*v-g*q,K=n*r-f*m,n=n*v-g*m,f=f*v-g*r;return(g=y*f-A*n+z*K+C*x-B*J+H*I)?(g=1/g,b[0]=(h*f-t*n+d*K)*g,b[1]=(t*x-l*f-d*J)*g,b[2]=(l*n-h*x+d*I)*g,b[3]=(p*n-e*f-k*K)*g,b[4]=(c*f-p*x+k*J)*g,b[5]=(e*x-c*n-k*I)*g,b[6]=(m*H-r*B+v*C)*g,b[7]=(r*z-q*H-v*A)*g,b[8]=(q*B-m*z+v*y)*g,b):null};d.str=function(b){return"mat3("+b[0]+", "+b[1]+", "+b[2]+
", "+b[3]+", "+b[4]+", "+b[5]+", "+b[6]+", "+b[7]+", "+b[8]+")"};d.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+Math.pow(b[6],2)+Math.pow(b[7],2)+Math.pow(b[8],2))};g.exports=d},function(g,d,f){var m=f(1),b={scalar:{},SIMD:{},create:function(){var a=new m.ARRAY_TYPE(16);return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a},clone:function(a){var c=
new m.ARRAY_TYPE(16);return c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15],c},copy:function(a,c){return a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a},identity:function(a){return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=0,a[9]=0,
a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a}};b.scalar.transpose=function(a,c){if(a===c){var e=c[1],b=c[2],k=c[3],l=c[6],h=c[7],t=c[11];a[1]=c[4];a[2]=c[8];a[3]=c[12];a[4]=e;a[6]=c[9];a[7]=c[13];a[8]=b;a[9]=l;a[11]=c[14];a[12]=k;a[13]=h;a[14]=t}else a[0]=c[0],a[1]=c[4],a[2]=c[8],a[3]=c[12],a[4]=c[1],a[5]=c[5],a[6]=c[9],a[7]=c[13],a[8]=c[2],a[9]=c[6],a[10]=c[10],a[11]=c[14],a[12]=c[3],a[13]=c[7],a[14]=c[11],a[15]=c[15];return a};b.SIMD.transpose=function(a,c){var e,b,k,l,h,t,d,f,n,g;return e=
SIMD.Float32x4.load(c,0),b=SIMD.Float32x4.load(c,4),k=SIMD.Float32x4.load(c,8),l=SIMD.Float32x4.load(c,12),h=SIMD.Float32x4.shuffle(e,b,0,1,4,5),t=SIMD.Float32x4.shuffle(k,l,0,1,4,5),d=SIMD.Float32x4.shuffle(h,t,0,2,4,6),f=SIMD.Float32x4.shuffle(h,t,1,3,5,7),SIMD.Float32x4.store(a,0,d),SIMD.Float32x4.store(a,4,f),h=SIMD.Float32x4.shuffle(e,b,2,3,6,7),t=SIMD.Float32x4.shuffle(k,l,2,3,6,7),n=SIMD.Float32x4.shuffle(h,t,0,2,4,6),g=SIMD.Float32x4.shuffle(h,t,1,3,5,7),SIMD.Float32x4.store(a,8,n),SIMD.Float32x4.store(a,
12,g),a};b.transpose=m.USE_SIMD?b.SIMD.transpose:b.scalar.transpose;b.scalar.invert=function(a,c){var e=c[0],b=c[1],k=c[2],l=c[3],h=c[4],t=c[5],d=c[6],f=c[7],n=c[8],g=c[9],m=c[10],q=c[11],w=c[12],r=c[13],v=c[14],y=c[15],A=e*t-b*h,z=e*d-k*h,C=e*f-l*h,B=b*d-k*t,H=b*f-l*t,I=k*f-l*d,J=n*r-g*w,K=n*v-m*w,L=n*y-q*w,M=g*v-m*r,F=g*y-q*r,G=m*y-q*v,D=A*G-z*F+C*M+B*L-H*K+I*J;return D?(D=1/D,a[0]=(t*G-d*F+f*M)*D,a[1]=(k*F-b*G-l*M)*D,a[2]=(r*I-v*H+y*B)*D,a[3]=(m*H-g*I-q*B)*D,a[4]=(d*L-h*G-f*K)*D,a[5]=(e*G-k*L+
l*K)*D,a[6]=(v*C-w*I-y*z)*D,a[7]=(n*I-m*C+q*z)*D,a[8]=(h*F-t*L+f*J)*D,a[9]=(b*L-e*F-l*J)*D,a[10]=(w*H-r*C+y*A)*D,a[11]=(g*C-n*H-q*A)*D,a[12]=(t*K-h*M-d*J)*D,a[13]=(e*M-b*K+k*J)*D,a[14]=(r*z-w*B-v*A)*D,a[15]=(n*B-g*z+m*A)*D,a):null};b.SIMD.invert=function(a,c){var e,b,k,l,h,d,f,x,n,g,m=SIMD.Float32x4.load(c,0),q=SIMD.Float32x4.load(c,4),w=SIMD.Float32x4.load(c,8),r=SIMD.Float32x4.load(c,12);return h=SIMD.Float32x4.shuffle(m,q,0,1,4,5),b=SIMD.Float32x4.shuffle(w,r,0,1,4,5),e=SIMD.Float32x4.shuffle(h,
b,0,2,4,6),b=SIMD.Float32x4.shuffle(b,h,1,3,5,7),h=SIMD.Float32x4.shuffle(m,q,2,3,6,7),l=SIMD.Float32x4.shuffle(w,r,2,3,6,7),k=SIMD.Float32x4.shuffle(h,l,0,2,4,6),l=SIMD.Float32x4.shuffle(l,h,1,3,5,7),h=SIMD.Float32x4.mul(k,l),h=SIMD.Float32x4.swizzle(h,1,0,3,2),d=SIMD.Float32x4.mul(b,h),f=SIMD.Float32x4.mul(e,h),h=SIMD.Float32x4.swizzle(h,2,3,0,1),d=SIMD.Float32x4.sub(SIMD.Float32x4.mul(b,h),d),f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(e,h),f),f=SIMD.Float32x4.swizzle(f,2,3,0,1),h=SIMD.Float32x4.mul(b,
k),h=SIMD.Float32x4.swizzle(h,1,0,3,2),d=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,h),d),n=SIMD.Float32x4.mul(e,h),h=SIMD.Float32x4.swizzle(h,2,3,0,1),d=SIMD.Float32x4.sub(d,SIMD.Float32x4.mul(l,h)),n=SIMD.Float32x4.sub(SIMD.Float32x4.mul(e,h),n),n=SIMD.Float32x4.swizzle(n,2,3,0,1),h=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(b,2,3,0,1),l),h=SIMD.Float32x4.swizzle(h,1,0,3,2),k=SIMD.Float32x4.swizzle(k,2,3,0,1),d=SIMD.Float32x4.add(SIMD.Float32x4.mul(k,h),d),x=SIMD.Float32x4.mul(e,h),h=SIMD.Float32x4.swizzle(h,
2,3,0,1),d=SIMD.Float32x4.sub(d,SIMD.Float32x4.mul(k,h)),x=SIMD.Float32x4.sub(SIMD.Float32x4.mul(e,h),x),x=SIMD.Float32x4.swizzle(x,2,3,0,1),h=SIMD.Float32x4.mul(e,b),h=SIMD.Float32x4.swizzle(h,1,0,3,2),x=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,h),x),n=SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,h),n),h=SIMD.Float32x4.swizzle(h,2,3,0,1),x=SIMD.Float32x4.sub(SIMD.Float32x4.mul(l,h),x),n=SIMD.Float32x4.sub(n,SIMD.Float32x4.mul(k,h)),h=SIMD.Float32x4.mul(e,l),h=SIMD.Float32x4.swizzle(h,1,0,3,2),f=SIMD.Float32x4.sub(f,
SIMD.Float32x4.mul(k,h)),x=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,h),x),h=SIMD.Float32x4.swizzle(h,2,3,0,1),f=SIMD.Float32x4.add(SIMD.Float32x4.mul(k,h),f),x=SIMD.Float32x4.sub(x,SIMD.Float32x4.mul(b,h)),h=SIMD.Float32x4.mul(e,k),h=SIMD.Float32x4.swizzle(h,1,0,3,2),f=SIMD.Float32x4.add(SIMD.Float32x4.mul(l,h),f),n=SIMD.Float32x4.sub(n,SIMD.Float32x4.mul(b,h)),h=SIMD.Float32x4.swizzle(h,2,3,0,1),f=SIMD.Float32x4.sub(f,SIMD.Float32x4.mul(l,h)),n=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,h),n),g=SIMD.Float32x4.mul(e,
d),g=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(g,2,3,0,1),g),g=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(g,1,0,3,2),g),h=SIMD.Float32x4.reciprocalApproximation(g),g=SIMD.Float32x4.sub(SIMD.Float32x4.add(h,h),SIMD.Float32x4.mul(g,SIMD.Float32x4.mul(h,h))),(g=SIMD.Float32x4.swizzle(g,0,0,0,0))?(SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(g,d)),SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(g,f)),SIMD.Float32x4.store(a,8,SIMD.Float32x4.mul(g,x)),SIMD.Float32x4.store(a,12,SIMD.Float32x4.mul(g,n)),a):null};
b.invert=m.USE_SIMD?b.SIMD.invert:b.scalar.invert;b.scalar.adjoint=function(a,c){var e=c[0],b=c[1],k=c[2],l=c[3],h=c[4],d=c[5],f=c[6],g=c[7],n=c[8],m=c[9],u=c[10],q=c[11],w=c[12],r=c[13],v=c[14],y=c[15];return a[0]=d*(u*y-q*v)-m*(f*y-g*v)+r*(f*q-g*u),a[1]=-(b*(u*y-q*v)-m*(k*y-l*v)+r*(k*q-l*u)),a[2]=b*(f*y-g*v)-d*(k*y-l*v)+r*(k*g-l*f),a[3]=-(b*(f*q-g*u)-d*(k*q-l*u)+m*(k*g-l*f)),a[4]=-(h*(u*y-q*v)-n*(f*y-g*v)+w*(f*q-g*u)),a[5]=e*(u*y-q*v)-n*(k*y-l*v)+w*(k*q-l*u),a[6]=-(e*(f*y-g*v)-h*(k*y-l*v)+w*(k*
g-l*f)),a[7]=e*(f*q-g*u)-h*(k*q-l*u)+n*(k*g-l*f),a[8]=h*(m*y-q*r)-n*(d*y-g*r)+w*(d*q-g*m),a[9]=-(e*(m*y-q*r)-n*(b*y-l*r)+w*(b*q-l*m)),a[10]=e*(d*y-g*r)-h*(b*y-l*r)+w*(b*g-l*d),a[11]=-(e*(d*q-g*m)-h*(b*q-l*m)+n*(b*g-l*d)),a[12]=-(h*(m*v-u*r)-n*(d*v-f*r)+w*(d*u-f*m)),a[13]=e*(m*v-u*r)-n*(b*v-k*r)+w*(b*u-k*m),a[14]=-(e*(d*v-f*r)-h*(b*v-k*r)+w*(b*f-k*d)),a[15]=e*(d*u-f*m)-h*(b*u-k*m)+n*(b*f-k*d),a};b.SIMD.adjoint=function(a,c){var e,b,k,l,h,d,f,g,n,m,u,q,w;e=SIMD.Float32x4.load(c,0);b=SIMD.Float32x4.load(c,
4);k=SIMD.Float32x4.load(c,8);l=SIMD.Float32x4.load(c,12);return n=SIMD.Float32x4.shuffle(e,b,0,1,4,5),d=SIMD.Float32x4.shuffle(k,l,0,1,4,5),h=SIMD.Float32x4.shuffle(n,d,0,2,4,6),d=SIMD.Float32x4.shuffle(d,n,1,3,5,7),n=SIMD.Float32x4.shuffle(e,b,2,3,6,7),g=SIMD.Float32x4.shuffle(k,l,2,3,6,7),f=SIMD.Float32x4.shuffle(n,g,0,2,4,6),g=SIMD.Float32x4.shuffle(g,n,1,3,5,7),n=SIMD.Float32x4.mul(f,g),n=SIMD.Float32x4.swizzle(n,1,0,3,2),m=SIMD.Float32x4.mul(d,n),u=SIMD.Float32x4.mul(h,n),n=SIMD.Float32x4.swizzle(n,
2,3,0,1),m=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,n),m),u=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,n),u),u=SIMD.Float32x4.swizzle(u,2,3,0,1),n=SIMD.Float32x4.mul(d,f),n=SIMD.Float32x4.swizzle(n,1,0,3,2),m=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,n),m),w=SIMD.Float32x4.mul(h,n),n=SIMD.Float32x4.swizzle(n,2,3,0,1),m=SIMD.Float32x4.sub(m,SIMD.Float32x4.mul(g,n)),w=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,n),w),w=SIMD.Float32x4.swizzle(w,2,3,0,1),n=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,2,3,0,1),g),
n=SIMD.Float32x4.swizzle(n,1,0,3,2),f=SIMD.Float32x4.swizzle(f,2,3,0,1),m=SIMD.Float32x4.add(SIMD.Float32x4.mul(f,n),m),q=SIMD.Float32x4.mul(h,n),n=SIMD.Float32x4.swizzle(n,2,3,0,1),m=SIMD.Float32x4.sub(m,SIMD.Float32x4.mul(f,n)),q=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,n),q),q=SIMD.Float32x4.swizzle(q,2,3,0,1),n=SIMD.Float32x4.mul(h,d),n=SIMD.Float32x4.swizzle(n,1,0,3,2),q=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,n),q),w=SIMD.Float32x4.sub(SIMD.Float32x4.mul(f,n),w),n=SIMD.Float32x4.swizzle(n,2,
3,0,1),q=SIMD.Float32x4.sub(SIMD.Float32x4.mul(g,n),q),w=SIMD.Float32x4.sub(w,SIMD.Float32x4.mul(f,n)),n=SIMD.Float32x4.mul(h,g),n=SIMD.Float32x4.swizzle(n,1,0,3,2),u=SIMD.Float32x4.sub(u,SIMD.Float32x4.mul(f,n)),q=SIMD.Float32x4.add(SIMD.Float32x4.mul(d,n),q),n=SIMD.Float32x4.swizzle(n,2,3,0,1),u=SIMD.Float32x4.add(SIMD.Float32x4.mul(f,n),u),q=SIMD.Float32x4.sub(q,SIMD.Float32x4.mul(d,n)),n=SIMD.Float32x4.mul(h,f),n=SIMD.Float32x4.swizzle(n,1,0,3,2),u=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,n),u),
w=SIMD.Float32x4.sub(w,SIMD.Float32x4.mul(d,n)),n=SIMD.Float32x4.swizzle(n,2,3,0,1),u=SIMD.Float32x4.sub(u,SIMD.Float32x4.mul(g,n)),w=SIMD.Float32x4.add(SIMD.Float32x4.mul(d,n),w),SIMD.Float32x4.store(a,0,m),SIMD.Float32x4.store(a,4,u),SIMD.Float32x4.store(a,8,q),SIMD.Float32x4.store(a,12,w),a};b.adjoint=m.USE_SIMD?b.SIMD.adjoint:b.scalar.adjoint;b.determinant=function(a){var c=a[0],e=a[1],b=a[2],k=a[3],l=a[4],h=a[5],d=a[6],f=a[7],g=a[8],n=a[9],m=a[10],u=a[11],q=a[12],w=a[13],r=a[14];a=a[15];return(c*
h-e*l)*(m*a-u*r)-(c*d-b*l)*(n*a-u*w)+(c*f-k*l)*(n*r-m*w)+(e*d-b*h)*(g*a-u*q)-(e*f-k*h)*(g*r-m*q)+(b*f-k*d)*(g*w-n*q)};b.SIMD.multiply=function(a,c,e){var b=SIMD.Float32x4.load(c,0),k=SIMD.Float32x4.load(c,4),l=SIMD.Float32x4.load(c,8);c=SIMD.Float32x4.load(c,12);var h=SIMD.Float32x4.load(e,0),h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,
2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,0,h);h=SIMD.Float32x4.load(e,4);h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,4,h);h=SIMD.Float32x4.load(e,8);h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,
0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,2,2,2,2),l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,8,h);e=SIMD.Float32x4.load(e,12);b=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,2,2,2,2),
l),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,3,3,3,3),c))));return SIMD.Float32x4.store(a,12,b),a};b.scalar.multiply=function(a,c,e){var b=c[0],k=c[1],l=c[2],h=c[3],d=c[4],f=c[5],g=c[6],n=c[7],m=c[8],u=c[9],q=c[10],w=c[11],r=c[12],v=c[13],y=c[14];c=c[15];var A=e[0],z=e[1],C=e[2],B=e[3];return a[0]=A*b+z*d+C*m+B*r,a[1]=A*k+z*f+C*u+B*v,a[2]=A*l+z*g+C*q+B*y,a[3]=A*h+z*n+C*w+B*c,A=e[4],z=e[5],C=e[6],B=e[7],a[4]=A*b+z*d+C*m+B*r,a[5]=A*k+z*f+C*u+B*v,a[6]=A*l+z*g+C*q+B*y,a[7]=A*h+z*n+C*w+B*c,A=e[8],z=
e[9],C=e[10],B=e[11],a[8]=A*b+z*d+C*m+B*r,a[9]=A*k+z*f+C*u+B*v,a[10]=A*l+z*g+C*q+B*y,a[11]=A*h+z*n+C*w+B*c,A=e[12],z=e[13],C=e[14],B=e[15],a[12]=A*b+z*d+C*m+B*r,a[13]=A*k+z*f+C*u+B*v,a[14]=A*l+z*g+C*q+B*y,a[15]=A*h+z*n+C*w+B*c,a};b.multiply=m.USE_SIMD?b.SIMD.multiply:b.scalar.multiply;b.mul=b.multiply;b.scalar.translate=function(a,c,e){var b,k,l,h,d,f,g,n,m,u,q,w,r=e[0],v=e[1];e=e[2];return c===a?(a[12]=c[0]*r+c[4]*v+c[8]*e+c[12],a[13]=c[1]*r+c[5]*v+c[9]*e+c[13],a[14]=c[2]*r+c[6]*v+c[10]*e+c[14],
a[15]=c[3]*r+c[7]*v+c[11]*e+c[15]):(b=c[0],k=c[1],l=c[2],h=c[3],d=c[4],f=c[5],g=c[6],n=c[7],m=c[8],u=c[9],q=c[10],w=c[11],a[0]=b,a[1]=k,a[2]=l,a[3]=h,a[4]=d,a[5]=f,a[6]=g,a[7]=n,a[8]=m,a[9]=u,a[10]=q,a[11]=w,a[12]=b*r+d*v+m*e+c[12],a[13]=k*r+f*v+u*e+c[13],a[14]=l*r+g*v+q*e+c[14],a[15]=h*r+n*v+w*e+c[15]),a};b.SIMD.translate=function(a,c,e){var b=SIMD.Float32x4.load(c,0),k=SIMD.Float32x4.load(c,4),l=SIMD.Float32x4.load(c,8),h=SIMD.Float32x4.load(c,12);e=SIMD.Float32x4(e[0],e[1],e[2],0);c!==a&&(a[0]=
c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11]);b=SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(e,0,0,0,0));k=SIMD.Float32x4.mul(k,SIMD.Float32x4.swizzle(e,1,1,1,1));l=SIMD.Float32x4.mul(l,SIMD.Float32x4.swizzle(e,2,2,2,2));c=SIMD.Float32x4.add(b,SIMD.Float32x4.add(k,SIMD.Float32x4.add(l,h)));return SIMD.Float32x4.store(a,12,c),a};b.translate=m.USE_SIMD?b.SIMD.translate:b.scalar.translate;b.scalar.scale=function(a,c,e){var b=e[0],
k=e[1];e=e[2];return a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b,a[3]=c[3]*b,a[4]=c[4]*k,a[5]=c[5]*k,a[6]=c[6]*k,a[7]=c[7]*k,a[8]=c[8]*e,a[9]=c[9]*e,a[10]=c[10]*e,a[11]=c[11]*e,a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a};b.SIMD.scale=function(a,c,e){var b,k,l;e=SIMD.Float32x4(e[0],e[1],e[2],0);return b=SIMD.Float32x4.load(c,0),SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(b,SIMD.Float32x4.swizzle(e,0,0,0,0))),k=SIMD.Float32x4.load(c,4),SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(k,SIMD.Float32x4.swizzle(e,
1,1,1,1))),l=SIMD.Float32x4.load(c,8),SIMD.Float32x4.store(a,8,SIMD.Float32x4.mul(l,SIMD.Float32x4.swizzle(e,2,2,2,2))),a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a};b.scale=m.USE_SIMD?b.SIMD.scale:b.scalar.scale;b.rotate=function(a,c,e,b){var p,l,h,d,f,g,n,E,u,q,w,r,v,y,A,z,C,B,H,I,J,K,L,M,F=b[0],G=b[1];b=b[2];var D=Math.sqrt(F*F+G*G+b*b);return Math.abs(D)<m.EPSILON?null:(D=1/D,F*=D,G*=D,b*=D,p=Math.sin(e),l=Math.cos(e),h=1-l,d=c[0],f=c[1],g=c[2],n=c[3],E=c[4],u=c[5],q=c[6],w=c[7],r=c[8],v=
c[9],y=c[10],A=c[11],z=F*F*h+l,C=G*F*h+b*p,B=b*F*h-G*p,H=F*G*h-b*p,I=G*G*h+l,J=b*G*h+F*p,K=F*b*h+G*p,L=G*b*h-F*p,M=b*b*h+l,a[0]=d*z+E*C+r*B,a[1]=f*z+u*C+v*B,a[2]=g*z+q*C+y*B,a[3]=n*z+w*C+A*B,a[4]=d*H+E*I+r*J,a[5]=f*H+u*I+v*J,a[6]=g*H+q*I+y*J,a[7]=n*H+w*I+A*J,a[8]=d*K+E*L+r*M,a[9]=f*K+u*L+v*M,a[10]=g*K+q*L+y*M,a[11]=n*K+w*L+A*M,c!==a&&(a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a)};b.scalar.rotateX=function(a,c,e){var b=Math.sin(e);e=Math.cos(e);var k=c[4],l=c[5],h=c[6],d=c[7],f=c[8],g=c[9],
n=c[10],m=c[11];return c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[4]=k*e+f*b,a[5]=l*e+g*b,a[6]=h*e+n*b,a[7]=d*e+m*b,a[8]=f*e-k*b,a[9]=g*e-l*b,a[10]=n*e-h*b,a[11]=m*e-d*b,a};b.SIMD.rotateX=function(a,c,e){var b=SIMD.Float32x4.splat(Math.sin(e));e=SIMD.Float32x4.splat(Math.cos(e));c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,4);c=SIMD.Float32x4.load(c,8);return SIMD.Float32x4.store(a,
4,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,e),SIMD.Float32x4.mul(c,b))),SIMD.Float32x4.store(a,8,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,e),SIMD.Float32x4.mul(k,b))),a};b.rotateX=m.USE_SIMD?b.SIMD.rotateX:b.scalar.rotateX;b.scalar.rotateY=function(a,c,e){var b=Math.sin(e);e=Math.cos(e);var k=c[0],l=c[1],h=c[2],d=c[3],f=c[8],g=c[9],n=c[10],m=c[11];return c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[0]=k*e-f*b,a[1]=l*e-g*b,a[2]=h*e-n*b,a[3]=d*e-m*
b,a[8]=k*b+f*e,a[9]=l*b+g*e,a[10]=h*b+n*e,a[11]=d*b+m*e,a};b.SIMD.rotateY=function(a,c,b){var e=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,8);return SIMD.Float32x4.store(a,0,SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,b),SIMD.Float32x4.mul(c,e))),SIMD.Float32x4.store(a,8,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,e),SIMD.Float32x4.mul(c,
b))),a};b.rotateY=m.USE_SIMD?b.SIMD.rotateY:b.scalar.rotateY;b.scalar.rotateZ=function(a,c,b){var e=Math.sin(b);b=Math.cos(b);var k=c[0],l=c[1],h=c[2],d=c[3],f=c[4],g=c[5],n=c[6],m=c[7];return c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[0]=k*b+f*e,a[1]=l*b+g*e,a[2]=h*b+n*e,a[3]=d*b+m*e,a[4]=f*b-k*e,a[5]=g*b-l*e,a[6]=n*b-h*e,a[7]=m*b-d*e,a};b.SIMD.rotateZ=function(a,c,b){var e=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));
c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,4);return SIMD.Float32x4.store(a,0,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,b),SIMD.Float32x4.mul(c,e))),SIMD.Float32x4.store(a,4,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,b),SIMD.Float32x4.mul(k,e))),a};b.rotateZ=m.USE_SIMD?b.SIMD.rotateZ:b.scalar.rotateZ;b.fromTranslation=function(a,c){return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=
0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=c[0],a[13]=c[1],a[14]=c[2],a[15]=1,a};b.fromScaling=function(a,c){return a[0]=c[0],a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=c[1],a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=c[2],a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromRotation=function(a,c,b){var e,k,l,h=b[0],d=b[1];b=b[2];var f=Math.sqrt(h*h+d*d+b*b);return Math.abs(f)<m.EPSILON?null:(f=1/f,h*=f,d*=f,b*=f,e=Math.sin(c),k=Math.cos(c),l=1-k,a[0]=h*h*l+k,a[1]=d*h*l+b*e,a[2]=b*h*l-d*e,a[3]=0,a[4]=h*d*l-b*e,a[5]=d*d*l+k,a[6]=
b*d*l+h*e,a[7]=0,a[8]=h*b*l+d*e,a[9]=d*b*l-h*e,a[10]=b*b*l+k,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a)};b.fromXRotation=function(a,c){var b=Math.sin(c),p=Math.cos(c);return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=p,a[6]=b,a[7]=0,a[8]=0,a[9]=-b,a[10]=p,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromYRotation=function(a,c){var b=Math.sin(c),p=Math.cos(c);return a[0]=p,a[1]=0,a[2]=-b,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=b,a[9]=0,a[10]=p,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromZRotation=
function(a,c){var b=Math.sin(c),p=Math.cos(c);return a[0]=p,a[1]=b,a[2]=0,a[3]=0,a[4]=-b,a[5]=p,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromRotationTranslation=function(a,c,b){var e=c[0],k=c[1],l=c[2],h=c[3],d=e+e,f=k+k,g=l+l;c=e*d;var n=e*f,e=e*g,m=k*f,k=k*g,l=l*g,d=h*d,f=h*f,h=h*g;return a[0]=1-(m+l),a[1]=n+h,a[2]=e-f,a[3]=0,a[4]=n-h,a[5]=1-(c+l),a[6]=k+d,a[7]=0,a[8]=e+f,a[9]=k-d,a[10]=1-(c+m),a[11]=0,a[12]=b[0],a[13]=b[1],a[14]=b[2],a[15]=1,a};b.fromRotationTranslationScale=
function(a,c,b,p){var e=c[0],l=c[1],h=c[2],d=c[3],f=e+e,g=l+l,n=h+h;c=e*f;var m=e*g,e=e*n,u=l*g,l=l*n,h=h*n,f=d*f,g=d*g,d=d*n,n=p[0],q=p[1];p=p[2];return a[0]=(1-(u+h))*n,a[1]=(m+d)*n,a[2]=(e-g)*n,a[3]=0,a[4]=(m-d)*q,a[5]=(1-(c+h))*q,a[6]=(l+f)*q,a[7]=0,a[8]=(e+g)*p,a[9]=(l-f)*p,a[10]=(1-(c+u))*p,a[11]=0,a[12]=b[0],a[13]=b[1],a[14]=b[2],a[15]=1,a};b.fromRotationTranslationScaleOrigin=function(a,c,b,p,k){var e=c[0],h=c[1],d=c[2],f=c[3],g=e+e,n=h+h,m=d+d;c=e*g;var u=e*n,e=e*m,q=h*n,h=h*m,d=d*m,g=f*
g,n=f*n,f=f*m,m=p[0],w=p[1];p=p[2];var r=k[0],v=k[1];k=k[2];return a[0]=(1-(q+d))*m,a[1]=(u+f)*m,a[2]=(e-n)*m,a[3]=0,a[4]=(u-f)*w,a[5]=(1-(c+d))*w,a[6]=(h+g)*w,a[7]=0,a[8]=(e+n)*p,a[9]=(h-g)*p,a[10]=(1-(c+q))*p,a[11]=0,a[12]=b[0]+r-(a[0]*r+a[4]*v+a[8]*k),a[13]=b[1]+v-(a[1]*r+a[5]*v+a[9]*k),a[14]=b[2]+k-(a[2]*r+a[6]*v+a[10]*k),a[15]=1,a};b.fromQuat=function(a,c){var b=c[0],p=c[1],k=c[2],l=c[3],d=b+b,f=p+p,g=k+k,b=b*d,m=p*d,p=p*f,n=k*d,E=k*f,k=k*g,d=l*d,f=l*f,l=l*g;return a[0]=1-p-k,a[1]=m+l,a[2]=n-
f,a[3]=0,a[4]=m-l,a[5]=1-b-k,a[6]=E+d,a[7]=0,a[8]=n+f,a[9]=E-d,a[10]=1-b-p,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.frustum=function(a,c,b,p,k,d,h){var e=1/(b-c),l=1/(k-p),f=1/(d-h);return a[0]=2*d*e,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=2*d*l,a[6]=0,a[7]=0,a[8]=(b+c)*e,a[9]=(k+p)*l,a[10]=(h+d)*f,a[11]=-1,a[12]=0,a[13]=0,a[14]=h*d*2*f,a[15]=0,a};b.perspective=function(a,c,b,p,k){c=1/Math.tan(c/2);var e=1/(p-k);return a[0]=c/b,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=c,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=(k+
p)*e,a[11]=-1,a[12]=0,a[13]=0,a[14]=2*k*p*e,a[15]=0,a};b.perspectiveFromFieldOfView=function(a,c,b,p){var e=Math.tan(c.upDegrees*Math.PI/180),d=Math.tan(c.downDegrees*Math.PI/180),h=Math.tan(c.leftDegrees*Math.PI/180);c=Math.tan(c.rightDegrees*Math.PI/180);var f=2/(h+c),g=2/(e+d);return a[0]=f,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=g,a[6]=0,a[7]=0,a[8]=-((h-c)*f*.5),a[9]=(e-d)*g*.5,a[10]=p/(b-p),a[11]=-1,a[12]=0,a[13]=0,a[14]=p*b/(b-p),a[15]=0,a};b.ortho=function(a,c,b,p,k,d,h){var e=1/(c-b),l=1/(p-k),
f=1/(d-h);return a[0]=-2*e,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=-2*l,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=2*f,a[11]=0,a[12]=(c+b)*e,a[13]=(k+p)*l,a[14]=(h+d)*f,a[15]=1,a};b.lookAt=function(a,c,e,p){var k,d,h,f,g,x,n,E,u,q,w=c[0],r=c[1];c=c[2];var v=p[0],y=p[1];p=p[2];var A=e[0],z=e[1];e=e[2];return Math.abs(w-A)<m.EPSILON&&Math.abs(r-z)<m.EPSILON&&Math.abs(c-e)<m.EPSILON?b.identity(a):(n=w-A,E=r-z,u=c-e,q=1/Math.sqrt(n*n+E*E+u*u),n*=q,E*=q,u*=q,k=y*u-p*E,d=p*n-v*u,h=v*E-y*n,q=Math.sqrt(k*k+d*d+h*h),q?(q=
1/q,k*=q,d*=q,h*=q):(k=0,d=0,h=0),f=E*h-u*d,g=u*k-n*h,x=n*d-E*k,q=Math.sqrt(f*f+g*g+x*x),q?(q=1/q,f*=q,g*=q,x*=q):(f=0,g=0,x=0),a[0]=k,a[1]=f,a[2]=n,a[3]=0,a[4]=d,a[5]=g,a[6]=E,a[7]=0,a[8]=h,a[9]=x,a[10]=u,a[11]=0,a[12]=-(k*w+d*r+h*c),a[13]=-(f*w+g*r+x*c),a[14]=-(n*w+E*r+u*c),a[15]=1,a)};b.str=function(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"};b.frob=function(a){return Math.sqrt(Math.pow(a[0],
2)+Math.pow(a[1],2)+Math.pow(a[2],2)+Math.pow(a[3],2)+Math.pow(a[4],2)+Math.pow(a[5],2)+Math.pow(a[6],2)+Math.pow(a[7],2)+Math.pow(a[8],2)+Math.pow(a[9],2)+Math.pow(a[10],2)+Math.pow(a[11],2)+Math.pow(a[12],2)+Math.pow(a[13],2)+Math.pow(a[14],2)+Math.pow(a[15],2))};g.exports=b},function(g,d,f){var m=f(1),b=f(4),a=f(7);d=f(8);var c={create:function(){var a=new m.ARRAY_TYPE(4);return a[0]=0,a[1]=0,a[2]=0,a[3]=1,a}};c.rotationTo=function(){var b=a.create(),p=a.fromValues(1,0,0),k=a.fromValues(0,1,0);
return function(e,d,f){var h=a.dot(d,f);return-.999999>h?(a.cross(b,p,d),1E-6>a.length(b)&&a.cross(b,k,d),a.normalize(b,b),c.setAxisAngle(e,b,Math.PI),e):.999999<h?(e[0]=0,e[1]=0,e[2]=0,e[3]=1,e):(a.cross(b,d,f),e[0]=b[0],e[1]=b[1],e[2]=b[2],e[3]=1+h,c.normalize(e,e))}}();c.setAxes=function(){var a=b.create();return function(b,e,d,h){return a[0]=d[0],a[3]=d[1],a[6]=d[2],a[1]=h[0],a[4]=h[1],a[7]=h[2],a[2]=-e[0],a[5]=-e[1],a[8]=-e[2],c.normalize(b,c.fromMat3(b,a))}}();c.clone=d.clone;c.fromValues=d.fromValues;
c.copy=d.copy;c.set=d.set;c.identity=function(a){return a[0]=0,a[1]=0,a[2]=0,a[3]=1,a};c.setAxisAngle=function(a,c,b){b*=.5;var e=Math.sin(b);return a[0]=e*c[0],a[1]=e*c[1],a[2]=e*c[2],a[3]=Math.cos(b),a};c.add=d.add;c.multiply=function(a,c,b){var e=c[0],d=c[1],k=c[2];c=c[3];var p=b[0],f=b[1],g=b[2];b=b[3];return a[0]=e*b+c*p+d*g-k*f,a[1]=d*b+c*f+k*p-e*g,a[2]=k*b+c*g+e*f-d*p,a[3]=c*b-e*p-d*f-k*g,a};c.mul=c.multiply;c.scale=d.scale;c.rotateX=function(a,c,b){b*=.5;var e=c[0],d=c[1],k=c[2];c=c[3];var p=
Math.sin(b);b=Math.cos(b);return a[0]=e*b+c*p,a[1]=d*b+k*p,a[2]=k*b-d*p,a[3]=c*b-e*p,a};c.rotateY=function(a,c,b){b*=.5;var e=c[0],d=c[1],p=c[2];c=c[3];var k=Math.sin(b);b=Math.cos(b);return a[0]=e*b-p*k,a[1]=d*b+c*k,a[2]=p*b+e*k,a[3]=c*b-d*k,a};c.rotateZ=function(a,c,b){b*=.5;var e=c[0],d=c[1],p=c[2];c=c[3];var k=Math.sin(b);b=Math.cos(b);return a[0]=e*b+d*k,a[1]=d*b-e*k,a[2]=p*b+c*k,a[3]=c*b-p*k,a};c.calculateW=function(a,c){var b=c[0],e=c[1],d=c[2];return a[0]=b,a[1]=e,a[2]=d,a[3]=Math.sqrt(Math.abs(1-
b*b-e*e-d*d)),a};c.dot=d.dot;c.lerp=d.lerp;c.slerp=function(a,c,b,d){var e,p,k,f,l,g=c[0],m=c[1],q=c[2];c=c[3];var w=b[0],r=b[1],v=b[2];b=b[3];return p=g*w+m*r+q*v+c*b,0>p&&(p=-p,w=-w,r=-r,v=-v,b=-b),1E-6<1-p?(e=Math.acos(p),k=Math.sin(e),f=Math.sin((1-d)*e)/k,l=Math.sin(d*e)/k):(f=1-d,l=d),a[0]=f*g+l*w,a[1]=f*m+l*r,a[2]=f*q+l*v,a[3]=f*c+l*b,a};c.sqlerp=function(){var a=c.create(),b=c.create();return function(e,d,p,f,g,m){return c.slerp(a,d,g,m),c.slerp(b,p,f,m),c.slerp(e,a,b,2*m*(1-m)),e}}();c.invert=
function(a,c){var b=c[0],e=c[1],d=c[2],p=c[3],f=b*b+e*e+d*d+p*p,f=f?1/f:0;return a[0]=-b*f,a[1]=-e*f,a[2]=-d*f,a[3]=p*f,a};c.conjugate=function(a,c){return a[0]=-c[0],a[1]=-c[1],a[2]=-c[2],a[3]=c[3],a};c.length=d.length;c.len=c.length;c.squaredLength=d.squaredLength;c.sqrLen=c.squaredLength;c.normalize=d.normalize;c.fromMat3=function(a,c){var b;b=c[0]+c[4]+c[8];if(0<b)b=Math.sqrt(b+1),a[3]=.5*b,b=.5/b,a[0]=(c[5]-c[7])*b,a[1]=(c[6]-c[2])*b,a[2]=(c[1]-c[3])*b;else{var e=0;c[4]>c[0]&&(e=1);c[8]>c[3*
e+e]&&(e=2);var d=(e+1)%3,p=(e+2)%3;b=Math.sqrt(c[3*e+e]-c[3*d+d]-c[3*p+p]+1);a[e]=.5*b;b=.5/b;a[3]=(c[3*d+p]-c[3*p+d])*b;a[d]=(c[3*d+e]+c[3*e+d])*b;a[p]=(c[3*p+e]+c[3*e+p])*b}return a};c.str=function(a){return"quat("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};g.exports=c},function(g,d,f){var m=f(1),b={create:function(){var a=new m.ARRAY_TYPE(3);return a[0]=0,a[1]=0,a[2]=0,a},clone:function(a){var c=new m.ARRAY_TYPE(3);return c[0]=a[0],c[1]=a[1],c[2]=a[2],c},fromValues:function(a,c,b){var e=new m.ARRAY_TYPE(3);
return e[0]=a,e[1]=c,e[2]=b,e},copy:function(a,c){return a[0]=c[0],a[1]=c[1],a[2]=c[2],a},set:function(a,c,b,d){return a[0]=c,a[1]=b,a[2]=d,a},add:function(a,c,b){return a[0]=c[0]+b[0],a[1]=c[1]+b[1],a[2]=c[2]+b[2],a},subtract:function(a,c,b){return a[0]=c[0]-b[0],a[1]=c[1]-b[1],a[2]=c[2]-b[2],a}};b.sub=b.subtract;b.multiply=function(a,c,b){return a[0]=c[0]*b[0],a[1]=c[1]*b[1],a[2]=c[2]*b[2],a};b.mul=b.multiply;b.divide=function(a,c,b){return a[0]=c[0]/b[0],a[1]=c[1]/b[1],a[2]=c[2]/b[2],a};b.div=
b.divide;b.min=function(a,c,b){return a[0]=Math.min(c[0],b[0]),a[1]=Math.min(c[1],b[1]),a[2]=Math.min(c[2],b[2]),a};b.max=function(a,c,b){return a[0]=Math.max(c[0],b[0]),a[1]=Math.max(c[1],b[1]),a[2]=Math.max(c[2],b[2]),a};b.scale=function(a,c,b){return a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b,a};b.scaleAndAdd=function(a,c,b,d){return a[0]=c[0]+b[0]*d,a[1]=c[1]+b[1]*d,a[2]=c[2]+b[2]*d,a};b.distance=function(a,c){var b=c[0]-a[0],d=c[1]-a[1],k=c[2]-a[2];return Math.sqrt(b*b+d*d+k*k)};b.dist=b.distance;b.squaredDistance=
function(a,c){var b=c[0]-a[0],d=c[1]-a[1],k=c[2]-a[2];return b*b+d*d+k*k};b.sqrDist=b.squaredDistance;b.length=function(a){var c=a[0],b=a[1];a=a[2];return Math.sqrt(c*c+b*b+a*a)};b.len=b.length;b.squaredLength=function(a){var c=a[0],b=a[1];a=a[2];return c*c+b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,c){return a[0]=-c[0],a[1]=-c[1],a[2]=-c[2],a};b.inverse=function(a,c){return a[0]=1/c[0],a[1]=1/c[1],a[2]=1/c[2],a};b.normalize=function(a,c){var b=c[0],d=c[1],k=c[2],b=b*b+d*d+k*k;return 0<
b&&(b=1/Math.sqrt(b),a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b),a};b.dot=function(a,c){return a[0]*c[0]+a[1]*c[1]+a[2]*c[2]};b.cross=function(a,c,b){var e=c[0],d=c[1];c=c[2];var f=b[0],h=b[1];b=b[2];return a[0]=d*b-c*h,a[1]=c*f-e*b,a[2]=e*h-d*f,a};b.lerp=function(a,c,b,d){var e=c[0],f=c[1];c=c[2];return a[0]=e+d*(b[0]-e),a[1]=f+d*(b[1]-f),a[2]=c+d*(b[2]-c),a};b.hermite=function(a,c,b,d,f,l){var e=l*l,k=e*(2*l-3)+1,p=e*(l-2)+l,g=e*(l-1);l=e*(3-2*l);return a[0]=c[0]*k+b[0]*p+d[0]*g+f[0]*l,a[1]=c[1]*k+b[1]*
p+d[1]*g+f[1]*l,a[2]=c[2]*k+b[2]*p+d[2]*g+f[2]*l,a};b.bezier=function(a,c,b,d,f,g){var e=1-g,k=e*e,p=g*g,l=k*e,k=3*g*k,e=3*p*e;g*=p;return a[0]=c[0]*l+b[0]*k+d[0]*e+f[0]*g,a[1]=c[1]*l+b[1]*k+d[1]*e+f[1]*g,a[2]=c[2]*l+b[2]*k+d[2]*e+f[2]*g,a};b.random=function(a,c){c=c||1;var b=2*m.RANDOM()*Math.PI,d=2*m.RANDOM()-1,f=Math.sqrt(1-d*d)*c;return a[0]=Math.cos(b)*f,a[1]=Math.sin(b)*f,a[2]=d*c,a};b.transformMat4=function(a,c,b){var e=c[0],d=c[1];c=c[2];var f=b[3]*e+b[7]*d+b[11]*c+b[15];return f=f||1,a[0]=
(b[0]*e+b[4]*d+b[8]*c+b[12])/f,a[1]=(b[1]*e+b[5]*d+b[9]*c+b[13])/f,a[2]=(b[2]*e+b[6]*d+b[10]*c+b[14])/f,a};b.transformMat3=function(a,c,b){var e=c[0],d=c[1];c=c[2];return a[0]=e*b[0]+d*b[3]+c*b[6],a[1]=e*b[1]+d*b[4]+c*b[7],a[2]=e*b[2]+d*b[5]+c*b[8],a};b.transformQuat=function(a,c,b){var e=c[0],d=c[1],f=c[2];c=b[0];var g=b[1],m=b[2];b=b[3];var N=b*e+g*f-m*d,x=b*d+m*e-c*f,n=b*f+c*d-g*e,e=-c*e-g*d-m*f;return a[0]=N*b+e*-c+x*-m-n*-g,a[1]=x*b+e*-g+n*-c-N*-m,a[2]=n*b+e*-m+N*-g-x*-c,a};b.rotateX=function(a,
c,b,d){var e=[],f=[];return e[0]=c[0]-b[0],e[1]=c[1]-b[1],e[2]=c[2]-b[2],f[0]=e[0],f[1]=e[1]*Math.cos(d)-e[2]*Math.sin(d),f[2]=e[1]*Math.sin(d)+e[2]*Math.cos(d),a[0]=f[0]+b[0],a[1]=f[1]+b[1],a[2]=f[2]+b[2],a};b.rotateY=function(a,c,b,d){var e=[],f=[];return e[0]=c[0]-b[0],e[1]=c[1]-b[1],e[2]=c[2]-b[2],f[0]=e[2]*Math.sin(d)+e[0]*Math.cos(d),f[1]=e[1],f[2]=e[2]*Math.cos(d)-e[0]*Math.sin(d),a[0]=f[0]+b[0],a[1]=f[1]+b[1],a[2]=f[2]+b[2],a};b.rotateZ=function(a,c,b,d){var e=[],f=[];return e[0]=c[0]-b[0],
e[1]=c[1]-b[1],e[2]=c[2]-b[2],f[0]=e[0]*Math.cos(d)-e[1]*Math.sin(d),f[1]=e[0]*Math.sin(d)+e[1]*Math.cos(d),f[2]=e[2],a[0]=f[0]+b[0],a[1]=f[1]+b[1],a[2]=f[2]+b[2],a};b.forEach=function(){var a=b.create();return function(c,b,d,f,g,h){b||(b=3);d||(d=0);for(f=f?Math.min(f*b+d,c.length):c.length;f>d;d+=b)a[0]=c[d],a[1]=c[d+1],a[2]=c[d+2],g(a,a,h),c[d]=a[0],c[d+1]=a[1],c[d+2]=a[2];return c}}();b.angle=function(a,c){var e=b.fromValues(a[0],a[1],a[2]),d=b.fromValues(c[0],c[1],c[2]);b.normalize(e,e);b.normalize(d,
d);e=b.dot(e,d);return 1<e?0:Math.acos(e)};b.str=function(a){return"vec3("+a[0]+", "+a[1]+", "+a[2]+")"};g.exports=b},function(g,d,f){var m=f(1),b={create:function(){var a=new m.ARRAY_TYPE(4);return a[0]=0,a[1]=0,a[2]=0,a[3]=0,a},clone:function(a){var c=new m.ARRAY_TYPE(4);return c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c},fromValues:function(a,c,b,d){var e=new m.ARRAY_TYPE(4);return e[0]=a,e[1]=c,e[2]=b,e[3]=d,e},copy:function(a,c){return a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a},set:function(a,
c,b,d,f){return a[0]=c,a[1]=b,a[2]=d,a[3]=f,a},add:function(a,c,b){return a[0]=c[0]+b[0],a[1]=c[1]+b[1],a[2]=c[2]+b[2],a[3]=c[3]+b[3],a},subtract:function(a,c,b){return a[0]=c[0]-b[0],a[1]=c[1]-b[1],a[2]=c[2]-b[2],a[3]=c[3]-b[3],a}};b.sub=b.subtract;b.multiply=function(a,c,b){return a[0]=c[0]*b[0],a[1]=c[1]*b[1],a[2]=c[2]*b[2],a[3]=c[3]*b[3],a};b.mul=b.multiply;b.divide=function(a,b,e){return a[0]=b[0]/e[0],a[1]=b[1]/e[1],a[2]=b[2]/e[2],a[3]=b[3]/e[3],a};b.div=b.divide;b.min=function(a,b,e){return a[0]=
Math.min(b[0],e[0]),a[1]=Math.min(b[1],e[1]),a[2]=Math.min(b[2],e[2]),a[3]=Math.min(b[3],e[3]),a};b.max=function(a,b,e){return a[0]=Math.max(b[0],e[0]),a[1]=Math.max(b[1],e[1]),a[2]=Math.max(b[2],e[2]),a[3]=Math.max(b[3],e[3]),a};b.scale=function(a,b,e){return a[0]=b[0]*e,a[1]=b[1]*e,a[2]=b[2]*e,a[3]=b[3]*e,a};b.scaleAndAdd=function(a,b,e,d){return a[0]=b[0]+e[0]*d,a[1]=b[1]+e[1]*d,a[2]=b[2]+e[2]*d,a[3]=b[3]+e[3]*d,a};b.distance=function(a,b){var c=b[0]-a[0],d=b[1]-a[1],f=b[2]-a[2],g=b[3]-a[3];return Math.sqrt(c*
c+d*d+f*f+g*g)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],d=b[1]-a[1],f=b[2]-a[2],g=b[3]-a[3];return c*c+d*d+f*f+g*g};b.sqrDist=b.squaredDistance;b.length=function(a){var b=a[0],e=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+e*e+d*d+a*a)};b.len=b.length;b.squaredLength=function(a){var b=a[0],e=a[1],d=a[2];a=a[3];return b*b+e*e+d*d+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){return a[0]=-b[0],a[1]=-b[1],a[2]=-b[2],a[3]=-b[3],a};b.inverse=function(a,b){return a[0]=1/b[0],
a[1]=1/b[1],a[2]=1/b[2],a[3]=1/b[3],a};b.normalize=function(a,b){var c=b[0],d=b[1],f=b[2],g=b[3],h=c*c+d*d+f*f+g*g;return 0<h&&(h=1/Math.sqrt(h),a[0]=c*h,a[1]=d*h,a[2]=f*h,a[3]=g*h),a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};b.lerp=function(a,b,e,d){var c=b[0],f=b[1],g=b[2];b=b[3];return a[0]=c+d*(e[0]-c),a[1]=f+d*(e[1]-f),a[2]=g+d*(e[2]-g),a[3]=b+d*(e[3]-b),a};b.random=function(a,c){return c=c||1,a[0]=m.RANDOM(),a[1]=m.RANDOM(),a[2]=m.RANDOM(),a[3]=m.RANDOM(),b.normalize(a,
a),b.scale(a,a,c),a};b.transformMat4=function(a,b,e){var c=b[0],d=b[1],f=b[2];b=b[3];return a[0]=e[0]*c+e[4]*d+e[8]*f+e[12]*b,a[1]=e[1]*c+e[5]*d+e[9]*f+e[13]*b,a[2]=e[2]*c+e[6]*d+e[10]*f+e[14]*b,a[3]=e[3]*c+e[7]*d+e[11]*f+e[15]*b,a};b.transformQuat=function(a,b,e){var c=b[0],d=b[1],f=b[2],g=e[0],m=e[1],N=e[2];e=e[3];var x=e*c+m*f-N*d,n=e*d+N*c-g*f,E=e*f+g*d-m*c,c=-g*c-m*d-N*f;return a[0]=x*e+c*-g+n*-N-E*-m,a[1]=n*e+c*-m+E*-g-x*-N,a[2]=E*e+c*-N+x*-m-n*-g,a[3]=b[3],a};b.forEach=function(){var a=b.create();
return function(b,e,d,f,g,h){e||(e=4);d||(d=0);for(f=f?Math.min(f*e+d,b.length):b.length;f>d;d+=e)a[0]=b[d],a[1]=b[d+1],a[2]=b[d+2],a[3]=b[d+3],g(a,a,h),b[d]=a[0],b[d+1]=a[1],b[d+2]=a[2],b[d+3]=a[3];return b}}();b.str=function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};g.exports=b},function(g,d,f){var m=f(1),b={create:function(){var a=new m.ARRAY_TYPE(2);return a[0]=0,a[1]=0,a},clone:function(a){var b=new m.ARRAY_TYPE(2);return b[0]=a[0],b[1]=a[1],b},fromValues:function(a,b){var c=new m.ARRAY_TYPE(2);
return c[0]=a,c[1]=b,c},copy:function(a,b){return a[0]=b[0],a[1]=b[1],a},set:function(a,b,e){return a[0]=b,a[1]=e,a},add:function(a,b,e){return a[0]=b[0]+e[0],a[1]=b[1]+e[1],a},subtract:function(a,b,e){return a[0]=b[0]-e[0],a[1]=b[1]-e[1],a}};b.sub=b.subtract;b.multiply=function(a,b,e){return a[0]=b[0]*e[0],a[1]=b[1]*e[1],a};b.mul=b.multiply;b.divide=function(a,b,e){return a[0]=b[0]/e[0],a[1]=b[1]/e[1],a};b.div=b.divide;b.min=function(a,b,e){return a[0]=Math.min(b[0],e[0]),a[1]=Math.min(b[1],e[1]),
a};b.max=function(a,b,e){return a[0]=Math.max(b[0],e[0]),a[1]=Math.max(b[1],e[1]),a};b.scale=function(a,b,e){return a[0]=b[0]*e,a[1]=b[1]*e,a};b.scaleAndAdd=function(a,b,e,d){return a[0]=b[0]+e[0]*d,a[1]=b[1]+e[1]*d,a};b.distance=function(a,b){var c=b[0]-a[0],d=b[1]-a[1];return Math.sqrt(c*c+d*d)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],d=b[1]-a[1];return c*c+d*d};b.sqrDist=b.squaredDistance;b.length=function(a){var b=a[0];a=a[1];return Math.sqrt(b*b+a*a)};b.len=b.length;
b.squaredLength=function(a){var b=a[0];a=a[1];return b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){return a[0]=-b[0],a[1]=-b[1],a};b.inverse=function(a,b){return a[0]=1/b[0],a[1]=1/b[1],a};b.normalize=function(a,b){var c=b[0],d=b[1],c=c*c+d*d;return 0<c&&(c=1/Math.sqrt(c),a[0]=b[0]*c,a[1]=b[1]*c),a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]};b.cross=function(a,b,e){b=b[0]*e[1]-b[1]*e[0];return a[0]=a[1]=0,a[2]=b,a};b.lerp=function(a,b,e,d){var c=b[0];b=b[1];return a[0]=c+d*(e[0]-c),
a[1]=b+d*(e[1]-b),a};b.random=function(a,b){b=b||1;var c=2*m.RANDOM()*Math.PI;return a[0]=Math.cos(c)*b,a[1]=Math.sin(c)*b,a};b.transformMat2=function(a,b,e){var c=b[0];b=b[1];return a[0]=e[0]*c+e[2]*b,a[1]=e[1]*c+e[3]*b,a};b.transformMat2d=function(a,b,e){var c=b[0];b=b[1];return a[0]=e[0]*c+e[2]*b+e[4],a[1]=e[1]*c+e[3]*b+e[5],a};b.transformMat3=function(a,b,e){var c=b[0];b=b[1];return a[0]=e[0]*c+e[3]*b+e[6],a[1]=e[1]*c+e[4]*b+e[7],a};b.transformMat4=function(a,b,e){var c=b[0];b=b[1];return a[0]=
e[0]*c+e[4]*b+e[12],a[1]=e[1]*c+e[5]*b+e[13],a};b.forEach=function(){var a=b.create();return function(b,e,d,f,g,h){e||(e=2);d||(d=0);for(f=f?Math.min(f*e+d,b.length):b.length;f>d;d+=e)a[0]=b[d],a[1]=b[d+1],g(a,a,h),b[d]=a[0],b[d+1]=a[1];return b}}();b.str=function(a){return"vec2("+a[0]+", "+a[1]+")"};g.exports=b}])});
function getShader(g,d,f){f?(g=retrieveShader(g,"vertex"),d=retrieveShader(d,"fragment")):(g=shader(g),d=shader(d));f=gl.createProgram();gl.attachShader(f,g);gl.attachShader(f,d);gl.linkProgram(f);return gl.getProgramParameter(f,gl.LINK_STATUS)?f:(alert("Could not initialise shaders"),null)}function retrieveShader(g,d){}
function shader(g){var d=document.getElementById(g);if(!d)return null;for(var f="",m=d.firstChild;m;)3==m.nodeType&&(f+=m.textContent),m=m.nextSibling;if("frag"==d.type)d=gl.createShader(gl.FRAGMENT_SHADER);else if("vert"==d.type)d=gl.createShader(gl.VERTEX_SHADER);else return null;gl.shaderSource(d,f);gl.compileShader(d);return gl.getShaderParameter(d,gl.COMPILE_STATUS)?d:(alert(gl.getShaderInfoLog(d)+"  "+g),null)}
function createCamera(){this.getViewMatrix=getViewMatrix;this.params=camera_params;this.camera_keydown=camera_keydown;this.camera_keyup=camera_keyup;this.camera_mousemove=camera_mousemove;this.camera_mousedown=camera_mousedown;this.camera_mouseup=camera_mouseup;this.camera_zoom=camera_zoom;this.pos=vec3.fromValues(0,0,0);this.up=vec3.fromValues(0,1,0);this.front=vec3.fromValues(0,0,-1);this.frontCross=vec3.fromValues(0,0,0);this.dir=vec3.fromValues(0,0,0);this.speed=5;this.zoom_smoothness=.1;this.autoRotate=
this.autoCentered=!1;this.radius=this.autoRotateSpeed=3;this.look=[0,0,0];this.mousecontrols=!0;this.lookAt=mat4.create();this.yaw=-1.57;this.pitch=0;this.deltaRot=[0,0];this.lastPos=[null,null];this.deltazoom=0;this.dragging=!1;this.startingZoom=window.zoom;this.zoomdefined=!1;this.smoothDeltaTimeCheck=!0;this.rotationSensitivity=.002;this.pressedKeys={w:!1,s:!1,a:!1,d:!1,space:!1,shift:!1,la:!1,ua:!1,ra:!1,da:!1};this.mousecontrols&&(window.addEventListener("keydown",this.camera_keydown.bind(this)),
window.addEventListener("keyup",this.camera_keyup.bind(this)),document.getElementById("canvas").addEventListener("mousemove",this.camera_mousemove.bind(this)),document.getElementById("canvas").addEventListener("mousedown",this.camera_mousedown.bind(this)),window.addEventListener("mouseup",this.camera_mouseup.bind(this)),window.addEventListener("mousewheel",this.camera_zoom.bind(this)),window.addEventListener("DOMMouseScroll",this.camera_zoom.bind(this)))}
function camera_params(g,d,f,m,b){void 0!==g&&(this.zoom_smoothness=g);void 0!==d&&(this.speed=d);void 0!==f&&(this.startingZoom=f);void 0!==m&&(this.smoothDeltaTimeCheck=m);void 0!==b&&(this.rotationSensitivity=b)}
function getViewMatrix(g,d){this.smoothDeltaTimeCheck&&.03333>=g&&!(.01>g)&&(g=.016);this.zoomdefined||(this.startingZoom=zoom,this.zoomdefined=!0);if(this.autoCentered)return camera_getAutocenteredViewMatrix.call(this,g,d,this.radius);if(this.pressedKeys.w||this.pressedKeys.ua)this.pos[0]+=g*this.speed*this.front[0],this.pos[1]+=g*this.speed*this.front[1],this.pos[2]+=g*this.speed*this.front[2];if(this.pressedKeys.s||this.pressedKeys.da)this.pos[0]-=g*this.speed*this.front[0],this.pos[1]-=g*this.speed*
this.front[1],this.pos[2]-=g*this.speed*this.front[2];if(this.pressedKeys.d||this.pressedKeys.ra)this.frontCross=vec3.cross(this.frontCross,this.front,this.up),vec3.normalize(this.frontCross,this.frontCross),this.pos[0]+=g*this.speed*this.frontCross[0],this.pos[1]+=g*this.speed*this.frontCross[1],this.pos[2]+=g*this.speed*this.frontCross[2];if(this.pressedKeys.a||this.pressedKeys.la)this.frontCross=vec3.cross(this.frontCross,this.front,this.up),vec3.normalize(this.frontCross,this.frontCross),this.pos[0]-=
g*this.speed*this.frontCross[0],this.pos[1]-=g*this.speed*this.frontCross[1],this.pos[2]-=g*this.speed*this.frontCross[2];this.pressedKeys.space&&(this.pos[0]+=g*this.speed*this.up[0],this.pos[1]+=g*this.speed*this.up[1],this.pos[2]+=g*this.speed*this.up[2]);this.pressedKeys.shift&&(this.pos[0]-=g*this.speed*this.up[0],this.pos[1]-=g*this.speed*this.up[1],this.pos[2]-=g*this.speed*this.up[2]);this.yaw+=this.deltaRot[0]*d;this.pitch-=this.deltaRot[1]*d;this.deltaRot[0]-=this.deltaRot[0]*d;this.deltaRot[1]-=
this.deltaRot[1]*d;1.565<this.pitch&&(this.pitch=1.565);-1.565>this.pitch&&(this.pitch=-1.565);this.front[0]=Math.cos(this.yaw)*Math.cos(this.pitch);this.front[1]=Math.sin(this.pitch);this.front[2]=Math.sin(this.yaw)*Math.cos(this.pitch);vec3.normalize(this.front,this.front);if(0<Math.abs(this.deltazoom)){var f=this.deltazoom*this.zoom_smoothness;0>this.deltazoom&&(this.deltazoom=-.01>this.deltazoom?this.deltazoom-f:0);0<this.deltazoom&&(this.deltazoom=.01<this.deltazoom?this.deltazoom-f:0);zoom+=
f;44.5>zoom&&(zoom=44.5);zoom>this.startingZoom&&(zoom=this.startingZoom)}this.dir[0]=this.pos[0]+this.front[0];this.dir[1]=this.pos[1]+this.front[1];this.dir[2]=this.pos[2]+this.front[2];mat4.lookAt(this.lookAt,this.pos,this.dir,this.up);return this.lookAt}
function camera_keydown(g){switch(g.keyCode){case 87:this.pressedKeys.w=!0;break;case 65:this.pressedKeys.a=!0;break;case 83:this.pressedKeys.s=!0;break;case 68:this.pressedKeys.d=!0;break;case 32:this.pressedKeys.space=!0;break;case 16:this.pressedKeys.shift=!0;break;case 37:this.pressedKeys.la=!0;break;case 38:this.pressedKeys.ua=!0;break;case 39:this.pressedKeys.ra=!0;break;case 40:this.pressedKeys.da=!0}}
function camera_keyup(g){switch(g.keyCode){case 87:this.pressedKeys.w=!1;break;case 65:this.pressedKeys.a=!1;break;case 83:this.pressedKeys.s=!1;break;case 68:this.pressedKeys.d=!1;break;case 32:this.pressedKeys.space=!1;break;case 16:this.pressedKeys.shift=!1;break;case 37:this.pressedKeys.la=!1;break;case 38:this.pressedKeys.ua=!1;break;case 39:this.pressedKeys.ra=!1;break;case 40:this.pressedKeys.da=!1}}
function camera_mousemove(g){this.dragging&&(this.deltaRot[0]+=(g.clientX-this.lastPos[0])*this.rotationSensitivity,this.deltaRot[1]+=(g.clientY-this.lastPos[1])*this.rotationSensitivity,this.lastPos[0]=g.clientX,this.lastPos[1]=g.clientY)}function camera_mousedown(g){1==g.which&&(this.lastPos[0]=g.clientX,this.lastPos[1]=g.clientY,this.dragging=!0)}function camera_mouseup(g){this.dragging=!1}
function camera_zoom(g){this.deltazoom=0<(g.wheelDelta?g.wheelDelta:-g.detail)?this.deltazoom+-.15:this.deltazoom+.15}
function camera_getAutocenteredViewMatrix(g,d,f){this.yaw+=this.deltaRot[0]*d;this.pitch-=this.deltaRot[1]*d;this.autoRotate&&(this.yaw+=this.autoRotateSpeed/180*Math.PI*g);this.deltaRot[0]-=this.deltaRot[0]*d;this.deltaRot[1]-=this.deltaRot[1]*d;1.565<this.pitch&&(this.pitch=1.565);-1.565>this.pitch&&(this.pitch=-1.565);0<Math.abs(this.deltazoom)&&(g=this.deltazoom*this.zoom_smoothness,0>this.deltazoom&&(this.deltazoom=-.01>this.deltazoom?this.deltazoom-g:0),0<this.deltazoom&&(this.deltazoom=.01<
this.deltazoom?this.deltazoom-g:0),zoom+=g,44.5>zoom&&(zoom=44.5),zoom>this.startingZoom&&(zoom=this.startingZoom));g=Math.sin(this.yaw)*Math.cos(this.pitch)*f;d=Math.sin(this.pitch)*f;this.pos[0]=Math.cos(this.yaw)*Math.cos(this.pitch)*f+this.look[0];this.pos[1]=d+this.look[1];this.pos[2]=-g+this.look[2];mat4.lookAt(this.lookAt,this.pos,this.look,this.up);return this.lookAt}
var buffer,Program,finalBuffer,finalProgram,pongProgram,pongBuffer,jsonStruct,texture,glyph_texture,skull_texture,boundingVertices=[],rows=0,columns=500,zoom=45,textureAlpha=0,textureBlurAlpha=0,WaitTime=2.5,pongFramebuffer,pongFramebufferTexture,pingFramebuffer,pingFramebufferTexture,displayFramebuffer,displayFramebufferTexture,opacity=[],chars=[],changer=[],percentage=.5,traverser=[],Kpressed=!1,DistanceTrigger=!1,wwidth,quadSize,camera,projection=mat4.create(),model=mat4.create(),view=mat4.create();
window.onload=function(){var g=document.getElementById("canvas");g.width=window.innerWidth;g.height=window.innerHeight;document.addEventListener("keydown",keypress);document.addEventListener("keyup",keyup);camera=new createCamera;camera.speed=7.5;var d=["webgl","experimental-webgl","webkit-3d","mozwebgl"],f;for(f in d)try{if((gl=g.getContext(d[f],{premultipliedAlpha:!1}))&&"function"==typeof gl.getParameter)break}catch(l){}null==gl&&alert("could not initialize webGL");gl.getExtension("OES_texture_float");
setAudio();var m=new XMLHttpRequest;m.onreadystatechange=function(){4==m.readyState&&200==m.status&&(jsonStruct=JSON.parse(m.responseText))};m.open("GET","timevals.json",!0);m.send();Program=getShader("vertex","fragment",!1);Program.a1=gl.getAttribLocation(Program,"pos");Program.a2=gl.getAttribLocation(Program,"coord");Program.floatingTex=gl.getUniformLocation(Program,"floatingTex");Program.glyphs=gl.getUniformLocation(Program,"glyphs");Program.rows=gl.getUniformLocation(Program,"rows");Program.columns=
gl.getUniformLocation(Program,"columns");Program.Time=gl.getUniformLocation(Program,"Time");Program.rotator=gl.getUniformLocation(Program,"rotator");Program.values=gl.getUniformLocation(Program,"values");Program.world_width=gl.getUniformLocation(Program,"world_width");Program.quadSize=gl.getUniformLocation(Program,"quadSize");Program.projection=gl.getUniformLocation(Program,"projection");Program.model=gl.getUniformLocation(Program,"model");Program.view=gl.getUniformLocation(Program,"view");gl.enableVertexAttribArray(Program.a1);
gl.enableVertexAttribArray(Program.a2);wwidth=2*getBoundingVertices(zoom,window.innerWidth/window.innerHeight,45.5)[2][1];boundingVertices=getBoundingVertices(zoom,window.innerWidth/window.innerHeight,30);g=2*boundingVertices[2][1];quadSize=d=2*boundingVertices[2][0]/120;rows=Math.floor(g/d+5);array=new Float32Array(rows*columns*4);var b=[];for(f=0;f<columns;f++)traverser[f]={active:9999,wait:2.5*Math.random(),incrementor:.85*Math.pow(Math.random(),1.8)+.15};for(f=0;f<rows*columns;f++)opacity.push(0);
for(f=0;f<rows*columns;f++)chars.push(0);percentage=Math.floor(rows*columns*percentage);for(f=0;f<percentage;f++)changer.push(Math.floor(Math.random()*rows*columns));var a=[];for(f=0;f<columns;f++)a.push(f);for(f=0;f<columns;f++){var c=(columns-f)/columns;.5>=c?(c*=2,c=Math.pow(c,.3),depth=28*-c-2):(c=2*(c-.5),c=Math.pow(c,3),depth=25.5*-c-30);var e=Math.floor(Math.random()*a.length),c=a[e];a.splice(e,1);e=2*getBoundingVertices(zoom,window.innerWidth/window.innerHeight,depth)[2][0];c=e/columns*c-
e/2;for(e=0;e<rows;e++)for(var p=g/2-e*d,p=[c,p-d,depth,0,0,e,f,c,p,depth,0,.0625,e,f,c+d,p-d,depth,1,0,e,f,c+d,p-d,depth,1,0,e,f,c,p,depth,0,.0625,e,f,c+d,p,depth,1,.0625,e,f],k=0;42>k;k++)b.push(p[k])}buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(b),gl.STATIC_DRAW);f=Float32Array.BYTES_PER_ELEMENT;gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,7*f,0);gl.vertexAttribPointer(Program.a2,4,gl.FLOAT,!1,7*f,3*f);pongFramebuffer=gl.createFramebuffer();
gl.bindFramebuffer(gl.FRAMEBUFFER,pongFramebuffer);pongFramebuffer.width=window.innerWidth;pongFramebuffer.height=window.innerHeight;pongFramebufferTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,
0,gl.RGBA,pongFramebuffer.width,pongFramebuffer.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);f=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,f);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,pongFramebuffer.width,pongFramebuffer.height);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,pongFramebufferTexture,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,f);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindRenderbuffer(gl.RENDERBUFFER,
null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);pingFramebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,pingFramebuffer);pingFramebuffer.width=window.innerWidth;pingFramebuffer.height=window.innerHeight;pingFramebufferTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,pingFramebufferTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,pingFramebuffer.width,pingFramebuffer.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);f=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,f);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,pingFramebuffer.width,pingFramebuffer.height);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,pingFramebufferTexture,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,
gl.RENDERBUFFER,f);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindRenderbuffer(gl.RENDERBUFFER,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);pongProgram=getShader("pvertex","pfragment",!1);pongProgram.a1=gl.getAttribLocation(pongProgram,"pos");pongProgram.texture=gl.getUniformLocation(pongProgram,"texture");pongProgram.hor=gl.getUniformLocation(pongProgram,"hor");pongBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pongBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,1,0,0,1,1,
1]),gl.STATIC_DRAW);displayFramebuffer=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,displayFramebuffer);displayFramebuffer.width=window.innerWidth;displayFramebuffer.height=window.innerHeight;displayFramebufferTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,displayFramebufferTexture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,displayFramebuffer.width,displayFramebuffer.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);f=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,f);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,displayFramebuffer.width,displayFramebuffer.height);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,displayFramebufferTexture,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,
gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,f);gl.bindTexture(gl.TEXTURE_2D,null);gl.bindRenderbuffer(gl.RENDERBUFFER,null);gl.bindFramebuffer(gl.FRAMEBUFFER,null);p=[0,0,0,1,1,0,1,0,0,1,1,1];finalProgram=getShader("fvertex","ffragment",!1);finalProgram.a1=gl.getAttribLocation(finalProgram,"pos");finalProgram.blurtexture=gl.getUniformLocation(finalProgram,"blurtexture");finalProgram.displaytexture=gl.getUniformLocation(finalProgram,"displaytexture");finalProgram.skulltexture=gl.getUniformLocation(finalProgram,
"skulltexture");finalProgram.textureAlpha=gl.getUniformLocation(finalProgram,"textureAlpha");finalProgram.screenRatio=gl.getUniformLocation(finalProgram,"screenRatio");finalProgram.blurAlpha=gl.getUniformLocation(finalProgram,"blurAlpha");finalProgram.textureBlurAlpha=gl.getUniformLocation(finalProgram,"textureBlurAlpha");finalBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,finalBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(p),gl.STATIC_DRAW);texture=generateTexture();glyph_texture=
generateGlyphTexture();skull_texture=skullTexture();requestAnimationFrame(draw)};var array,then=0,controller=0,changerRotator=0,rotator=0,distanceRotator=86,deltamax=0,auto_cascade_not_released=!0;
function draw(g){requestAnimationFrame(draw);var d=Float32Array.BYTES_PER_ELEMENT;g*=.001;var f=g-then;then=g;if(started){changerRotator+=f;mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,1.5,100);mat4.identity(model);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.DEPTH_TEST);gl.bindFramebuffer(gl.FRAMEBUFFER,displayFramebuffer);gl.useProgram(Program);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|
gl.DEPTH_BUFFER_BIT);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(Program.a1);gl.enableVertexAttribArray(Program.a2);gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,7*d,0);gl.vertexAttribPointer(Program.a2,4,gl.FLOAT,!1,7*d,3*d);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,model);gl.uniformMatrix4fv(Program.view,!1,camera.getViewMatrix(f,.3));gl.uniform1f(Program.rows,rows);gl.uniform1f(Program.columns,columns);distanceRotator+=f;DistanceTrigger&&
(distanceRotator+=30*f);gl.uniform1f(Program.Time,2*distanceRotator%90);gl.uniform1f(Program.rotator,rotator);gl.uniform1f(Program.world_width,wwidth);gl.uniform1f(Program.quadSize,quadSize);analyser.getByteFrequencyData(frequencyArray);analyser.getFloatTimeDomainData(dataArray);for(var m=g=0,d=0;d<frequencyArray.length;d++)85>d&&(g+=frequencyArray[d]),dataArray[d]>m&&(m=dataArray[d]),averageArray[d]+=.045*(dataArray[d]-averageArray[d]),averageArray[d]=frequencyArray[d];g/=frequencyArray.length;g/=
128;rotator+=150*f*m;gl.uniform4fv(Program.values,averageArray);for(d=0;d<columns;d++)m=traverser[d].incrementor,Kpressed&&(m=1),traverser[d].active+=m,m=Math.floor(traverser[d].active),m>rows?(traverser[d].wait-=f,0>=traverser[d].wait&&(traverser[d].active=0,traverser[d].wait=Math.random()*WaitTime,traverser[d].incrementor=.85*Math.pow(Math.random(),3)+.15)):(m=rows-1-m,opacity[m*columns+d]=1,chars[m*columns+d]=Math.floor(16*Math.random()));f=.07<f?.03:f;for(d=0;d<rows*columns;d++)array[4*d+0]=chars[d],
array[4*d+1]=opacity[d],array[4*d+2]=d/1200,array[4*d+3]=1,0!=opacity[d]&&(opacity[d]-=.5*f,0>opacity[d]&&(opacity[d]=0));gl.bindTexture(gl.TEXTURE_2D,texture);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,columns,rows,gl.RGBA,gl.FLOAT,array);gl.bindTexture(gl.TEXTURE_2D,null);loadingCascade&&(WaitTime=25);if(releaseCascade){for(d=0;d<columns;d++)traverser[d].active>rows&&(traverser[d].wait=0,traverser[d].active=0,traverser[d].incrementor=.75);loadingCascade=releaseCascade=!1;WaitTime=2.5}if(.06<changerRotator){f=
Math.floor(.008*percentage);for(d=0;d<f;d++)changer[Math.floor(Math.random(percentage))]=Math.floor(Math.random(rows*columns));for(d=0;d<changer.length;d++)chars[changer[d]]=Math.floor(16*Math.random());changerRotator=0}gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(Program.floatingTex,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,glyph_texture);gl.uniform1i(Program.glyphs,1);gl.drawArrays(gl.TRIANGLES,0,rows*columns*6);gl.useProgram(pongProgram);
gl.bindBuffer(gl.ARRAY_BUFFER,pongBuffer);gl.enableVertexAttribArray(pongProgram.a1);gl.vertexAttribPointer(pongProgram.a1,2,gl.FLOAT,!1,0,0);gl.bindFramebuffer(gl.FRAMEBUFFER,pingFramebuffer);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,displayFramebufferTexture);gl.uniform1i(pongProgram.texture,0);gl.uniform1f(pongProgram.hor,15);gl.drawArrays(gl.TRIANGLES,0,6);for(d=0;13>d;d++)f=1-d%2,0==d%2?gl.bindFramebuffer(gl.FRAMEBUFFER,
pongFramebuffer):gl.bindFramebuffer(gl.FRAMEBUFFER,pingFramebuffer),gl.clearColor(0,0,0,0),gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT),gl.activeTexture(gl.TEXTURE0),0==d%2?gl.bindTexture(gl.TEXTURE_2D,pingFramebufferTexture):gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture),gl.uniform1i(pongProgram.texture,0),gl.uniform1f(pongProgram.hor,f),gl.drawArrays(gl.TRIANGLES,0,6);f=audioContext.currentTime-start_time;36>f&&(28<f&&(textureBlurAlpha=(f-28)/4*2),32<f&&(textureBlurAlpha=2*(1-(f-32)/
4)));49.5>f&&37.6<f&&(WaitTime=25);if(auto_cascade_not_released&&49.5<f){for(d=0;d<columns;d++)traverser[d].active>rows&&(traverser[d].wait=0,traverser[d].active=0,traverser[d].incrementor=.75);loadingCascade=releaseCascade=!1;WaitTime=2.5;auto_cascade_not_released=!1}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.useProgram(finalProgram);gl.bindBuffer(gl.ARRAY_BUFFER,finalBuffer);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.bindBuffer(gl.ARRAY_BUFFER,finalBuffer);gl.enableVertexAttribArray(finalProgram.a1);
gl.vertexAttribPointer(finalProgram.a1,2,gl.FLOAT,!1,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,pongFramebufferTexture);gl.uniform1i(finalProgram.blurtexture,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,displayFramebufferTexture);gl.uniform1i(finalProgram.displaytexture,1);gl.activeTexture(gl.TEXTURE2);gl.bindTexture(gl.TEXTURE_2D,skull_texture);gl.uniform1i(finalProgram.skulltexture,2);gl.uniform1f(finalProgram.screenRatio,window.innerWidth/window.innerHeight);
gl.uniform1f(finalProgram.blurAlpha,Math.pow(g,2.59));16.5>f&&(f/=16.5,textureAlpha=f*f*f);gl.uniform1f(finalProgram.textureAlpha,textureAlpha);gl.uniform1f(finalProgram.textureBlurAlpha,textureBlurAlpha);gl.drawArrays(gl.TRIANGLES,0,6)}}
function generateTexture(){for(var g=gl.createTexture(),d=new Float32Array(rows*columns*4),f=0;f<rows*columns;f++)d[4*f+0]=Math.floor(16*Math.random()),d[4*f+1]=0,d[4*f+2]=25,d[4*f+3]=225;gl.bindTexture(gl.TEXTURE_2D,g);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,columns,rows,0,gl.RGBA,gl.FLOAT,d);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,
gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,null);return g}function getBoundingVertices(g,d,f){var m=[],b=mat4.create(),a=mat4.create();mat4.perspective(b,g,d,.1,f);mat4.invert(a,b);g=[];g.push(vec4.fromValues(-1,-1,1,1));g.push(vec4.fromValues(-1,1,1,1));g.push(vec4.fromValues(1,1,1,1));g.push(vec4.fromValues(1,-1,1,1));for(d=0;4>d;d++)f=vec4.create(),f=vec4.transformMat4(f,g[d],a),m.push(vec3.fromValues(f[0]/f[3],f[1]/f[3],f[2]/f[3]));return m}
function generateGlyphTexture(){var g=gl.createTexture(),d=document.getElementById("chars");gl.bindTexture(gl.TEXTURE_2D,g);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,d);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
gl.generateMipmap(gl.TEXTURE_2D);gl.bindTexture(gl.TEXTURE_2D,null);return g}
function skullTexture(){var g=gl.createTexture(),d=document.getElementById("skull");gl.bindTexture(gl.TEXTURE_2D,g);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,d);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,
null);return g}var held=!1,helddowntime=0,loadingCascade=!1,releaseCascade=!1;function keypress(g){helddowntime=audioContext.currentTime-start_time+", ";74==g.keyCode&&(Kpressed=!0);75==g.keyCode&&(DistanceTrigger=!0);76==g.keyCode&&(loadingCascade=resetTraverser=!0);77==g.keyCode&&1>textureBlurAlpha&&(textureBlurAlpha+=.15);78==g.keyCode&&0<textureBlurAlpha&&(textureBlurAlpha-=.15)}var data='{"array": [';
function keyup(g){74==g.keyCode&&(Kpressed=!1);75==g.keyCode&&(DistanceTrigger=!1);76==g.keyCode&&(releaseCascade=!0)}var start_time=0,started=!1,audioContext,dataArray,frequencyArray,averageArray,analyser,sourceBuffer,gainNode;
function setAudio(){audioContext=new (window.AudioContext||window.webkitAudioContext);var g=new XMLHttpRequest;g.open("GET","test.mp3",!0);g.responseType="arraybuffer";g.addEventListener("progress",function(d){d.lengthComputable?(console.log(d.loaded),document.getElementById("loading").innerHTML="Loaded:  "+(d.loaded/d.total*100).toFixed(0)+"%"):console.log(uncomputable)});g.onload=function(){var d=g.response;document.getElementById("loading").style.display="none";audioContext.decodeAudioData(d,function(d){sourceBuffer=
audioContext.createBufferSource();gainNode=audioContext.createGain();sourceBuffer.loop=!0;sourceBuffer.buffer=d;gainNode.gain.value=.001;gainNode.gain.linearRampToValueAtTime(gainNode.gain.value,audioContext.currentTime);gainNode.gain.linearRampToValueAtTime(.5,audioContext.currentTime+6);analyser=audioContext.createAnalyser();analyser.fftSize=1024;d=analyser.frequencyBinCount;dataArray=new Float32Array(d);averageArray=new Float32Array(d);frequencyArray=new Uint8Array(d);analyser.getFloatTimeDomainData(dataArray);
analyser.getFloatTimeDomainData(averageArray);sourceBuffer.connect(gainNode);gainNode.connect(analyser);analyser.connect(audioContext.destination);sourceBuffer.start(audioContext.currentTime,300);start_time=audioContext.currentTime;started=!0})};g.send()}function jsonCheck(){};