window.onload=webGLStart;
var gl,Program,Program_glyph,glyph_texture,glyph_buffer,vertices_glyph=new Float32Array(1E4),textBuffer=[],leaf_Program,LeavesBuffer,LayersBuffer,layer1,layer2,layer3=[],layer4=[],leaf,leaf2,leaf3,leafhalfquadsize=[0,0],step,layer1vertices=new Float32Array(100),layer2vertices=new Float32Array(100),layer3vertices=[],layer4vertices=[],leavesvertices=new Float32Array(4800),layer3_world_window_width=0,layer3_world_window_height=0,projection=mat4.create(),model=mat4.create(),view=mat4.create(),Xtranslation=
0,layer3quadwidth=0,layer4quadwidth=0,world_width_of_last_layer=0,multiPurposeBuffer=[0,0,0],boundingVertices=[];
function webGLStart(){var c=document.getElementById("canvas");c.width=window.innerWidth;c.height=window.innerHeight;document.onmousedown=mdown;document.onmouseup=mup;document.onmousemove=mmove;document.addEventListener("touchstart",phonetouchdown);document.addEventListener("touchend",phonetouchup);document.addEventListener("touchmove",phonetouchmove);var b=["webgl","experimental-webgl","webkit-3d","mozwebgl"],a;for(a in b)try{if((gl=c.getContext(b[a],{stencil:!0,premultipliedAlpha:!1}))&&"function"==
typeof gl.getParameter)break}catch(k){}null==gl&&alert("could not initialize webGL");step=Float32Array.BYTES_PER_ELEMENT;Program=getShader("vertex","fragment",!1);Program.a1=gl.getAttribLocation(Program,"pos");Program.a2=gl.getAttribLocation(Program,"tcoord");Program.projection=gl.getUniformLocation(Program,"projection");Program.model=gl.getUniformLocation(Program,"model");Program.view=gl.getUniformLocation(Program,"view");Program.radius=gl.getUniformLocation(Program,"radius");Program.textel_offset=
gl.getUniformLocation(Program,"textel_offset");Program.tex=gl.getUniformLocation(Program,"tex");Program_glyph=getShader("glyphv","glyphf",!1);Program_glyph.a1=gl.getAttribLocation(Program_glyph,"pos");Program_glyph.a2=gl.getAttribLocation(Program_glyph,"tcoord");Program_glyph.a3=gl.getAttribLocation(Program_glyph,"fx");Program_glyph.tex=gl.getUniformLocation(Program_glyph,"tex");Program_glyph.pixelSize=gl.getUniformLocation(Program_glyph,"pixelSize");Program_glyph.rotator=gl.getUniformLocation(Program_glyph,
"rotator");Program_glyph.anim=gl.getUniformLocation(Program_glyph,"fx");Program_glyph.blurradius=gl.getUniformLocation(Program_glyph,"blurradius");glyph_texture=loadGlyphTexture("AnonymousPro.png");a=generateString("Welcome to Parallax City",0,.577,.067,.035);c=generateString("drag to scroll,",0,.68,.037,.02);b=generateString("don't be afraid :)",0,.673,0,.02);textBuffer=a.concat(a,c,b);for(a=0;a<textBuffer.length;a++)vertices_glyph[a]=textBuffer[a];glyph_buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,
glyph_buffer);gl.bufferData(gl.ARRAY_BUFFER,vertices_glyph,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,null);leaf_Program=getShader("leaf_vertex","leaf_fragment",!1);leaf_Program.a1=gl.getAttribLocation(leaf_Program,"pos");leaf_Program.a2=gl.getAttribLocation(leaf_Program,"tcoord");leaf_Program.a3=gl.getAttribLocation(leaf_Program,"ystart");leaf_Program.a4=gl.getAttribLocation(leaf_Program,"ID");leaf_Program.a5=gl.getAttribLocation(leaf_Program,"texID");leaf_Program.projection=gl.getUniformLocation(leaf_Program,
"projection");leaf_Program.model=gl.getUniformLocation(leaf_Program,"model");leaf_Program.view=gl.getUniformLocation(leaf_Program,"view");leaf_Program.Rotator=gl.getUniformLocation(leaf_Program,"Rotator");leaf_Program.quad_world_size=gl.getUniformLocation(leaf_Program,"quad_world_size");leaf_Program.tex=gl.getUniformLocation(leaf_Program,"tex");leaf_Program.tex2=gl.getUniformLocation(leaf_Program,"tex2");leaf_Program.tex3=gl.getUniformLocation(leaf_Program,"tex3");leaf_Program.radius=gl.getUniformLocation(leaf_Program,
"radius");leaf_Program.textel_offset=gl.getUniformLocation(leaf_Program,"textel_offset");boundingVertices=getBoundingVertices(45,window.innerWidth/window.innerHeight,8.5);c=generateLeaves(2*boundingVertices[2][0]/window.innerWidth,8.5,20);for(a=0;a<leavesvertices.length;a++)leavesvertices[a]=c[a];layer1=loadTexture("layer1");layer2=loadTexture("layer2");layer3.push(loadTexture("layer3_1"));layer3.push(loadTexture("layer3_2"));layer3.push(loadTexture("layer3_3"));layer4.push(loadTexture("layer4_1"));
layer4.push(loadTexture("layer4_2"));leaf=loadTexture("leaves");leaf2=loadTexture("leaves2");leaf3=loadTexture("leaves3");var c=createSceneQuadInDepth(90),b=createSceneQuadInDepth(65),d=createSceneQuadInLayer3Depth(17),f=createSceneQuadInLayer3Depth(17),g=createSceneQuadInLayer3Depth(17),e=createSceneQuadInLayer4Depth(9),h=createSceneQuadInLayer4Depth(9);layer3vertices.push(new Float32Array(100));layer3vertices.push(new Float32Array(100));layer3vertices.push(new Float32Array(100));layer4vertices.push(new Float32Array(100));
layer4vertices.push(new Float32Array(100));for(a=0;a<c.length;a++)layer1vertices[a]=c[a],layer2vertices[a]=b[a],layer3vertices[0][a]=d[a],layer3vertices[1][a]=f[a],layer3vertices[2][a]=g[a],layer4vertices[0][a]=e[a],layer4vertices[1][a]=h[a];LeavesBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,LeavesBuffer);gl.bufferData(gl.ARRAY_BUFFER,leavesvertices,gl.STATIC_DRAW);LayersBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer);gl.bufferData(gl.ARRAY_BUFFER,layer1vertices,gl.STATIC_DRAW);
gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE);requestAnimationFrame(draw)}var then=0;
function draw(c){gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE);requestAnimationFrame(draw);then=c*=.001;0<lastDelta&&(lastDelta=down?lastDelta-.25*lastDelta:lastDelta-.5*lastDelta);gl.disable(gl.DEPTH_TEST);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT);mat4.identity(model);mat4.identity(view);mat4.perspective(projection,45,window.innerWidth/window.innerHeight,.1,200);gl.useProgram(Program);gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer);gl.enableVertexAttribArray(Program.a1);
gl.enableVertexAttribArray(Program.a2);gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,5*step,0);gl.vertexAttribPointer(Program.a2,2,gl.FLOAT,!1,5*step,3*step);multiPurposeBuffer[0]=.25*Math.sin(c)+Xtranslation;multiPurposeBuffer[1]=3.5;multiPurposeBuffer[2]=0;mat4.translate(model,model,multiPurposeBuffer);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,model);gl.uniformMatrix4fv(Program.view,!1,view);gl.uniform1f(Program.radius,lastDelta/10);gl.uniform1f(Program.textel_offset,
.001);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,layer1);gl.uniform1i(Program.tex,0);gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer);gl.bufferData(gl.ARRAY_BUFFER,layer1vertices,gl.STATIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,6);multiPurposeBuffer[1]=2;mat4.translate(model,model,multiPurposeBuffer);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,model);gl.uniformMatrix4fv(Program.view,!1,view);gl.uniform1f(Program.radius,lastDelta/3.7);gl.uniform1f(Program.textel_offset,
1/1500);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,layer2);gl.uniform1i(Program.tex,0);gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer);gl.bufferData(gl.ARRAY_BUFFER,layer2vertices,gl.STATIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,6);for(var b=0,a=0;b<layer3vertices.length;b++)0==b&&(a=.8*-layer3fakeworld_width+.001),1==b&&(a=0),2==b&&(a=.8*+layer3fakeworld_width),mat4.identity(model),multiPurposeBuffer[0]=a,multiPurposeBuffer[1]=0,multiPurposeBuffer[2]=0,mat4.translate(model,model,multiPurposeBuffer),
multiPurposeBuffer[0]=.25*Math.sin(c)+Xtranslation,multiPurposeBuffer[1]=1.6,mat4.translate(model,model,multiPurposeBuffer),multiPurposeBuffer[0]=.8,multiPurposeBuffer[1]=.8,multiPurposeBuffer[2]=1,mat4.scale(model,model,multiPurposeBuffer),gl.uniformMatrix4fv(Program.projection,!1,projection),gl.uniformMatrix4fv(Program.model,!1,model),gl.uniformMatrix4fv(Program.view,!1,view),gl.uniform1f(Program.radius,1*lastDelta),gl.uniform1f(Program.textel_offset,1/1500),gl.activeTexture(gl.TEXTURE0),gl.bindTexture(gl.TEXTURE_2D,
layer3[b]),gl.uniform1i(Program.tex,0),gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer),gl.bufferData(gl.ARRAY_BUFFER,layer3vertices[b],gl.STATIC_DRAW),gl.drawArrays(gl.TRIANGLES,0,6);for(a=b=0;b<layer4vertices.length;b++)mat4.identity(model),0==b&&(a=-(layer4quadwidth/2)),1==b&&(a=layer4quadwidth/2),multiPurposeBuffer[0]=.25*Math.sin(c)+Xtranslation+a,multiPurposeBuffer[1]=-.3,multiPurposeBuffer[2]=0,mat4.translate(model,model,multiPurposeBuffer),multiPurposeBuffer[0]=1,multiPurposeBuffer[1]=1,multiPurposeBuffer[2]=
1,mat4.scale(model,model,multiPurposeBuffer),gl.uniformMatrix4fv(Program.projection,!1,projection),gl.uniformMatrix4fv(Program.model,!1,model),gl.uniformMatrix4fv(Program.view,!1,view),gl.uniform1f(Program.radius,.8*lastDelta),gl.uniform1f(Program.textel_offset,1/1500),gl.activeTexture(gl.TEXTURE0),gl.bindTexture(gl.TEXTURE_2D,layer4[b]),gl.uniform1i(Program.tex,0),gl.bindBuffer(gl.ARRAY_BUFFER,LayersBuffer),gl.bufferData(gl.ARRAY_BUFFER,layer4vertices[b],gl.STATIC_DRAW),gl.drawArrays(gl.TRIANGLES,
0,6);gl.useProgram(leaf_Program);gl.bindBuffer(gl.ARRAY_BUFFER,LeavesBuffer);gl.enableVertexAttribArray(leaf_Program.a1);gl.enableVertexAttribArray(leaf_Program.a2);gl.enableVertexAttribArray(leaf_Program.a3);gl.enableVertexAttribArray(leaf_Program.a4);gl.enableVertexAttribArray(leaf_Program.a5);gl.vertexAttribPointer(leaf_Program.a1,3,gl.FLOAT,!1,8*step,0);gl.vertexAttribPointer(leaf_Program.a2,2,gl.FLOAT,!1,8*step,3*step);gl.vertexAttribPointer(leaf_Program.a3,1,gl.FLOAT,!1,8*step,5*step);gl.vertexAttribPointer(leaf_Program.a4,
1,gl.FLOAT,!1,8*step,6*step);gl.vertexAttribPointer(leaf_Program.a5,1,gl.FLOAT,!1,8*step,7*step);mat4.identity(view);mat4.identity(model);multiPurposeBuffer[0]=.25*Math.sin(c)+Xtranslation;multiPurposeBuffer[1]=-.3;multiPurposeBuffer[2]=0;mat4.translate(model,model,multiPurposeBuffer);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,leaf);gl.uniform1i(leaf_Program.tex,0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,leaf2);gl.uniform1i(leaf_Program.tex2,1);gl.activeTexture(gl.TEXTURE2);
gl.bindTexture(gl.TEXTURE_2D,leaf3);gl.uniform1i(leaf_Program.tex3,2);gl.uniformMatrix4fv(leaf_Program.projection,!1,projection);gl.uniformMatrix4fv(leaf_Program.model,!1,model);gl.uniformMatrix4fv(leaf_Program.view,!1,view);gl.uniform1f(leaf_Program.radius,6.9*lastDelta);gl.uniform1f(leaf_Program.textel_offset,1/199);gl.uniform1f(leaf_Program.Rotator,c%2500);gl.uniform2fv(leaf_Program.quad_world_size,leafhalfquadsize);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,
gl.ONE);gl.enable(gl.DEPTH_TEST);gl.drawArrays(gl.TRIANGLES,0,600);gl.useProgram(Program_glyph);gl.bindBuffer(gl.ARRAY_BUFFER,glyph_buffer);gl.enableVertexAttribArray(Program_glyph.a1);gl.enableVertexAttribArray(Program_glyph.a2);gl.enableVertexAttribArray(Program_glyph.a3);gl.vertexAttribPointer(Program_glyph.a1,2,gl.FLOAT,!1,6*step,0);gl.vertexAttribPointer(Program_glyph.a2,3,gl.FLOAT,!1,6*step,2*step);gl.vertexAttribPointer(Program_glyph.a3,1,gl.FLOAT,!1,6*step,5*step);gl.activeTexture(gl.TEXTURE0);
gl.bindTexture(gl.TEXTURE_2D,glyph_texture);gl.uniform1i(Program_glyph.tex,0);gl.uniform1f(Program_glyph.pixelSize,1/4096);gl.uniform1f(Program_glyph.rotator,3*c);gl.uniform1f(Program_glyph.blurradius,Xtranslation);gl.disable(gl.DEPTH_TEST);gl.drawArrays(gl.TRIANGLES,0,textBuffer.length/6);gl.enable(gl.DEPTH_TEST)}
function loadTexture(c){var b=gl.createTexture();c=document.getElementById(c);gl.bindTexture(gl.TEXTURE_2D,b);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,
null);return b}function getBoundingVertices(c,b,a){var d=[],f=mat4.create(),g=mat4.create();mat4.perspective(f,c,b,.1,a);mat4.invert(g,f);c=[];c.push(vec4.fromValues(-1,-1,1,1));c.push(vec4.fromValues(-1,1,1,1));c.push(vec4.fromValues(1,1,1,1));c.push(vec4.fromValues(1,-1,1,1));for(b=0;4>b;b++)a=vec4.create(),a=vec4.transformMat4(a,c[b],g),d.push(vec3.fromValues(a[0]/a[3],a[1]/a[3],a[2]/a[3]));world_width_of_last_layer=2*d[2][0];return d}
function createSceneQuadInDepth(c,b,a,d){var f=4096/721,g=0,e=0;b&&(f=b);a&&(g=a);d&&(e=d);boundingVertices=getBoundingVertices(45,window.innerWidth/window.innerHeight,c);b=2*boundingVertices[2][1];f=b*f/2;b/=2;return[-f+g,-b+e,-c,0,0,-f+g,+b+e,-c,0,1,+f+g,-b+e,-c,1,0,+f+g,-b+e,-c,1,0,-f+g,+b+e,-c,0,1,+f+g,+b+e,-c,1,1]}var layer3fakeworld_width=0;
function createSceneQuadInLayer3Depth(c){var b=2048/721;boundingVertices=getBoundingVertices(45,window.innerWidth/window.innerHeight,c);var a=2*boundingVertices[2][1];layer3fakeworld_width=b*=a;b=2*b/2;a/=2;return[-b,-a,-c,-.5,0,-b,+a,-c,-.5,1,+b,-a,-c,1.5,0,+b,-a,-c,1.5,0,-b,+a,-c,-.5,1,+b,+a,-c,1.5,1]}
function createSceneQuadInLayer4Depth(c){boundingVertices=getBoundingVertices(45,window.innerWidth/window.innerHeight,c);var b=2.5*boundingVertices[2][1],a=4*b;layer4quadwidth=a;a=2*a/2;b/=2;return[-a,-b,-c,-.5,0,-a,+b,-c,-.5,1,+a,-b,-c,1.5,0,+a,-b,-c,1.5,0,-a,+b,-c,-.5,1,+a,+b,-c,1.5,1]}var down=!1,lastxPos=0;function mdown(c){down=!0;lastxPos=c.clientX}function mup(c){down=!1}var lastDelta=0;
function mmove(c){if(down){var b=c.clientX-lastxPos;lastDelta=Math.abs(b)>lastDelta?lastDelta+.2*Math.abs(b):lastDelta-.1*Math.abs(b);Xtranslation+=b/(window.innerWidth/world_width_of_last_layer);lastxPos=c.clientX}}
function generateLeaves(c,b,a){var d=[];b=-b;leafhalfquadsize[0]=2*a*c;leafhalfquadsize[1]=a*c/1.77;for(var f=0;100>f;f++){var g=15*Math.random()-7.5,e=10*Math.random()+5,h=.084*f,k=Math.floor(3*Math.pow(Math.random(),.85));d.push(2*-a*c+g);d.push(-(a*c)/1.77+e);d.push(b+h);d.push(-.5);d.push(0);d.push(e);d.push(f);d.push(k);d.push(2*-a*c+g);d.push(+(a*c)/1.77+e);d.push(b+h);d.push(-.5);d.push(1);d.push(e);d.push(f);d.push(k);d.push(2*+a*c+g);d.push(-(a*c)/1.77+e);d.push(b+h);d.push(1.5);d.push(0);
d.push(e);d.push(f);d.push(k);d.push(2*+a*c+g);d.push(-(a*c)/1.77+e);d.push(b+h);d.push(1.5);d.push(0);d.push(e);d.push(f);d.push(k);d.push(2*-a*c+g);d.push(+(a*c)/1.77+e);d.push(b+h);d.push(-.5);d.push(1);d.push(e);d.push(f);d.push(k);d.push(2*+a*c+g);d.push(+(a*c)/1.77+e);d.push(b+h);d.push(1.5);d.push(1);d.push(e);d.push(f);d.push(k)}return d}
function loadGlyphTexture(c){var b=gl.createTexture(),a=new Image;a.onload=function(){gl.bindTexture(gl.TEXTURE_2D,glyph_texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,a);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,
null)};a.crossOrigin="";a.src=c;return b}function generateString(c,b,a,d,f){var g=[],e,h=window.innerWidth/window.innerHeight;a=2*a-1-.005*b;b=2*d-1-b*f*h*1.73;for(d=0;d<c.length;d++){e=a+(f-f/5)*d;e=[a+e,b,0,0,c.charCodeAt(d)-32,e,a+e,b+f*h*1.73,0,1,c.charCodeAt(d)-32,e,a+e+f,b,1,0,c.charCodeAt(d)-32,e,a+e+f,b,1,0,c.charCodeAt(d)-32,e,a+e,b+f*h*1.73,0,1,c.charCodeAt(d)-32,e,a+e+f,b+f*h*1.73,1,1,c.charCodeAt(d)-32,e];for(var k=0;k<e.length;k++)g.push(e[k])}return g}
function phonetouchdown(c){down=!0;lastxPos=c.touches[0].clientX}function phonetouchup(c){down=!1}function phonetouchmove(c){if(down){var b=c.touches[0].clientX-lastxPos;lastDelta=Math.abs(b)>lastDelta?lastDelta+.2*Math.abs(b):lastDelta-.1*Math.abs(b);Xtranslation+=b/(window.innerWidth/world_width_of_last_layer);lastxPos=c.touches[0].clientX}};