window.addEventListener("load",AudioInit);var gl,analyser,dataArray,bufferLength,processor,processor2,biquadFilter,gainNode,audioContext,convolver,sourceBuffer,fullBuffer,lf,rf,projection=mat4.create(),model=mat4.create(),view=mat4.create(),mainQuadVertices=new Float32Array(6291456),pointVertices=new Float32Array(8192),multiPurposeBuffer=[0,0,0],step=Float32Array.BYTES_PER_ELEMENT,Program_main,Buffer_main,Program_points,Buffer_points;
function AudioInit(){var a=document.getElementById("canvas");a.width=window.innerWidth;a.height=window.innerHeight;a.addEventListener("mousedown",moused);a.addEventListener("mouseup",mouseu);a.addEventListener("mousemove",mousedrag);window.addEventListener("mousewheel",MouseWheelHandler);window.addEventListener("DOMMouseScroll",MouseWheelHandler);gl=a.getContext("experimental-webgl");var e=["webgl","experimental-webgl","webkit-3d","mozwebgl"],b;for(b in e)try{if((gl=a.getContext(e[b],{stencil:!0,
premultipliedAlpha:!1}))&&"function"==typeof gl.getParameter)break}catch(d){}null==gl&&alert("could not initialize webGL");Program_main=getShader("mainv","mainf",!1);Program_main.a1=gl.getAttribLocation(Program_main,"pos");Program_main.a2=gl.getAttribLocation(Program_main,"ID");Program_main.projection=gl.getUniformLocation(Program_main,"projection");Program_main.model=gl.getUniformLocation(Program_main,"model");Program_main.view=gl.getUniformLocation(Program_main,"view");Program_main.values=gl.getUniformLocation(Program_main,
"values");Program_points=getShader("pointv","pointf",!1);Program_points.a1=gl.getAttribLocation(Program_points,"id");Program_points.projection=gl.getUniformLocation(Program_points,"projection");Program_points.model=gl.getUniformLocation(Program_points,"model");Program_points.view=gl.getUniformLocation(Program_points,"view");Program_points.samples=gl.getUniformLocation(Program_points,"samples");Program_points.pheight=gl.getUniformLocation(Program_points,"pheight");audioContext=new (window.AudioContext||
window.webkitAudioContext);audioContext.createOscillator();var c=new XMLHttpRequest;c.open("GET","test.mp3",!0);c.responseType="arraybuffer";c.addEventListener("progress",function(a){a.lengthComputable?(console.log(a.loaded),document.getElementById("loading").getElementsByTagName("div")[0].innerHTML="Loaded:  "+(a.loaded/a.total*100).toFixed(0)+"%"):console.log(uncomputable)});c.onload=function(){var a=c.response;document.getElementById("loading").getElementsByTagName("div")[0].innerHTML="Creating buffers...";
audioContext.decodeAudioData(a,function(a){sourceBuffer=audioContext.createBufferSource();biquadFilter=audioContext.createBiquadFilter();gainNode=audioContext.createGain();sourceBuffer.loop=!0;fullBuffer=sourceBuffer.buffer=a;gainNode.gain.value=.001;gainNode.gain.linearRampToValueAtTime(gainNode.gain.value,audioContext.currentTime);gainNode.gain.linearRampToValueAtTime(1,audioContext.currentTime+6);biquadFilter.type="lowpass";biquadFilter.frequency.value=4400;processor=audioContext.createScriptProcessor(2048);
processor.onaudioprocess=onProcess;processor2=audioContext.createScriptProcessor(2048);processor2.onaudioprocess=math;analyser=audioContext.createAnalyser();analyser.fftSize=1024;bufferLength=analyser.frequencyBinCount;dataArray=new Float32Array(bufferLength);analyser.getFloatTimeDomainData(dataArray);sourceBuffer.connect(processor);processor.connect(processor2);processor2.connect(biquadFilter);biquadFilter.connect(gainNode);gainNode.connect(analyser);analyser.connect(audioContext.destination);sourceBuffer.start(audioContext.currentTime);
lf=fullBuffer.getChannelData(0);rf=fullBuffer.getChannelData(1);init();draw()})};c.send()}var f=0,then=0,buffery=new Float32Array(512),count=0,deltatime=0,threshold=450,pheight=-2,NOISE_FACTOR=0,zoom=0,deltazoom=0,deltarotvec=[0,0];
function draw(a){requestAnimationFrame(draw);a*=.001;deltatime=a-then;then=a;deltatime&&(count+=deltatime);zoom!=deltazoom&&(deltazoom+=.2*(zoom-deltazoom));if(deltarotvec[0]!=rotVec[0]||deltarotvec[1]!=rotVec[1])a=rotVec[1]-deltarotvec[1],deltarotvec[0]+=.4*(rotVec[0]-deltarotvec[0]),deltarotvec[1]+=.4*a;count>Math.pow(.001*threshold,4)&&(analyser.getFloatTimeDomainData(dataArray),count=0);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);mat4.perspective(projection,
45,window.innerWidth/window.innerHeight,1,2E3);mat4.identity(model);mat4.identity(view);multiPurposeBuffer[0]=0;multiPurposeBuffer[1]=-25;multiPurposeBuffer[2]=-145+deltazoom;mat4.translate(model,model,multiPurposeBuffer);multiPurposeBuffer[0]=0;multiPurposeBuffer[1]=0;multiPurposeBuffer[2]=-180;mat4.translate(model,model,multiPurposeBuffer);multiPurposeBuffer[0]=1;multiPurposeBuffer[1]=0;multiPurposeBuffer[2]=0;mat4.rotate(model,model,deltarotvec[1],multiPurposeBuffer);multiPurposeBuffer[0]=0;multiPurposeBuffer[1]=
1;multiPurposeBuffer[2]=0;mat4.rotate(model,model,deltarotvec[0],multiPurposeBuffer);multiPurposeBuffer[0]=0;multiPurposeBuffer[1]=0;multiPurposeBuffer[2]=128;mat4.translate(model,model,multiPurposeBuffer);gl.useProgram(Program_main);gl.bindBuffer(gl.ARRAY_BUFFER,Buffer_main);gl.enableVertexAttribArray(Program_main.a1);gl.enableVertexAttribArray(Program_main.a2);gl.vertexAttribPointer(Program_main.a1,3,gl.FLOAT,!1,4*step,0);gl.vertexAttribPointer(Program_main.a2,1,gl.FLOAT,!1,4*step,3*step);gl.uniformMatrix4fv(Program_main.projection,
!1,projection);gl.uniformMatrix4fv(Program_main.model,!1,model);gl.uniformMatrix4fv(Program_main.view,!1,view);gl.uniform4fv(Program_main.values,dataArray);gl.drawArrays(gl.TRIANGLES,0,mainQuadVertices.length/4);gl.useProgram(Program_points);gl.bindBuffer(gl.ARRAY_BUFFER,Buffer_points);gl.enableVertexAttribArray(Program_points.a1);gl.vertexAttribPointer(Program_points.a1,2,gl.FLOAT,!1,0,0);gl.uniformMatrix4fv(Program_points.projection,!1,projection);gl.uniformMatrix4fv(Program_points.model,!1,model);
gl.uniformMatrix4fv(Program_points.view,!1,view);gl.uniform4fv(Program_points.samples,dataArray);gl.uniform1f(Program_points.pheight,pheight);gl.drawArrays(gl.POINTS,0,pointVertices.length/2)}
function init(){document.getElementById("loading").style.display="none";for(var a=[],e,b=0;b<bufferLength;b++)for(var c=e=0;c<bufferLength;c++){var d=-(0+b),h=e,k=0+c-bufferLength/2,g=1+b,l=e,m=1+c-bufferLength/2,n=-(0+b),p=e,q=1+c-bufferLength/2,r=-(0+b),t=e,u=0+c-bufferLength/2,v=1+b,w=e,x=1+c-bufferLength/2,y=1+b,z=e;a.push(0+c-bufferLength/2);a.push(0);a.push(d);a.push(h);a.push(k);a.push(0);a.push(g);a.push(l);a.push(m);a.push(0);a.push(n);a.push(p);a.push(q);a.push(0);a.push(r);a.push(t);a.push(u);
a.push(0);a.push(v);a.push(w);a.push(x);a.push(0);a.push(y);a.push(z);e++}for(b=0;b<a.length;b++)mainQuadVertices[b]=a[b];Buffer_main=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,Buffer_main);gl.bufferData(gl.ARRAY_BUFFER,mainQuadVertices,gl.STATIC_DRAW);a=[];for(b=0;64>b;b++)for(c=0;64>c;c++)a.push(c),a.push(b);for(b=0;b<a.length;b++)pointVertices[b]=a[b];Buffer_points=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,Buffer_points);gl.bufferData(gl.ARRAY_BUFFER,pointVertices,gl.STATIC_DRAW)}
function freq(a){biquadFilter.frequency.value=a}function gainv(a){gainNode.gain.linearRampToValueAtTime(a,audioContext.currentTime)}function reverbt(a){0==a?(sourceBuffer.connect(biquadFilter),convolver.disconnect(),biquadFilter.connect(gainNode)):(biquadFilter.connect(convolver),convolver.connect(gainNode));convolver.buffer=impulseResponse(a,2,3)}function noise(a){NOISE_FACTOR=a}function exponentialc(a){reverber=Math.floor(a)}function analratio(a){threshold=parseFloat(a)}
function pointheight(a){pheight=parseFloat(a)}function getBoundingVertices(a,e,b){var c=[],d=mat4.create(),h=mat4.create();mat4.perspective(d,a,e,.1,b);mat4.invert(h,d);a=[];a.push(vec4.fromValues(-1,-1,1,1));a.push(vec4.fromValues(-1,1,1,1));a.push(vec4.fromValues(1,1,1,1));a.push(vec4.fromValues(1,-1,1,1));for(e=0;4>e;e++)b=vec4.create(),b=vec4.transformMat4(b,a[e],h),c.push(vec3.fromValues(b[0]/b[3],b[1]/b[3],b[2]/b[3]));return c}var dragging=0,startpos=[0,0];
function moused(a){a.preventDefault();startpos[0]=a.clientX;startpos[1]=a.clientY;dragging=1}function mouseu(a){a.preventDefault();startpos[0]=0;dragging=startpos[1]=0}var rotVec=[0,.18];function mousedrag(a){a.preventDefault();if(dragging){var e=startpos[1]-a.clientY;rotVec[0]+=-((startpos[0]-a.clientX)/10)*deltatime;rotVec[1]+=-(e/10)*deltatime;startpos[0]=a.clientX;startpos[1]=a.clientY}}var impulseL,impulseR,impulse;
function impulseResponse(a,e,b){var c=audioContext.sampleRate;a*=c;impulse||(alert(),impulse=audioContext.createBuffer(2,a,c),impulseL=impulse.getChannelData(0),impulseR=impulse.getChannelData(1));e||(e=2);for(c=0;c<a;c++){var d=b?a-c:c;impulseL[c]=(2*Math.random()-1)*Math.pow(1-d/a,e);impulseR[c]=(2*Math.random()-1)*Math.pow(1-d/a,e)}return impulse}
function onProcess(a){var e=a.inputBuffer.getChannelData(0),b=a.inputBuffer.getChannelData(1),c=a.outputBuffer.getChannelData(0);a=a.outputBuffer.getChannelData(1);for(var d=0;d<c.length;d++)c[d]=e[d]+(Math.random()-.5)*NOISE_FACTOR,a[d]=b[d]+(Math.random()-.5)*NOISE_FACTOR}var gaussianblur=[.1,.3,.5,.3,.1],power=2,whentostart=0,reverber=0;
function math(a){0==whentostart&&(whentostart=audioContext.currentTime);var e=a.inputBuffer.getChannelData(0),b=a.inputBuffer.getChannelData(1),c=a.outputBuffer.getChannelData(0);a=a.outputBuffer.getChannelData(1);275<audioContext.currentTime-whentostart&&(reverber=0);if(0==reverber)for(var d=0;d<c.length;d++)c[d]=e[d],a[d]=b[d];else{var h=48E3*(audioContext.currentTime-whentostart-reverber);0>h&&(h=0);var k=0,g=0;switch(reverber){case 0:g=1;break;case 1:k=2;g=1.5;break;case 2:k=3;g=2;break;case 3:k=
3;g=2;break;case 4:k=3;g=2;break;case 5:k=3,g=2}for(d=0;d<c.length;d++){for(var l=0;l<reverber;l++)c[d]+=lf[Math.floor(h)+d+Math.floor(48E3*l)]/k,a[d]+=rf[Math.floor(h)+d+Math.floor(48E3*l)]/k;c[d]+=e[d]/g;a[d]+=b[d]/g}}}
function mic(a){a?navigator.mediaDevices.getUserMedia?(a=navigator.mediaDevices.getUserMedia({audio:!0}),a.then(function(a){window.microphone=audioContext.createMediaStreamSource(a);window.microphone&&(sourceBuffer.disconnect(),processor.disconnect(),processor2.disconnect(),biquadFilter.disconnect(),gainNode.disconnect(),analyser.disconnect(),microphone.connect(biquadFilter),biquadFilter.connect(gainNode),gainNode.connect(analyser),analyser.connect(audioContext.destination))}),a["catch"](function(a){console.log(a.name)})):
navigator.webkitGetUserMedia?navigator.webkitGetUserMedia({audio:!0},function(a){window.microphone=audioContext.createMediaStreamSource(a);window.microphone&&(sourceBuffer.disconnect(),processor.disconnect(),processor2.disconnect(),biquadFilter.disconnect(),gainNode.disconnect(),analyser.disconnect(),microphone.connect(biquadFilter),biquadFilter.connect(gainNode),gainNode.connect(analyser),analyser.connect(audioContext.destination))},function(){}):navigator.msGetUserMedia&&navigator.msGetUserMedia({audio:!0},
function(a){window.microphone=audioContext.createMediaStreamSource(a);window.microphone&&(sourceBuffer.disconnect(),processor.disconnect(),processor2.disconnect(),biquadFilter.disconnect(),gainNode.disconnect(),analyser.disconnect(),microphone.connect(biquadFilter),biquadFilter.connect(gainNode),gainNode.connect(analyser),analyser.connect(audioContext.destination))},function(){}):window.microphone&&(microphone.disconnect(),biquadFilter.disconnect(),gainNode.disconnect(),analyser.disconnect(),whentostart=
0,sourceBuffer=audioContext.createBufferSource(),biquadFilter=audioContext.createBiquadFilter(),gainNode=audioContext.createGain(),sourceBuffer.loop=!0,sourceBuffer.buffer=fullBuffer,gainNode.gain.value=.001,gainNode.gain.linearRampToValueAtTime(gainNode.gain.value,audioContext.currentTime),gainNode.gain.linearRampToValueAtTime(1,audioContext.currentTime+6),biquadFilter.type="lowpass",biquadFilter.frequency.value=4400,sourceBuffer.connect(processor),processor.connect(processor2),processor2.connect(biquadFilter),
biquadFilter.connect(gainNode),gainNode.connect(analyser),analyser.connect(audioContext.destination),sourceBuffer.start(audioContext.currentTime),lf=fullBuffer.getChannelData(0),rf=fullBuffer.getChannelData(1))}function MouseWheelHandler(a){zoom=0<(a.wheelDelta?a.wheelDelta:-a.detail)?zoom+20:zoom+-20;140<zoom&&(zoom=140);-220>zoom&&(zoom=-220)}var datatext;
function dataTexture(){var a=new Float32Array(512);gl.bindTexture(gl.TEXTURE_2D,datatext);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,a);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.bindTexture(gl.TEXTURE_2D,null)};