!function(f,e){if("object"==typeof exports&&"object"==typeof module)module.exports=e();else if("function"==typeof define&&define.amd)define(e);else{var g=e(),l;for(l in g)("object"==typeof exports?exports:f)[l]=g[l]}}(this,function(){return function(f){function e(l){if(g[l])return g[l].exports;var b=g[l]={exports:{},id:l,loaded:!1};return f[l].call(b.exports,b,b.exports,e),b.loaded=!0,b.exports}var g={};return e.m=f,e.c=g,e.p="",e(0)}([function(f,e,g){e.glMatrix=g(1);e.mat2=g(2);e.mat2d=g(3);e.mat3=
g(4);e.mat4=g(5);e.quat=g(6);e.vec2=g(9);e.vec3=g(7);e.vec4=g(8)},function(f,e){var g={EPSILON:1E-6};g.ARRAY_TYPE="undefined"!=typeof Float32Array?Float32Array:Array;g.RANDOM=Math.random;g.ENABLE_SIMD=!1;g.SIMD_AVAILABLE=g.ARRAY_TYPE===Float32Array&&"SIMD"in this;g.USE_SIMD=g.ENABLE_SIMD&&g.SIMD_AVAILABLE;g.setMatrixArrayType=function(b){g.ARRAY_TYPE=b};var l=Math.PI/180;g.toRadian=function(b){return b*l};f.exports=g},function(f,e,g){var l=g(1);e={create:function(){var b=new l.ARRAY_TYPE(4);return b[0]=
1,b[1]=0,b[2]=0,b[3]=1,b},clone:function(b){var a=new l.ARRAY_TYPE(4);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b},transpose:function(b,a){if(b===a){var c=a[1];b[1]=a[2];b[2]=c}else b[0]=a[0],b[1]=a[2],b[2]=a[1],b[3]=a[3];return b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],k=a[3],m=c*k-n*d;return m?(m=1/m,b[0]=k*m,b[1]=-d*m,b[2]=-n*m,b[3]=c*m,b):null},adjoint:function(b,
a){var c=a[0];return b[0]=a[3],b[1]=-a[1],b[2]=-a[2],b[3]=c,b},determinant:function(b){return b[0]*b[3]-b[2]*b[1]},multiply:function(b,a,c){var d=a[0],n=a[1],k=a[2];a=a[3];var m=c[0],h=c[1],t=c[2];c=c[3];return b[0]=d*m+k*h,b[1]=n*m+a*h,b[2]=d*t+k*c,b[3]=n*t+a*c,b}};e.mul=e.multiply;e.rotate=function(b,a,c){var d=a[0],n=a[1],k=a[2];a=a[3];var m=Math.sin(c);c=Math.cos(c);return b[0]=d*c+k*m,b[1]=n*c+a*m,b[2]=d*-m+k*c,b[3]=n*-m+a*c,b};e.scale=function(b,a,c){var d=a[1],n=a[2],k=a[3],m=c[0];c=c[1];return b[0]=
a[0]*m,b[1]=d*m,b[2]=n*c,b[3]=k*c,b};e.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);return b[0]=d,b[1]=c,b[2]=-c,b[3]=d,b};e.fromScaling=function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=a[1],b};e.str=function(b){return"mat2("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+")"};e.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2))};e.LDU=function(b,a,c,d){return b[2]=d[2]/d[0],c[0]=d[0],c[1]=d[1],c[3]=d[3]-b[2]*c[1],[b,a,c]};f.exports=e},function(f,
e,g){var l=g(1);e={create:function(){var b=new l.ARRAY_TYPE(6);return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=0,b[5]=0,b},clone:function(b){var a=new l.ARRAY_TYPE(6);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[4]=b[4],a[5]=b[5],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=0,b[5]=0,b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],k=a[3],m=a[4],h=a[5],t=c*k-d*n;return t?(t=1/t,b[0]=k*t,b[1]=-d*
t,b[2]=-n*t,b[3]=c*t,b[4]=(n*h-k*m)*t,b[5]=(d*m-c*h)*t,b):null},determinant:function(b){return b[0]*b[3]-b[1]*b[2]},multiply:function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4];a=a[5];var t=c[0],e=c[1],u=c[2],p=c[3],f=c[4];c=c[5];return b[0]=d*t+k*e,b[1]=n*t+m*e,b[2]=d*u+k*p,b[3]=n*u+m*p,b[4]=d*f+k*c+h,b[5]=n*f+m*c+a,b}};e.mul=e.multiply;e.rotate=function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4];a=a[5];var t=Math.sin(c);c=Math.cos(c);return b[0]=d*c+k*t,b[1]=n*c+m*t,b[2]=d*-t+k*c,b[3]=n*-t+
m*c,b[4]=h,b[5]=a,b};e.scale=function(b,a,c){var d=a[1],n=a[2],k=a[3],m=a[4],h=a[5],t=c[0];c=c[1];return b[0]=a[0]*t,b[1]=d*t,b[2]=n*c,b[3]=k*c,b[4]=m,b[5]=h,b};e.translate=function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4];a=a[5];var t=c[0];c=c[1];return b[0]=d,b[1]=n,b[2]=k,b[3]=m,b[4]=d*t+k*c+h,b[5]=n*t+m*c+a,b};e.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);return b[0]=d,b[1]=c,b[2]=-c,b[3]=d,b[4]=0,b[5]=0,b};e.fromScaling=function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=a[1],
b[4]=0,b[5]=0,b};e.fromTranslation=function(b,a){return b[0]=1,b[1]=0,b[2]=0,b[3]=1,b[4]=a[0],b[5]=a[1],b};e.str=function(b){return"mat2d("+b[0]+", "+b[1]+", "+b[2]+", "+b[3]+", "+b[4]+", "+b[5]+")"};e.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+1)};f.exports=e},function(f,e,g){var l=g(1);e={create:function(){var b=new l.ARRAY_TYPE(9);return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b},
fromMat4:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[4],b[4]=a[5],b[5]=a[6],b[6]=a[8],b[7]=a[9],b[8]=a[10],b},clone:function(b){var a=new l.ARRAY_TYPE(9);return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[4]=b[4],a[5]=b[5],a[6]=b[6],a[7]=b[7],a[8]=b[8],a},copy:function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b},identity:function(b){return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b},transpose:function(b,
a){if(b===a){var c=a[1],d=a[2],n=a[5];b[1]=a[3];b[2]=a[6];b[3]=c;b[5]=a[7];b[6]=d;b[7]=n}else b[0]=a[0],b[1]=a[3],b[2]=a[6],b[3]=a[1],b[4]=a[4],b[5]=a[7],b[6]=a[2],b[7]=a[5],b[8]=a[8];return b},invert:function(b,a){var c=a[0],d=a[1],n=a[2],k=a[3],m=a[4],h=a[5],t=a[6],e=a[7],u=a[8],p=u*m-h*e,f=-u*k+h*t,g=e*k-m*t,l=c*p+d*f+n*g;return l?(l=1/l,b[0]=p*l,b[1]=(-u*d+n*e)*l,b[2]=(h*d-n*m)*l,b[3]=f*l,b[4]=(u*c-n*t)*l,b[5]=(-h*c+n*k)*l,b[6]=g*l,b[7]=(-e*c+d*t)*l,b[8]=(m*c-d*k)*l,b):null},adjoint:function(b,
a){var c=a[0],d=a[1],n=a[2],k=a[3],m=a[4],h=a[5],t=a[6],e=a[7],u=a[8];return b[0]=m*u-h*e,b[1]=n*e-d*u,b[2]=d*h-n*m,b[3]=h*t-k*u,b[4]=c*u-n*t,b[5]=n*k-c*h,b[6]=k*e-m*t,b[7]=d*t-c*e,b[8]=c*m-d*k,b},determinant:function(b){var a=b[3],c=b[4],d=b[5],n=b[6],k=b[7],m=b[8];return b[0]*(m*c-d*k)+b[1]*(-m*a+d*n)+b[2]*(k*a-c*n)},multiply:function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4],t=a[5],e=a[6],u=a[7];a=a[8];var p=c[0],f=c[1],g=c[2],l=c[3],r=c[4],v=c[5],x=c[6],y=c[7];c=c[8];return b[0]=p*d+f*m+g*
e,b[1]=p*n+f*h+g*u,b[2]=p*k+f*t+g*a,b[3]=l*d+r*m+v*e,b[4]=l*n+r*h+v*u,b[5]=l*k+r*t+v*a,b[6]=x*d+y*m+c*e,b[7]=x*n+y*h+c*u,b[8]=x*k+y*t+c*a,b}};e.mul=e.multiply;e.translate=function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4],t=a[5],e=a[6],u=a[7];a=a[8];var p=c[0];c=c[1];return b[0]=d,b[1]=n,b[2]=k,b[3]=m,b[4]=h,b[5]=t,b[6]=p*d+c*m+e,b[7]=p*n+c*h+u,b[8]=p*k+c*t+a,b};e.rotate=function(b,a,c){var d=a[0],n=a[1],k=a[2],m=a[3],h=a[4],t=a[5],e=a[6],u=a[7];a=a[8];var p=Math.sin(c);c=Math.cos(c);return b[0]=
c*d+p*m,b[1]=c*n+p*h,b[2]=c*k+p*t,b[3]=c*m-p*d,b[4]=c*h-p*n,b[5]=c*t-p*k,b[6]=e,b[7]=u,b[8]=a,b};e.scale=function(b,a,c){var d=c[0];c=c[1];return b[0]=d*a[0],b[1]=d*a[1],b[2]=d*a[2],b[3]=c*a[3],b[4]=c*a[4],b[5]=c*a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b};e.fromTranslation=function(b,a){return b[0]=1,b[1]=0,b[2]=0,b[3]=0,b[4]=1,b[5]=0,b[6]=a[0],b[7]=a[1],b[8]=1,b};e.fromRotation=function(b,a){var c=Math.sin(a),d=Math.cos(a);return b[0]=d,b[1]=c,b[2]=0,b[3]=-c,b[4]=d,b[5]=0,b[6]=0,b[7]=0,b[8]=1,b};e.fromScaling=
function(b,a){return b[0]=a[0],b[1]=0,b[2]=0,b[3]=0,b[4]=a[1],b[5]=0,b[6]=0,b[7]=0,b[8]=1,b};e.fromMat2d=function(b,a){return b[0]=a[0],b[1]=a[1],b[2]=0,b[3]=a[2],b[4]=a[3],b[5]=0,b[6]=a[4],b[7]=a[5],b[8]=1,b};e.fromQuat=function(b,a){var c=a[0],d=a[1],n=a[2],k=a[3],m=c+c,h=d+d,t=n+n,c=c*m,e=d*m,d=d*h,u=n*m,p=n*h,n=n*t,m=k*m,h=k*h,k=k*t;return b[0]=1-d-n,b[3]=e-k,b[6]=u+h,b[1]=e+k,b[4]=1-c-n,b[7]=p-m,b[2]=u-h,b[5]=p+m,b[8]=1-c-d,b};e.normalFromMat4=function(b,a){var c=a[0],d=a[1],n=a[2],k=a[3],m=
a[4],h=a[5],t=a[6],e=a[7],u=a[8],p=a[9],f=a[10],g=a[11],l=a[12],r=a[13],v=a[14],x=a[15],y=c*h-d*m,A=c*t-n*m,z=c*e-k*m,D=d*t-n*h,B=d*e-k*h,H=n*e-k*t,I=u*r-p*l,J=u*v-f*l,u=u*x-g*l,K=p*v-f*r,p=p*x-g*r,f=f*x-g*v;return(g=y*f-A*p+z*K+D*u-B*J+H*I)?(g=1/g,b[0]=(h*f-t*p+e*K)*g,b[1]=(t*u-m*f-e*J)*g,b[2]=(m*p-h*u+e*I)*g,b[3]=(n*p-d*f-k*K)*g,b[4]=(c*f-n*u+k*J)*g,b[5]=(d*u-c*p-k*I)*g,b[6]=(r*H-v*B+x*D)*g,b[7]=(v*z-l*H-x*A)*g,b[8]=(l*B-r*z+x*y)*g,b):null};e.str=function(b){return"mat3("+b[0]+", "+b[1]+", "+b[2]+
", "+b[3]+", "+b[4]+", "+b[5]+", "+b[6]+", "+b[7]+", "+b[8]+")"};e.frob=function(b){return Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)+Math.pow(b[2],2)+Math.pow(b[3],2)+Math.pow(b[4],2)+Math.pow(b[5],2)+Math.pow(b[6],2)+Math.pow(b[7],2)+Math.pow(b[8],2))};f.exports=e},function(f,e,g){var l=g(1),b={scalar:{},SIMD:{},create:function(){var a=new l.ARRAY_TYPE(16);return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a},clone:function(a){var c=
new l.ARRAY_TYPE(16);return c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15],c},copy:function(a,c){return a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a},identity:function(a){return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=0,a[9]=0,
a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a}};b.scalar.transpose=function(a,c){if(a===c){var d=c[1],b=c[2],k=c[3],m=c[6],h=c[7],t=c[11];a[1]=c[4];a[2]=c[8];a[3]=c[12];a[4]=d;a[6]=c[9];a[7]=c[13];a[8]=b;a[9]=m;a[11]=c[14];a[12]=k;a[13]=h;a[14]=t}else a[0]=c[0],a[1]=c[4],a[2]=c[8],a[3]=c[12],a[4]=c[1],a[5]=c[5],a[6]=c[9],a[7]=c[13],a[8]=c[2],a[9]=c[6],a[10]=c[10],a[11]=c[14],a[12]=c[3],a[13]=c[7],a[14]=c[11],a[15]=c[15];return a};b.SIMD.transpose=function(a,c){var d,b,k,m,h,t,e,u,p,f;return d=
SIMD.Float32x4.load(c,0),b=SIMD.Float32x4.load(c,4),k=SIMD.Float32x4.load(c,8),m=SIMD.Float32x4.load(c,12),h=SIMD.Float32x4.shuffle(d,b,0,1,4,5),t=SIMD.Float32x4.shuffle(k,m,0,1,4,5),e=SIMD.Float32x4.shuffle(h,t,0,2,4,6),u=SIMD.Float32x4.shuffle(h,t,1,3,5,7),SIMD.Float32x4.store(a,0,e),SIMD.Float32x4.store(a,4,u),h=SIMD.Float32x4.shuffle(d,b,2,3,6,7),t=SIMD.Float32x4.shuffle(k,m,2,3,6,7),p=SIMD.Float32x4.shuffle(h,t,0,2,4,6),f=SIMD.Float32x4.shuffle(h,t,1,3,5,7),SIMD.Float32x4.store(a,8,p),SIMD.Float32x4.store(a,
12,f),a};b.transpose=l.USE_SIMD?b.SIMD.transpose:b.scalar.transpose;b.scalar.invert=function(a,c){var d=c[0],b=c[1],k=c[2],m=c[3],h=c[4],t=c[5],e=c[6],u=c[7],p=c[8],f=c[9],g=c[10],l=c[11],r=c[12],v=c[13],x=c[14],y=c[15],A=d*t-b*h,z=d*e-k*h,D=d*u-m*h,B=b*e-k*t,H=b*u-m*t,I=k*u-m*e,J=p*v-f*r,K=p*x-g*r,L=p*y-l*r,M=f*x-g*v,F=f*y-l*v,G=g*y-l*x,E=A*G-z*F+D*M+B*L-H*K+I*J;return E?(E=1/E,a[0]=(t*G-e*F+u*M)*E,a[1]=(k*F-b*G-m*M)*E,a[2]=(v*I-x*H+y*B)*E,a[3]=(g*H-f*I-l*B)*E,a[4]=(e*L-h*G-u*K)*E,a[5]=(d*G-k*L+
m*K)*E,a[6]=(x*D-r*I-y*z)*E,a[7]=(p*I-g*D+l*z)*E,a[8]=(h*F-t*L+u*J)*E,a[9]=(b*L-d*F-m*J)*E,a[10]=(r*H-v*D+y*A)*E,a[11]=(f*D-p*H-l*A)*E,a[12]=(t*K-h*M-e*J)*E,a[13]=(d*M-b*K+k*J)*E,a[14]=(v*z-r*B-x*A)*E,a[15]=(p*B-f*z+g*A)*E,a):null};b.SIMD.invert=function(a,c){var d,b,k,m,h,e,f,u,p,g,l=SIMD.Float32x4.load(c,0),q=SIMD.Float32x4.load(c,4),r=SIMD.Float32x4.load(c,8),v=SIMD.Float32x4.load(c,12);return h=SIMD.Float32x4.shuffle(l,q,0,1,4,5),b=SIMD.Float32x4.shuffle(r,v,0,1,4,5),d=SIMD.Float32x4.shuffle(h,
b,0,2,4,6),b=SIMD.Float32x4.shuffle(b,h,1,3,5,7),h=SIMD.Float32x4.shuffle(l,q,2,3,6,7),m=SIMD.Float32x4.shuffle(r,v,2,3,6,7),k=SIMD.Float32x4.shuffle(h,m,0,2,4,6),m=SIMD.Float32x4.shuffle(m,h,1,3,5,7),h=SIMD.Float32x4.mul(k,m),h=SIMD.Float32x4.swizzle(h,1,0,3,2),e=SIMD.Float32x4.mul(b,h),f=SIMD.Float32x4.mul(d,h),h=SIMD.Float32x4.swizzle(h,2,3,0,1),e=SIMD.Float32x4.sub(SIMD.Float32x4.mul(b,h),e),f=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,h),f),f=SIMD.Float32x4.swizzle(f,2,3,0,1),h=SIMD.Float32x4.mul(b,
k),h=SIMD.Float32x4.swizzle(h,1,0,3,2),e=SIMD.Float32x4.add(SIMD.Float32x4.mul(m,h),e),p=SIMD.Float32x4.mul(d,h),h=SIMD.Float32x4.swizzle(h,2,3,0,1),e=SIMD.Float32x4.sub(e,SIMD.Float32x4.mul(m,h)),p=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,h),p),p=SIMD.Float32x4.swizzle(p,2,3,0,1),h=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(b,2,3,0,1),m),h=SIMD.Float32x4.swizzle(h,1,0,3,2),k=SIMD.Float32x4.swizzle(k,2,3,0,1),e=SIMD.Float32x4.add(SIMD.Float32x4.mul(k,h),e),u=SIMD.Float32x4.mul(d,h),h=SIMD.Float32x4.swizzle(h,
2,3,0,1),e=SIMD.Float32x4.sub(e,SIMD.Float32x4.mul(k,h)),u=SIMD.Float32x4.sub(SIMD.Float32x4.mul(d,h),u),u=SIMD.Float32x4.swizzle(u,2,3,0,1),h=SIMD.Float32x4.mul(d,b),h=SIMD.Float32x4.swizzle(h,1,0,3,2),u=SIMD.Float32x4.add(SIMD.Float32x4.mul(m,h),u),p=SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,h),p),h=SIMD.Float32x4.swizzle(h,2,3,0,1),u=SIMD.Float32x4.sub(SIMD.Float32x4.mul(m,h),u),p=SIMD.Float32x4.sub(p,SIMD.Float32x4.mul(k,h)),h=SIMD.Float32x4.mul(d,m),h=SIMD.Float32x4.swizzle(h,1,0,3,2),f=SIMD.Float32x4.sub(f,
SIMD.Float32x4.mul(k,h)),u=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,h),u),h=SIMD.Float32x4.swizzle(h,2,3,0,1),f=SIMD.Float32x4.add(SIMD.Float32x4.mul(k,h),f),u=SIMD.Float32x4.sub(u,SIMD.Float32x4.mul(b,h)),h=SIMD.Float32x4.mul(d,k),h=SIMD.Float32x4.swizzle(h,1,0,3,2),f=SIMD.Float32x4.add(SIMD.Float32x4.mul(m,h),f),p=SIMD.Float32x4.sub(p,SIMD.Float32x4.mul(b,h)),h=SIMD.Float32x4.swizzle(h,2,3,0,1),f=SIMD.Float32x4.sub(f,SIMD.Float32x4.mul(m,h)),p=SIMD.Float32x4.add(SIMD.Float32x4.mul(b,h),p),g=SIMD.Float32x4.mul(d,
e),g=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(g,2,3,0,1),g),g=SIMD.Float32x4.add(SIMD.Float32x4.swizzle(g,1,0,3,2),g),h=SIMD.Float32x4.reciprocalApproximation(g),g=SIMD.Float32x4.sub(SIMD.Float32x4.add(h,h),SIMD.Float32x4.mul(g,SIMD.Float32x4.mul(h,h))),(g=SIMD.Float32x4.swizzle(g,0,0,0,0))?(SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(g,e)),SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(g,f)),SIMD.Float32x4.store(a,8,SIMD.Float32x4.mul(g,u)),SIMD.Float32x4.store(a,12,SIMD.Float32x4.mul(g,p)),a):null};
b.invert=l.USE_SIMD?b.SIMD.invert:b.scalar.invert;b.scalar.adjoint=function(a,c){var d=c[0],b=c[1],k=c[2],m=c[3],h=c[4],e=c[5],f=c[6],g=c[7],p=c[8],l=c[9],w=c[10],q=c[11],r=c[12],v=c[13],x=c[14],y=c[15];return a[0]=e*(w*y-q*x)-l*(f*y-g*x)+v*(f*q-g*w),a[1]=-(b*(w*y-q*x)-l*(k*y-m*x)+v*(k*q-m*w)),a[2]=b*(f*y-g*x)-e*(k*y-m*x)+v*(k*g-m*f),a[3]=-(b*(f*q-g*w)-e*(k*q-m*w)+l*(k*g-m*f)),a[4]=-(h*(w*y-q*x)-p*(f*y-g*x)+r*(f*q-g*w)),a[5]=d*(w*y-q*x)-p*(k*y-m*x)+r*(k*q-m*w),a[6]=-(d*(f*y-g*x)-h*(k*y-m*x)+r*(k*
g-m*f)),a[7]=d*(f*q-g*w)-h*(k*q-m*w)+p*(k*g-m*f),a[8]=h*(l*y-q*v)-p*(e*y-g*v)+r*(e*q-g*l),a[9]=-(d*(l*y-q*v)-p*(b*y-m*v)+r*(b*q-m*l)),a[10]=d*(e*y-g*v)-h*(b*y-m*v)+r*(b*g-m*e),a[11]=-(d*(e*q-g*l)-h*(b*q-m*l)+p*(b*g-m*e)),a[12]=-(h*(l*x-w*v)-p*(e*x-f*v)+r*(e*w-f*l)),a[13]=d*(l*x-w*v)-p*(b*x-k*v)+r*(b*w-k*l),a[14]=-(d*(e*x-f*v)-h*(b*x-k*v)+r*(b*f-k*e)),a[15]=d*(e*w-f*l)-h*(b*w-k*l)+p*(b*f-k*e),a};b.SIMD.adjoint=function(a,c){var d,b,k,m,h,e,f,g,p,l,w,q,r;d=SIMD.Float32x4.load(c,0);b=SIMD.Float32x4.load(c,
4);k=SIMD.Float32x4.load(c,8);m=SIMD.Float32x4.load(c,12);return p=SIMD.Float32x4.shuffle(d,b,0,1,4,5),e=SIMD.Float32x4.shuffle(k,m,0,1,4,5),h=SIMD.Float32x4.shuffle(p,e,0,2,4,6),e=SIMD.Float32x4.shuffle(e,p,1,3,5,7),p=SIMD.Float32x4.shuffle(d,b,2,3,6,7),g=SIMD.Float32x4.shuffle(k,m,2,3,6,7),f=SIMD.Float32x4.shuffle(p,g,0,2,4,6),g=SIMD.Float32x4.shuffle(g,p,1,3,5,7),p=SIMD.Float32x4.mul(f,g),p=SIMD.Float32x4.swizzle(p,1,0,3,2),l=SIMD.Float32x4.mul(e,p),w=SIMD.Float32x4.mul(h,p),p=SIMD.Float32x4.swizzle(p,
2,3,0,1),l=SIMD.Float32x4.sub(SIMD.Float32x4.mul(e,p),l),w=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,p),w),w=SIMD.Float32x4.swizzle(w,2,3,0,1),p=SIMD.Float32x4.mul(e,f),p=SIMD.Float32x4.swizzle(p,1,0,3,2),l=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,p),l),r=SIMD.Float32x4.mul(h,p),p=SIMD.Float32x4.swizzle(p,2,3,0,1),l=SIMD.Float32x4.sub(l,SIMD.Float32x4.mul(g,p)),r=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,p),r),r=SIMD.Float32x4.swizzle(r,2,3,0,1),p=SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(e,2,3,0,1),g),
p=SIMD.Float32x4.swizzle(p,1,0,3,2),f=SIMD.Float32x4.swizzle(f,2,3,0,1),l=SIMD.Float32x4.add(SIMD.Float32x4.mul(f,p),l),q=SIMD.Float32x4.mul(h,p),p=SIMD.Float32x4.swizzle(p,2,3,0,1),l=SIMD.Float32x4.sub(l,SIMD.Float32x4.mul(f,p)),q=SIMD.Float32x4.sub(SIMD.Float32x4.mul(h,p),q),q=SIMD.Float32x4.swizzle(q,2,3,0,1),p=SIMD.Float32x4.mul(h,e),p=SIMD.Float32x4.swizzle(p,1,0,3,2),q=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,p),q),r=SIMD.Float32x4.sub(SIMD.Float32x4.mul(f,p),r),p=SIMD.Float32x4.swizzle(p,2,
3,0,1),q=SIMD.Float32x4.sub(SIMD.Float32x4.mul(g,p),q),r=SIMD.Float32x4.sub(r,SIMD.Float32x4.mul(f,p)),p=SIMD.Float32x4.mul(h,g),p=SIMD.Float32x4.swizzle(p,1,0,3,2),w=SIMD.Float32x4.sub(w,SIMD.Float32x4.mul(f,p)),q=SIMD.Float32x4.add(SIMD.Float32x4.mul(e,p),q),p=SIMD.Float32x4.swizzle(p,2,3,0,1),w=SIMD.Float32x4.add(SIMD.Float32x4.mul(f,p),w),q=SIMD.Float32x4.sub(q,SIMD.Float32x4.mul(e,p)),p=SIMD.Float32x4.mul(h,f),p=SIMD.Float32x4.swizzle(p,1,0,3,2),w=SIMD.Float32x4.add(SIMD.Float32x4.mul(g,p),w),
r=SIMD.Float32x4.sub(r,SIMD.Float32x4.mul(e,p)),p=SIMD.Float32x4.swizzle(p,2,3,0,1),w=SIMD.Float32x4.sub(w,SIMD.Float32x4.mul(g,p)),r=SIMD.Float32x4.add(SIMD.Float32x4.mul(e,p),r),SIMD.Float32x4.store(a,0,l),SIMD.Float32x4.store(a,4,w),SIMD.Float32x4.store(a,8,q),SIMD.Float32x4.store(a,12,r),a};b.adjoint=l.USE_SIMD?b.SIMD.adjoint:b.scalar.adjoint;b.determinant=function(a){var c=a[0],d=a[1],b=a[2],k=a[3],m=a[4],h=a[5],e=a[6],f=a[7],g=a[8],p=a[9],l=a[10],w=a[11],q=a[12],r=a[13],v=a[14];a=a[15];return(c*
h-d*m)*(l*a-w*v)-(c*e-b*m)*(p*a-w*r)+(c*f-k*m)*(p*v-l*r)+(d*e-b*h)*(g*a-w*q)-(d*f-k*h)*(g*v-l*q)+(b*f-k*e)*(g*r-p*q)};b.SIMD.multiply=function(a,c,d){var b=SIMD.Float32x4.load(c,0),k=SIMD.Float32x4.load(c,4),m=SIMD.Float32x4.load(c,8);c=SIMD.Float32x4.load(c,12);var h=SIMD.Float32x4.load(d,0),h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,
2,2,2,2),m),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,0,h);h=SIMD.Float32x4.load(d,4);h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,2,2,2,2),m),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,4,h);h=SIMD.Float32x4.load(d,8);h=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,
0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,2,2,2,2),m),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(h,3,3,3,3),c))));SIMD.Float32x4.store(a,8,h);d=SIMD.Float32x4.load(d,12);b=SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,0,0,0,0),b),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,1,1,1,1),k),SIMD.Float32x4.add(SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,2,2,2,2),
m),SIMD.Float32x4.mul(SIMD.Float32x4.swizzle(d,3,3,3,3),c))));return SIMD.Float32x4.store(a,12,b),a};b.scalar.multiply=function(a,c,d){var b=c[0],k=c[1],m=c[2],h=c[3],e=c[4],f=c[5],g=c[6],p=c[7],l=c[8],w=c[9],q=c[10],r=c[11],v=c[12],x=c[13],y=c[14];c=c[15];var A=d[0],z=d[1],D=d[2],B=d[3];return a[0]=A*b+z*e+D*l+B*v,a[1]=A*k+z*f+D*w+B*x,a[2]=A*m+z*g+D*q+B*y,a[3]=A*h+z*p+D*r+B*c,A=d[4],z=d[5],D=d[6],B=d[7],a[4]=A*b+z*e+D*l+B*v,a[5]=A*k+z*f+D*w+B*x,a[6]=A*m+z*g+D*q+B*y,a[7]=A*h+z*p+D*r+B*c,A=d[8],z=
d[9],D=d[10],B=d[11],a[8]=A*b+z*e+D*l+B*v,a[9]=A*k+z*f+D*w+B*x,a[10]=A*m+z*g+D*q+B*y,a[11]=A*h+z*p+D*r+B*c,A=d[12],z=d[13],D=d[14],B=d[15],a[12]=A*b+z*e+D*l+B*v,a[13]=A*k+z*f+D*w+B*x,a[14]=A*m+z*g+D*q+B*y,a[15]=A*h+z*p+D*r+B*c,a};b.multiply=l.USE_SIMD?b.SIMD.multiply:b.scalar.multiply;b.mul=b.multiply;b.scalar.translate=function(a,c,d){var b,k,m,h,e,f,g,p,l,w,q,r,v=d[0],x=d[1];d=d[2];return c===a?(a[12]=c[0]*v+c[4]*x+c[8]*d+c[12],a[13]=c[1]*v+c[5]*x+c[9]*d+c[13],a[14]=c[2]*v+c[6]*x+c[10]*d+c[14],
a[15]=c[3]*v+c[7]*x+c[11]*d+c[15]):(b=c[0],k=c[1],m=c[2],h=c[3],e=c[4],f=c[5],g=c[6],p=c[7],l=c[8],w=c[9],q=c[10],r=c[11],a[0]=b,a[1]=k,a[2]=m,a[3]=h,a[4]=e,a[5]=f,a[6]=g,a[7]=p,a[8]=l,a[9]=w,a[10]=q,a[11]=r,a[12]=b*v+e*x+l*d+c[12],a[13]=k*v+f*x+w*d+c[13],a[14]=m*v+g*x+q*d+c[14],a[15]=h*v+p*x+r*d+c[15]),a};b.SIMD.translate=function(a,c,b){var d=SIMD.Float32x4.load(c,0),k=SIMD.Float32x4.load(c,4),m=SIMD.Float32x4.load(c,8),h=SIMD.Float32x4.load(c,12);b=SIMD.Float32x4(b[0],b[1],b[2],0);c!==a&&(a[0]=
c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11]);d=SIMD.Float32x4.mul(d,SIMD.Float32x4.swizzle(b,0,0,0,0));k=SIMD.Float32x4.mul(k,SIMD.Float32x4.swizzle(b,1,1,1,1));m=SIMD.Float32x4.mul(m,SIMD.Float32x4.swizzle(b,2,2,2,2));c=SIMD.Float32x4.add(d,SIMD.Float32x4.add(k,SIMD.Float32x4.add(m,h)));return SIMD.Float32x4.store(a,12,c),a};b.translate=l.USE_SIMD?b.SIMD.translate:b.scalar.translate;b.scalar.scale=function(a,c,b){var d=b[0],
k=b[1];b=b[2];return a[0]=c[0]*d,a[1]=c[1]*d,a[2]=c[2]*d,a[3]=c[3]*d,a[4]=c[4]*k,a[5]=c[5]*k,a[6]=c[6]*k,a[7]=c[7]*k,a[8]=c[8]*b,a[9]=c[9]*b,a[10]=c[10]*b,a[11]=c[11]*b,a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a};b.SIMD.scale=function(a,c,b){var d,k,m;b=SIMD.Float32x4(b[0],b[1],b[2],0);return d=SIMD.Float32x4.load(c,0),SIMD.Float32x4.store(a,0,SIMD.Float32x4.mul(d,SIMD.Float32x4.swizzle(b,0,0,0,0))),k=SIMD.Float32x4.load(c,4),SIMD.Float32x4.store(a,4,SIMD.Float32x4.mul(k,SIMD.Float32x4.swizzle(b,
1,1,1,1))),m=SIMD.Float32x4.load(c,8),SIMD.Float32x4.store(a,8,SIMD.Float32x4.mul(m,SIMD.Float32x4.swizzle(b,2,2,2,2))),a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15],a};b.scale=l.USE_SIMD?b.SIMD.scale:b.scalar.scale;b.rotate=function(a,c,b,n){var d,m,h,e,f,g,p,C,w,q,r,v,x,y,A,z,D,B,H,I,J,K,L,M,F=n[0],G=n[1];n=n[2];var E=Math.sqrt(F*F+G*G+n*n);return Math.abs(E)<l.EPSILON?null:(E=1/E,F*=E,G*=E,n*=E,d=Math.sin(b),m=Math.cos(b),h=1-m,e=c[0],f=c[1],g=c[2],p=c[3],C=c[4],w=c[5],q=c[6],r=c[7],v=c[8],x=
c[9],y=c[10],A=c[11],z=F*F*h+m,D=G*F*h+n*d,B=n*F*h-G*d,H=F*G*h-n*d,I=G*G*h+m,J=n*G*h+F*d,K=F*n*h+G*d,L=G*n*h-F*d,M=n*n*h+m,a[0]=e*z+C*D+v*B,a[1]=f*z+w*D+x*B,a[2]=g*z+q*D+y*B,a[3]=p*z+r*D+A*B,a[4]=e*H+C*I+v*J,a[5]=f*H+w*I+x*J,a[6]=g*H+q*I+y*J,a[7]=p*H+r*I+A*J,a[8]=e*K+C*L+v*M,a[9]=f*K+w*L+x*M,a[10]=g*K+q*L+y*M,a[11]=p*K+r*L+A*M,c!==a&&(a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a)};b.scalar.rotateX=function(a,c,b){var d=Math.sin(b);b=Math.cos(b);var k=c[4],m=c[5],h=c[6],e=c[7],f=c[8],g=c[9],
p=c[10],l=c[11];return c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[4]=k*b+f*d,a[5]=m*b+g*d,a[6]=h*b+p*d,a[7]=e*b+l*d,a[8]=f*b-k*d,a[9]=g*b-m*d,a[10]=p*b-h*d,a[11]=l*b-e*d,a};b.SIMD.rotateX=function(a,c,b){var d=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));c!==a&&(a[0]=c[0],a[1]=c[1],a[2]=c[2],a[3]=c[3],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,4);c=SIMD.Float32x4.load(c,8);return SIMD.Float32x4.store(a,
4,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,b),SIMD.Float32x4.mul(c,d))),SIMD.Float32x4.store(a,8,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,b),SIMD.Float32x4.mul(k,d))),a};b.rotateX=l.USE_SIMD?b.SIMD.rotateX:b.scalar.rotateX;b.scalar.rotateY=function(a,c,b){var d=Math.sin(b);b=Math.cos(b);var k=c[0],m=c[1],h=c[2],e=c[3],f=c[8],g=c[9],p=c[10],l=c[11];return c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[0]=k*b-f*d,a[1]=m*b-g*d,a[2]=h*b-p*d,a[3]=e*b-l*
d,a[8]=k*d+f*b,a[9]=m*d+g*b,a[10]=h*d+p*b,a[11]=e*d+l*b,a};b.SIMD.rotateY=function(a,c,b){var d=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));c!==a&&(a[4]=c[4],a[5]=c[5],a[6]=c[6],a[7]=c[7],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,8);return SIMD.Float32x4.store(a,0,SIMD.Float32x4.sub(SIMD.Float32x4.mul(k,b),SIMD.Float32x4.mul(c,d))),SIMD.Float32x4.store(a,8,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,d),SIMD.Float32x4.mul(c,
b))),a};b.rotateY=l.USE_SIMD?b.SIMD.rotateY:b.scalar.rotateY;b.scalar.rotateZ=function(a,c,b){var d=Math.sin(b);b=Math.cos(b);var k=c[0],m=c[1],h=c[2],e=c[3],f=c[4],g=c[5],p=c[6],l=c[7];return c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]),a[0]=k*b+f*d,a[1]=m*b+g*d,a[2]=h*b+p*d,a[3]=e*b+l*d,a[4]=f*b-k*d,a[5]=g*b-m*d,a[6]=p*b-h*d,a[7]=l*b-e*d,a};b.SIMD.rotateZ=function(a,c,b){var d=SIMD.Float32x4.splat(Math.sin(b));b=SIMD.Float32x4.splat(Math.cos(b));
c!==a&&(a[8]=c[8],a[9]=c[9],a[10]=c[10],a[11]=c[11],a[12]=c[12],a[13]=c[13],a[14]=c[14],a[15]=c[15]);var k=SIMD.Float32x4.load(c,0);c=SIMD.Float32x4.load(c,4);return SIMD.Float32x4.store(a,0,SIMD.Float32x4.add(SIMD.Float32x4.mul(k,b),SIMD.Float32x4.mul(c,d))),SIMD.Float32x4.store(a,4,SIMD.Float32x4.sub(SIMD.Float32x4.mul(c,b),SIMD.Float32x4.mul(k,d))),a};b.rotateZ=l.USE_SIMD?b.SIMD.rotateZ:b.scalar.rotateZ;b.fromTranslation=function(a,c){return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=
0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=c[0],a[13]=c[1],a[14]=c[2],a[15]=1,a};b.fromScaling=function(a,c){return a[0]=c[0],a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=c[1],a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=c[2],a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromRotation=function(a,c,b){var d,k,m,h=b[0],e=b[1];b=b[2];var f=Math.sqrt(h*h+e*e+b*b);return Math.abs(f)<l.EPSILON?null:(f=1/f,h*=f,e*=f,b*=f,d=Math.sin(c),k=Math.cos(c),m=1-k,a[0]=h*h*m+k,a[1]=e*h*m+b*d,a[2]=b*h*m-e*d,a[3]=0,a[4]=h*e*m-b*d,a[5]=e*e*m+k,a[6]=
b*e*m+h*d,a[7]=0,a[8]=h*b*m+e*d,a[9]=e*b*m-h*d,a[10]=b*b*m+k,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a)};b.fromXRotation=function(a,c){var b=Math.sin(c),n=Math.cos(c);return a[0]=1,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=n,a[6]=b,a[7]=0,a[8]=0,a[9]=-b,a[10]=n,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromYRotation=function(a,c){var b=Math.sin(c),n=Math.cos(c);return a[0]=n,a[1]=0,a[2]=-b,a[3]=0,a[4]=0,a[5]=1,a[6]=0,a[7]=0,a[8]=b,a[9]=0,a[10]=n,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromZRotation=
function(a,c){var b=Math.sin(c),n=Math.cos(c);return a[0]=n,a[1]=b,a[2]=0,a[3]=0,a[4]=-b,a[5]=n,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=1,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.fromRotationTranslation=function(a,c,b){var d=c[0],k=c[1],m=c[2],h=c[3],e=d+d,f=k+k,g=m+m;c=d*e;var p=d*f,d=d*g,l=k*f,k=k*g,m=m*g,e=h*e,f=h*f,h=h*g;return a[0]=1-(l+m),a[1]=p+h,a[2]=d-f,a[3]=0,a[4]=p-h,a[5]=1-(c+m),a[6]=k+e,a[7]=0,a[8]=d+f,a[9]=k-e,a[10]=1-(c+l),a[11]=0,a[12]=b[0],a[13]=b[1],a[14]=b[2],a[15]=1,a};b.fromRotationTranslationScale=
function(a,c,b,n){var d=c[0],m=c[1],h=c[2],e=c[3],f=d+d,g=m+m,l=h+h;c=d*f;var C=d*g,d=d*l,w=m*g,m=m*l,h=h*l,f=e*f,g=e*g,e=e*l,l=n[0],q=n[1];n=n[2];return a[0]=(1-(w+h))*l,a[1]=(C+e)*l,a[2]=(d-g)*l,a[3]=0,a[4]=(C-e)*q,a[5]=(1-(c+h))*q,a[6]=(m+f)*q,a[7]=0,a[8]=(d+g)*n,a[9]=(m-f)*n,a[10]=(1-(c+w))*n,a[11]=0,a[12]=b[0],a[13]=b[1],a[14]=b[2],a[15]=1,a};b.fromRotationTranslationScaleOrigin=function(a,c,b,n,k){var d=c[0],h=c[1],e=c[2],f=c[3],g=d+d,l=h+h,C=e+e;c=d*g;var w=d*l,d=d*C,q=h*l,h=h*C,e=e*C,g=f*
g,l=f*l,f=f*C,C=n[0],r=n[1];n=n[2];var v=k[0],x=k[1];k=k[2];return a[0]=(1-(q+e))*C,a[1]=(w+f)*C,a[2]=(d-l)*C,a[3]=0,a[4]=(w-f)*r,a[5]=(1-(c+e))*r,a[6]=(h+g)*r,a[7]=0,a[8]=(d+l)*n,a[9]=(h-g)*n,a[10]=(1-(c+q))*n,a[11]=0,a[12]=b[0]+v-(a[0]*v+a[4]*x+a[8]*k),a[13]=b[1]+x-(a[1]*v+a[5]*x+a[9]*k),a[14]=b[2]+k-(a[2]*v+a[6]*x+a[10]*k),a[15]=1,a};b.fromQuat=function(a,c){var b=c[0],n=c[1],k=c[2],m=c[3],e=b+b,f=n+n,g=k+k,b=b*e,l=n*e,n=n*f,p=k*e,C=k*f,k=k*g,e=m*e,f=m*f,m=m*g;return a[0]=1-n-k,a[1]=l+m,a[2]=p-
f,a[3]=0,a[4]=l-m,a[5]=1-b-k,a[6]=C+e,a[7]=0,a[8]=p+f,a[9]=C-e,a[10]=1-b-n,a[11]=0,a[12]=0,a[13]=0,a[14]=0,a[15]=1,a};b.frustum=function(a,c,b,n,k,m,e){var d=1/(b-c),h=1/(k-n),f=1/(m-e);return a[0]=2*m*d,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=2*m*h,a[6]=0,a[7]=0,a[8]=(b+c)*d,a[9]=(k+n)*h,a[10]=(e+m)*f,a[11]=-1,a[12]=0,a[13]=0,a[14]=e*m*2*f,a[15]=0,a};b.perspective=function(a,c,b,n,k){c=1/Math.tan(c/2);var d=1/(n-k);return a[0]=c/b,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=c,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=(k+
n)*d,a[11]=-1,a[12]=0,a[13]=0,a[14]=2*k*n*d,a[15]=0,a};b.perspectiveFromFieldOfView=function(a,c,b,n){var d=Math.tan(c.upDegrees*Math.PI/180),m=Math.tan(c.downDegrees*Math.PI/180),e=Math.tan(c.leftDegrees*Math.PI/180);c=Math.tan(c.rightDegrees*Math.PI/180);var f=2/(e+c),g=2/(d+m);return a[0]=f,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=g,a[6]=0,a[7]=0,a[8]=-((e-c)*f*.5),a[9]=(d-m)*g*.5,a[10]=n/(b-n),a[11]=-1,a[12]=0,a[13]=0,a[14]=n*b/(b-n),a[15]=0,a};b.ortho=function(a,c,b,n,k,m,e){var d=1/(c-b),h=1/(n-k),
f=1/(m-e);return a[0]=-2*d,a[1]=0,a[2]=0,a[3]=0,a[4]=0,a[5]=-2*h,a[6]=0,a[7]=0,a[8]=0,a[9]=0,a[10]=2*f,a[11]=0,a[12]=(c+b)*d,a[13]=(k+n)*h,a[14]=(e+m)*f,a[15]=1,a};b.lookAt=function(a,c,d,n){var k,e,h,f,g,u,p,C,w,q,r=c[0],v=c[1];c=c[2];var x=n[0],y=n[1];n=n[2];var A=d[0],z=d[1];d=d[2];return Math.abs(r-A)<l.EPSILON&&Math.abs(v-z)<l.EPSILON&&Math.abs(c-d)<l.EPSILON?b.identity(a):(p=r-A,C=v-z,w=c-d,q=1/Math.sqrt(p*p+C*C+w*w),p*=q,C*=q,w*=q,k=y*w-n*C,e=n*p-x*w,h=x*C-y*p,q=Math.sqrt(k*k+e*e+h*h),q?(q=
1/q,k*=q,e*=q,h*=q):(k=0,e=0,h=0),f=C*h-w*e,g=w*k-p*h,u=p*e-C*k,q=Math.sqrt(f*f+g*g+u*u),q?(q=1/q,f*=q,g*=q,u*=q):(f=0,g=0,u=0),a[0]=k,a[1]=f,a[2]=p,a[3]=0,a[4]=e,a[5]=g,a[6]=C,a[7]=0,a[8]=h,a[9]=u,a[10]=w,a[11]=0,a[12]=-(k*r+e*v+h*c),a[13]=-(f*r+g*v+u*c),a[14]=-(p*r+C*v+w*c),a[15]=1,a)};b.str=function(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"};b.frob=function(a){return Math.sqrt(Math.pow(a[0],
2)+Math.pow(a[1],2)+Math.pow(a[2],2)+Math.pow(a[3],2)+Math.pow(a[4],2)+Math.pow(a[5],2)+Math.pow(a[6],2)+Math.pow(a[7],2)+Math.pow(a[8],2)+Math.pow(a[9],2)+Math.pow(a[10],2)+Math.pow(a[11],2)+Math.pow(a[12],2)+Math.pow(a[13],2)+Math.pow(a[14],2)+Math.pow(a[15],2))};f.exports=b},function(f,e,g){var l=g(1),b=g(4),a=g(7);e=g(8);var c={create:function(){var a=new l.ARRAY_TYPE(4);return a[0]=0,a[1]=0,a[2]=0,a[3]=1,a}};c.rotationTo=function(){var b=a.create(),n=a.fromValues(1,0,0),k=a.fromValues(0,1,0);
return function(d,e,f){var m=a.dot(e,f);return-.999999>m?(a.cross(b,n,e),1E-6>a.length(b)&&a.cross(b,k,e),a.normalize(b,b),c.setAxisAngle(d,b,Math.PI),d):.999999<m?(d[0]=0,d[1]=0,d[2]=0,d[3]=1,d):(a.cross(b,e,f),d[0]=b[0],d[1]=b[1],d[2]=b[2],d[3]=1+m,c.normalize(d,d))}}();c.setAxes=function(){var a=b.create();return function(b,d,e,h){return a[0]=e[0],a[3]=e[1],a[6]=e[2],a[1]=h[0],a[4]=h[1],a[7]=h[2],a[2]=-d[0],a[5]=-d[1],a[8]=-d[2],c.normalize(b,c.fromMat3(b,a))}}();c.clone=e.clone;c.fromValues=e.fromValues;
c.copy=e.copy;c.set=e.set;c.identity=function(a){return a[0]=0,a[1]=0,a[2]=0,a[3]=1,a};c.setAxisAngle=function(a,c,b){b*=.5;var d=Math.sin(b);return a[0]=d*c[0],a[1]=d*c[1],a[2]=d*c[2],a[3]=Math.cos(b),a};c.add=e.add;c.multiply=function(a,c,b){var d=c[0],n=c[1],k=c[2];c=c[3];var e=b[0],f=b[1],g=b[2];b=b[3];return a[0]=d*b+c*e+n*g-k*f,a[1]=n*b+c*f+k*e-d*g,a[2]=k*b+c*g+d*f-n*e,a[3]=c*b-d*e-n*f-k*g,a};c.mul=c.multiply;c.scale=e.scale;c.rotateX=function(a,c,b){b*=.5;var d=c[0],n=c[1],e=c[2];c=c[3];var k=
Math.sin(b);b=Math.cos(b);return a[0]=d*b+c*k,a[1]=n*b+e*k,a[2]=e*b-n*k,a[3]=c*b-d*k,a};c.rotateY=function(a,c,b){b*=.5;var d=c[0],e=c[1],n=c[2];c=c[3];var k=Math.sin(b);b=Math.cos(b);return a[0]=d*b-n*k,a[1]=e*b+c*k,a[2]=n*b+d*k,a[3]=c*b-e*k,a};c.rotateZ=function(a,c,b){b*=.5;var d=c[0],e=c[1],n=c[2];c=c[3];var k=Math.sin(b);b=Math.cos(b);return a[0]=d*b+e*k,a[1]=e*b-d*k,a[2]=n*b+c*k,a[3]=c*b-n*k,a};c.calculateW=function(a,c){var b=c[0],d=c[1],e=c[2];return a[0]=b,a[1]=d,a[2]=e,a[3]=Math.sqrt(Math.abs(1-
b*b-d*d-e*e)),a};c.dot=e.dot;c.lerp=e.lerp;c.slerp=function(a,c,b,e){var d,n,k,m,f,g=c[0],l=c[1],q=c[2];c=c[3];var r=b[0],v=b[1],x=b[2];b=b[3];return n=g*r+l*v+q*x+c*b,0>n&&(n=-n,r=-r,v=-v,x=-x,b=-b),1E-6<1-n?(d=Math.acos(n),k=Math.sin(d),m=Math.sin((1-e)*d)/k,f=Math.sin(e*d)/k):(m=1-e,f=e),a[0]=m*g+f*r,a[1]=m*l+f*v,a[2]=m*q+f*x,a[3]=m*c+f*b,a};c.sqlerp=function(){var a=c.create(),b=c.create();return function(d,e,n,f,g,l){return c.slerp(a,e,g,l),c.slerp(b,n,f,l),c.slerp(d,a,b,2*l*(1-l)),d}}();c.invert=
function(a,c){var b=c[0],d=c[1],e=c[2],n=c[3],f=b*b+d*d+e*e+n*n,f=f?1/f:0;return a[0]=-b*f,a[1]=-d*f,a[2]=-e*f,a[3]=n*f,a};c.conjugate=function(a,c){return a[0]=-c[0],a[1]=-c[1],a[2]=-c[2],a[3]=c[3],a};c.length=e.length;c.len=c.length;c.squaredLength=e.squaredLength;c.sqrLen=c.squaredLength;c.normalize=e.normalize;c.fromMat3=function(a,c){var b;b=c[0]+c[4]+c[8];if(0<b)b=Math.sqrt(b+1),a[3]=.5*b,b=.5/b,a[0]=(c[5]-c[7])*b,a[1]=(c[6]-c[2])*b,a[2]=(c[1]-c[3])*b;else{var d=0;c[4]>c[0]&&(d=1);c[8]>c[3*
d+d]&&(d=2);var e=(d+1)%3,n=(d+2)%3;b=Math.sqrt(c[3*d+d]-c[3*e+e]-c[3*n+n]+1);a[d]=.5*b;b=.5/b;a[3]=(c[3*e+n]-c[3*n+e])*b;a[e]=(c[3*e+d]+c[3*d+e])*b;a[n]=(c[3*n+d]+c[3*d+n])*b}return a};c.str=function(a){return"quat("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};f.exports=c},function(f,e,g){var l=g(1),b={create:function(){var a=new l.ARRAY_TYPE(3);return a[0]=0,a[1]=0,a[2]=0,a},clone:function(a){var c=new l.ARRAY_TYPE(3);return c[0]=a[0],c[1]=a[1],c[2]=a[2],c},fromValues:function(a,c,b){var d=new l.ARRAY_TYPE(3);
return d[0]=a,d[1]=c,d[2]=b,d},copy:function(a,c){return a[0]=c[0],a[1]=c[1],a[2]=c[2],a},set:function(a,c,b,e){return a[0]=c,a[1]=b,a[2]=e,a},add:function(a,c,b){return a[0]=c[0]+b[0],a[1]=c[1]+b[1],a[2]=c[2]+b[2],a},subtract:function(a,c,b){return a[0]=c[0]-b[0],a[1]=c[1]-b[1],a[2]=c[2]-b[2],a}};b.sub=b.subtract;b.multiply=function(a,c,b){return a[0]=c[0]*b[0],a[1]=c[1]*b[1],a[2]=c[2]*b[2],a};b.mul=b.multiply;b.divide=function(a,c,b){return a[0]=c[0]/b[0],a[1]=c[1]/b[1],a[2]=c[2]/b[2],a};b.div=
b.divide;b.min=function(a,c,b){return a[0]=Math.min(c[0],b[0]),a[1]=Math.min(c[1],b[1]),a[2]=Math.min(c[2],b[2]),a};b.max=function(a,c,b){return a[0]=Math.max(c[0],b[0]),a[1]=Math.max(c[1],b[1]),a[2]=Math.max(c[2],b[2]),a};b.scale=function(a,c,b){return a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b,a};b.scaleAndAdd=function(a,c,b,e){return a[0]=c[0]+b[0]*e,a[1]=c[1]+b[1]*e,a[2]=c[2]+b[2]*e,a};b.distance=function(a,c){var b=c[0]-a[0],e=c[1]-a[1],k=c[2]-a[2];return Math.sqrt(b*b+e*e+k*k)};b.dist=b.distance;b.squaredDistance=
function(a,c){var b=c[0]-a[0],e=c[1]-a[1],k=c[2]-a[2];return b*b+e*e+k*k};b.sqrDist=b.squaredDistance;b.length=function(a){var c=a[0],b=a[1];a=a[2];return Math.sqrt(c*c+b*b+a*a)};b.len=b.length;b.squaredLength=function(a){var c=a[0],b=a[1];a=a[2];return c*c+b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,c){return a[0]=-c[0],a[1]=-c[1],a[2]=-c[2],a};b.inverse=function(a,c){return a[0]=1/c[0],a[1]=1/c[1],a[2]=1/c[2],a};b.normalize=function(a,c){var b=c[0],e=c[1],k=c[2],b=b*b+e*e+k*k;return 0<
b&&(b=1/Math.sqrt(b),a[0]=c[0]*b,a[1]=c[1]*b,a[2]=c[2]*b),a};b.dot=function(a,c){return a[0]*c[0]+a[1]*c[1]+a[2]*c[2]};b.cross=function(a,c,b){var d=c[0],e=c[1];c=c[2];var f=b[0],h=b[1];b=b[2];return a[0]=e*b-c*h,a[1]=c*f-d*b,a[2]=d*h-e*f,a};b.lerp=function(a,c,b,e){var d=c[0],n=c[1];c=c[2];return a[0]=d+e*(b[0]-d),a[1]=n+e*(b[1]-n),a[2]=c+e*(b[2]-c),a};b.hermite=function(a,c,b,e,k,f){var d=f*f,n=d*(2*f-3)+1,m=d*(f-2)+f,g=d*(f-1);f=d*(3-2*f);return a[0]=c[0]*n+b[0]*m+e[0]*g+k[0]*f,a[1]=c[1]*n+b[1]*
m+e[1]*g+k[1]*f,a[2]=c[2]*n+b[2]*m+e[2]*g+k[2]*f,a};b.bezier=function(a,c,b,e,k,f){var d=1-f,n=d*d,g=f*f,m=n*d,n=3*f*n,d=3*g*d;f*=g;return a[0]=c[0]*m+b[0]*n+e[0]*d+k[0]*f,a[1]=c[1]*m+b[1]*n+e[1]*d+k[1]*f,a[2]=c[2]*m+b[2]*n+e[2]*d+k[2]*f,a};b.random=function(a,c){c=c||1;var b=2*l.RANDOM()*Math.PI,e=2*l.RANDOM()-1,k=Math.sqrt(1-e*e)*c;return a[0]=Math.cos(b)*k,a[1]=Math.sin(b)*k,a[2]=e*c,a};b.transformMat4=function(a,c,b){var d=c[0],e=c[1];c=c[2];var f=b[3]*d+b[7]*e+b[11]*c+b[15];return f=f||1,a[0]=
(b[0]*d+b[4]*e+b[8]*c+b[12])/f,a[1]=(b[1]*d+b[5]*e+b[9]*c+b[13])/f,a[2]=(b[2]*d+b[6]*e+b[10]*c+b[14])/f,a};b.transformMat3=function(a,c,b){var d=c[0],e=c[1];c=c[2];return a[0]=d*b[0]+e*b[3]+c*b[6],a[1]=d*b[1]+e*b[4]+c*b[7],a[2]=d*b[2]+e*b[5]+c*b[8],a};b.transformQuat=function(a,c,b){var d=c[0],e=c[1],f=c[2];c=b[0];var g=b[1],l=b[2];b=b[3];var N=b*d+g*f-l*e,u=b*e+l*d-c*f,p=b*f+c*e-g*d,d=-c*d-g*e-l*f;return a[0]=N*b+d*-c+u*-l-p*-g,a[1]=u*b+d*-g+p*-c-N*-l,a[2]=p*b+d*-l+N*-g-u*-c,a};b.rotateX=function(a,
b,d,e){var c=[],f=[];return c[0]=b[0]-d[0],c[1]=b[1]-d[1],c[2]=b[2]-d[2],f[0]=c[0],f[1]=c[1]*Math.cos(e)-c[2]*Math.sin(e),f[2]=c[1]*Math.sin(e)+c[2]*Math.cos(e),a[0]=f[0]+d[0],a[1]=f[1]+d[1],a[2]=f[2]+d[2],a};b.rotateY=function(a,b,d,e){var c=[],f=[];return c[0]=b[0]-d[0],c[1]=b[1]-d[1],c[2]=b[2]-d[2],f[0]=c[2]*Math.sin(e)+c[0]*Math.cos(e),f[1]=c[1],f[2]=c[2]*Math.cos(e)-c[0]*Math.sin(e),a[0]=f[0]+d[0],a[1]=f[1]+d[1],a[2]=f[2]+d[2],a};b.rotateZ=function(a,c,b,e){var d=[],f=[];return d[0]=c[0]-b[0],
d[1]=c[1]-b[1],d[2]=c[2]-b[2],f[0]=d[0]*Math.cos(e)-d[1]*Math.sin(e),f[1]=d[0]*Math.sin(e)+d[1]*Math.cos(e),f[2]=d[2],a[0]=f[0]+b[0],a[1]=f[1]+b[1],a[2]=f[2]+b[2],a};b.forEach=function(){var a=b.create();return function(b,d,e,f,g,h){d||(d=3);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;f>e;e+=d)a[0]=b[e],a[1]=b[e+1],a[2]=b[e+2],g(a,a,h),b[e]=a[0],b[e+1]=a[1],b[e+2]=a[2];return b}}();b.angle=function(a,c){var d=b.fromValues(a[0],a[1],a[2]),e=b.fromValues(c[0],c[1],c[2]);b.normalize(d,d);b.normalize(e,
e);d=b.dot(d,e);return 1<d?0:Math.acos(d)};b.str=function(a){return"vec3("+a[0]+", "+a[1]+", "+a[2]+")"};f.exports=b},function(f,e,g){var l=g(1),b={create:function(){var a=new l.ARRAY_TYPE(4);return a[0]=0,a[1]=0,a[2]=0,a[3]=0,a},clone:function(a){var b=new l.ARRAY_TYPE(4);return b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b},fromValues:function(a,b,d,e){var c=new l.ARRAY_TYPE(4);return c[0]=a,c[1]=b,c[2]=d,c[3]=e,c},copy:function(a,b){return a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a},set:function(a,
b,d,e,f){return a[0]=b,a[1]=d,a[2]=e,a[3]=f,a},add:function(a,b,d){return a[0]=b[0]+d[0],a[1]=b[1]+d[1],a[2]=b[2]+d[2],a[3]=b[3]+d[3],a},subtract:function(a,b,d){return a[0]=b[0]-d[0],a[1]=b[1]-d[1],a[2]=b[2]-d[2],a[3]=b[3]-d[3],a}};b.sub=b.subtract;b.multiply=function(a,b,d){return a[0]=b[0]*d[0],a[1]=b[1]*d[1],a[2]=b[2]*d[2],a[3]=b[3]*d[3],a};b.mul=b.multiply;b.divide=function(a,b,d){return a[0]=b[0]/d[0],a[1]=b[1]/d[1],a[2]=b[2]/d[2],a[3]=b[3]/d[3],a};b.div=b.divide;b.min=function(a,b,d){return a[0]=
Math.min(b[0],d[0]),a[1]=Math.min(b[1],d[1]),a[2]=Math.min(b[2],d[2]),a[3]=Math.min(b[3],d[3]),a};b.max=function(a,b,d){return a[0]=Math.max(b[0],d[0]),a[1]=Math.max(b[1],d[1]),a[2]=Math.max(b[2],d[2]),a[3]=Math.max(b[3],d[3]),a};b.scale=function(a,b,d){return a[0]=b[0]*d,a[1]=b[1]*d,a[2]=b[2]*d,a[3]=b[3]*d,a};b.scaleAndAdd=function(a,b,d,e){return a[0]=b[0]+d[0]*e,a[1]=b[1]+d[1]*e,a[2]=b[2]+d[2]*e,a[3]=b[3]+d[3]*e,a};b.distance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1],f=b[2]-a[2],g=b[3]-a[3];return Math.sqrt(c*
c+e*e+f*f+g*g)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1],f=b[2]-a[2],g=b[3]-a[3];return c*c+e*e+f*f+g*g};b.sqrDist=b.squaredDistance;b.length=function(a){var b=a[0],d=a[1],e=a[2];a=a[3];return Math.sqrt(b*b+d*d+e*e+a*a)};b.len=b.length;b.squaredLength=function(a){var b=a[0],d=a[1],e=a[2];a=a[3];return b*b+d*d+e*e+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){return a[0]=-b[0],a[1]=-b[1],a[2]=-b[2],a[3]=-b[3],a};b.inverse=function(a,b){return a[0]=1/b[0],
a[1]=1/b[1],a[2]=1/b[2],a[3]=1/b[3],a};b.normalize=function(a,b){var c=b[0],e=b[1],f=b[2],g=b[3],h=c*c+e*e+f*f+g*g;return 0<h&&(h=1/Math.sqrt(h),a[0]=c*h,a[1]=e*h,a[2]=f*h,a[3]=g*h),a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};b.lerp=function(a,b,d,e){var c=b[0],f=b[1],g=b[2];b=b[3];return a[0]=c+e*(d[0]-c),a[1]=f+e*(d[1]-f),a[2]=g+e*(d[2]-g),a[3]=b+e*(d[3]-b),a};b.random=function(a,c){return c=c||1,a[0]=l.RANDOM(),a[1]=l.RANDOM(),a[2]=l.RANDOM(),a[3]=l.RANDOM(),b.normalize(a,
a),b.scale(a,a,c),a};b.transformMat4=function(a,b,d){var c=b[0],e=b[1],f=b[2];b=b[3];return a[0]=d[0]*c+d[4]*e+d[8]*f+d[12]*b,a[1]=d[1]*c+d[5]*e+d[9]*f+d[13]*b,a[2]=d[2]*c+d[6]*e+d[10]*f+d[14]*b,a[3]=d[3]*c+d[7]*e+d[11]*f+d[15]*b,a};b.transformQuat=function(a,b,d){var c=b[0],e=b[1],f=b[2],g=d[0],l=d[1],N=d[2];d=d[3];var u=d*c+l*f-N*e,p=d*e+N*c-g*f,C=d*f+g*e-l*c,c=-g*c-l*e-N*f;return a[0]=u*d+c*-g+p*-N-C*-l,a[1]=p*d+c*-l+C*-g-u*-N,a[2]=C*d+c*-N+u*-l-p*-g,a[3]=b[3],a};b.forEach=function(){var a=b.create();
return function(b,d,e,f,g,h){d||(d=4);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;f>e;e+=d)a[0]=b[e],a[1]=b[e+1],a[2]=b[e+2],a[3]=b[e+3],g(a,a,h),b[e]=a[0],b[e+1]=a[1],b[e+2]=a[2],b[e+3]=a[3];return b}}();b.str=function(a){return"vec4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+")"};f.exports=b},function(f,e,g){var l=g(1),b={create:function(){var a=new l.ARRAY_TYPE(2);return a[0]=0,a[1]=0,a},clone:function(a){var b=new l.ARRAY_TYPE(2);return b[0]=a[0],b[1]=a[1],b},fromValues:function(a,b){var c=new l.ARRAY_TYPE(2);
return c[0]=a,c[1]=b,c},copy:function(a,b){return a[0]=b[0],a[1]=b[1],a},set:function(a,b,d){return a[0]=b,a[1]=d,a},add:function(a,b,d){return a[0]=b[0]+d[0],a[1]=b[1]+d[1],a},subtract:function(a,b,d){return a[0]=b[0]-d[0],a[1]=b[1]-d[1],a}};b.sub=b.subtract;b.multiply=function(a,b,d){return a[0]=b[0]*d[0],a[1]=b[1]*d[1],a};b.mul=b.multiply;b.divide=function(a,b,d){return a[0]=b[0]/d[0],a[1]=b[1]/d[1],a};b.div=b.divide;b.min=function(a,b,d){return a[0]=Math.min(b[0],d[0]),a[1]=Math.min(b[1],d[1]),
a};b.max=function(a,b,d){return a[0]=Math.max(b[0],d[0]),a[1]=Math.max(b[1],d[1]),a};b.scale=function(a,b,d){return a[0]=b[0]*d,a[1]=b[1]*d,a};b.scaleAndAdd=function(a,b,d,e){return a[0]=b[0]+d[0]*e,a[1]=b[1]+d[1]*e,a};b.distance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1];return Math.sqrt(c*c+e*e)};b.dist=b.distance;b.squaredDistance=function(a,b){var c=b[0]-a[0],e=b[1]-a[1];return c*c+e*e};b.sqrDist=b.squaredDistance;b.length=function(a){var b=a[0];a=a[1];return Math.sqrt(b*b+a*a)};b.len=b.length;
b.squaredLength=function(a){var b=a[0];a=a[1];return b*b+a*a};b.sqrLen=b.squaredLength;b.negate=function(a,b){return a[0]=-b[0],a[1]=-b[1],a};b.inverse=function(a,b){return a[0]=1/b[0],a[1]=1/b[1],a};b.normalize=function(a,b){var c=b[0],e=b[1],c=c*c+e*e;return 0<c&&(c=1/Math.sqrt(c),a[0]=b[0]*c,a[1]=b[1]*c),a};b.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]};b.cross=function(a,b,d){b=b[0]*d[1]-b[1]*d[0];return a[0]=a[1]=0,a[2]=b,a};b.lerp=function(a,b,d,e){var c=b[0];b=b[1];return a[0]=c+e*(d[0]-c),
a[1]=b+e*(d[1]-b),a};b.random=function(a,b){b=b||1;var c=2*l.RANDOM()*Math.PI;return a[0]=Math.cos(c)*b,a[1]=Math.sin(c)*b,a};b.transformMat2=function(a,b,d){var c=b[0];b=b[1];return a[0]=d[0]*c+d[2]*b,a[1]=d[1]*c+d[3]*b,a};b.transformMat2d=function(a,b,d){var c=b[0];b=b[1];return a[0]=d[0]*c+d[2]*b+d[4],a[1]=d[1]*c+d[3]*b+d[5],a};b.transformMat3=function(a,b,d){var c=b[0];b=b[1];return a[0]=d[0]*c+d[3]*b+d[6],a[1]=d[1]*c+d[4]*b+d[7],a};b.transformMat4=function(a,b,d){var c=b[0];b=b[1];return a[0]=
d[0]*c+d[4]*b+d[12],a[1]=d[1]*c+d[5]*b+d[13],a};b.forEach=function(){var a=b.create();return function(b,d,e,f,g,h){d||(d=2);e||(e=0);for(f=f?Math.min(f*d+e,b.length):b.length;f>e;e+=d)a[0]=b[e],a[1]=b[e+1],g(a,a,h),b[e]=a[0],b[e+1]=a[1];return b}}();b.str=function(a){return"vec2("+a[0]+", "+a[1]+")"};f.exports=b}])});
function getShader(f,e,g){g?(f=retrieveShader(f,"vertex"),e=retrieveShader(e,"fragment")):(f=shader(f),e=shader(e));g=gl.createProgram();gl.attachShader(g,f);gl.attachShader(g,e);gl.linkProgram(g);return gl.getProgramParameter(g,gl.LINK_STATUS)?g:(alert("Could not initialise shaders"),null)}function retrieveShader(f,e){}
function shader(f){var e=document.getElementById(f);if(!e)return null;for(var g="",l=e.firstChild;l;)3==l.nodeType&&(g+=l.textContent),l=l.nextSibling;if("frag"==e.type)e=gl.createShader(gl.FRAGMENT_SHADER);else if("vert"==e.type)e=gl.createShader(gl.VERTEX_SHADER);else return null;gl.shaderSource(e,g);gl.compileShader(e);return gl.getShaderParameter(e,gl.COMPILE_STATUS)?e:(alert(gl.getShaderInfoLog(e)+"  "+f),null)}
function createCamera(){this.getViewMatrix=getViewMatrix;this.params=camera_params;this.camera_keydown=camera_keydown;this.camera_keyup=camera_keyup;this.camera_mousemove=camera_mousemove;this.camera_mousedown=camera_mousedown;this.camera_mouseup=camera_mouseup;this.camera_zoom=camera_zoom;this.pos=vec3.fromValues(0,0,0);this.up=vec3.fromValues(0,1,0);this.front=vec3.fromValues(0,0,-1);this.frontCross=vec3.fromValues(0,0,0);this.dir=vec3.fromValues(0,0,0);this.speed=5;this.zoom_smoothness=.1;this.autoCentered=
!1;this.radius=3;this.look=[0,0,0];this.lookAt=mat4.create();this.yaw=-1.57;this.pitch=0;this.deltaRot=[0,0];this.lastPos=[null,null];this.deltazoom=0;this.dragging=!1;this.startingZoom=window.zoom;this.zoomdefined=!1;this.smoothDeltaTimeCheck=!0;this.rotationSensitivity=.002;this.pressedKeys={w:!1,s:!1,a:!1,d:!1,space:!1,shift:!1,la:!1,ua:!1,ra:!1,da:!1};window.addEventListener("keydown",this.camera_keydown.bind(this));window.addEventListener("keyup",this.camera_keyup.bind(this));document.getElementById("canvas").addEventListener("mousemove",
this.camera_mousemove.bind(this));document.getElementById("canvas").addEventListener("mousedown",this.camera_mousedown.bind(this));window.addEventListener("mouseup",this.camera_mouseup.bind(this));window.addEventListener("mousewheel",this.camera_zoom.bind(this));window.addEventListener("DOMMouseScroll",this.camera_zoom.bind(this))}
function camera_params(f,e,g,l,b){void 0!==f&&(this.zoom_smoothness=f);void 0!==e&&(this.speed=e);void 0!==g&&(this.startingZoom=g);void 0!==l&&(this.smoothDeltaTimeCheck=l);void 0!==b&&(this.rotationSensitivity=b)}
function getViewMatrix(f,e){this.smoothDeltaTimeCheck&&.03333>=f&&!(.01>f)&&(f=.016);this.zoomdefined||(this.startingZoom=zoom,this.zoomdefined=!0);if(this.autoCentered)return camera_getAutocenteredViewMatrix.call(this,f,e,this.radius);if(this.pressedKeys.w||this.pressedKeys.ua)this.pos[0]+=f*this.speed*this.front[0],this.pos[1]+=f*this.speed*this.front[1],this.pos[2]+=f*this.speed*this.front[2];if(this.pressedKeys.s||this.pressedKeys.da)this.pos[0]-=f*this.speed*this.front[0],this.pos[1]-=f*this.speed*
this.front[1],this.pos[2]-=f*this.speed*this.front[2];if(this.pressedKeys.d||this.pressedKeys.ra)this.frontCross=vec3.cross(this.frontCross,this.front,this.up),vec3.normalize(this.frontCross,this.frontCross),this.pos[0]+=f*this.speed*this.frontCross[0],this.pos[1]+=f*this.speed*this.frontCross[1],this.pos[2]+=f*this.speed*this.frontCross[2];if(this.pressedKeys.a||this.pressedKeys.la)this.frontCross=vec3.cross(this.frontCross,this.front,this.up),vec3.normalize(this.frontCross,this.frontCross),this.pos[0]-=
f*this.speed*this.frontCross[0],this.pos[1]-=f*this.speed*this.frontCross[1],this.pos[2]-=f*this.speed*this.frontCross[2];this.pressedKeys.space&&(this.pos[0]+=f*this.speed*this.up[0],this.pos[1]+=f*this.speed*this.up[1],this.pos[2]+=f*this.speed*this.up[2]);this.pressedKeys.shift&&(this.pos[0]-=f*this.speed*this.up[0],this.pos[1]-=f*this.speed*this.up[1],this.pos[2]-=f*this.speed*this.up[2]);this.yaw+=this.deltaRot[0]*e;this.pitch-=this.deltaRot[1]*e;this.deltaRot[0]-=this.deltaRot[0]*e;this.deltaRot[1]-=
this.deltaRot[1]*e;1.565<this.pitch&&(this.pitch=1.565);-1.565>this.pitch&&(this.pitch=-1.565);this.front[0]=Math.cos(this.yaw)*Math.cos(this.pitch);this.front[1]=Math.sin(this.pitch);this.front[2]=Math.sin(this.yaw)*Math.cos(this.pitch);vec3.normalize(this.front,this.front);if(0<Math.abs(this.deltazoom)){var g=this.deltazoom*this.zoom_smoothness;0>this.deltazoom&&(this.deltazoom=-.01>this.deltazoom?this.deltazoom-g:0);0<this.deltazoom&&(this.deltazoom=.01<this.deltazoom?this.deltazoom-g:0);zoom+=
g;44.5>zoom&&(zoom=44.5);zoom>this.startingZoom&&(zoom=this.startingZoom)}this.dir[0]=this.pos[0]+this.front[0];this.dir[1]=this.pos[1]+this.front[1];this.dir[2]=this.pos[2]+this.front[2];mat4.lookAt(this.lookAt,this.pos,this.dir,this.up);return this.lookAt}
function camera_keydown(f){switch(f.keyCode){case 87:this.pressedKeys.w=!0;break;case 65:this.pressedKeys.a=!0;break;case 83:this.pressedKeys.s=!0;break;case 68:this.pressedKeys.d=!0;break;case 32:this.pressedKeys.space=!0;break;case 16:this.pressedKeys.shift=!0;break;case 37:this.pressedKeys.la=!0;break;case 38:this.pressedKeys.ua=!0;break;case 39:this.pressedKeys.ra=!0;break;case 40:this.pressedKeys.da=!0}}
function camera_keyup(f){switch(f.keyCode){case 87:this.pressedKeys.w=!1;break;case 65:this.pressedKeys.a=!1;break;case 83:this.pressedKeys.s=!1;break;case 68:this.pressedKeys.d=!1;break;case 32:this.pressedKeys.space=!1;break;case 16:this.pressedKeys.shift=!1;break;case 37:this.pressedKeys.la=!1;break;case 38:this.pressedKeys.ua=!1;break;case 39:this.pressedKeys.ra=!1;break;case 40:this.pressedKeys.da=!1}}
function camera_mousemove(f){this.dragging&&(this.deltaRot[0]+=(f.clientX-this.lastPos[0])*this.rotationSensitivity,this.deltaRot[1]+=(f.clientY-this.lastPos[1])*this.rotationSensitivity,this.lastPos[0]=f.clientX,this.lastPos[1]=f.clientY)}function camera_mousedown(f){1==f.which&&(this.lastPos[0]=f.clientX,this.lastPos[1]=f.clientY,this.dragging=!0)}function camera_mouseup(f){this.dragging=!1}
function camera_zoom(f){this.deltazoom=0<(f.wheelDelta?f.wheelDelta:-f.detail)?this.deltazoom+-.15:this.deltazoom+.15}
function camera_getAutocenteredViewMatrix(f,e,g){this.yaw+=this.deltaRot[0]*e;this.pitch-=this.deltaRot[1]*e;this.deltaRot[0]-=this.deltaRot[0]*e;this.deltaRot[1]-=this.deltaRot[1]*e;1.565<this.pitch&&(this.pitch=1.565);-1.565>this.pitch&&(this.pitch=-1.565);0<Math.abs(this.deltazoom)&&(f=this.deltazoom*this.zoom_smoothness,0>this.deltazoom&&(this.deltazoom=-.01>this.deltazoom?this.deltazoom-f:0),0<this.deltazoom&&(this.deltazoom=.01<this.deltazoom?this.deltazoom-f:0),zoom+=f,44.5>zoom&&(zoom=44.5),
zoom>this.startingZoom&&(zoom=this.startingZoom));f=Math.sin(this.yaw)*Math.cos(this.pitch)*g;e=Math.sin(this.pitch)*g;this.pos[0]=Math.cos(this.yaw)*Math.cos(this.pitch)*g+this.look[0];this.pos[1]=e+this.look[1];this.pos[2]=-f+this.look[2];mat4.lookAt(this.lookAt,this.pos,this.look,this.up);return this.lookAt}window.addEventListener("load",webGLStart);
var gl,Program,buffer,cubeBuffer,camera,projection=mat4.create(),model=mat4.create(),view=mat4.create(),trianglesContainer=new Float32Array(9E6),trianglesContainer200=new Float32Array(144E4),trianglesContainer100=new Float32Array(36E4),trianglesContainer40=new Float32Array(57600),cosxmultiplier=1,coszmultiplier=1,degmult=1,ydegmult=1,vcosmult=1,vsinmult=1,frsnratio=0,brdfrsnratio=1,faceNormals=!1,refract=1,cubeMapText,zoom=45,tessellation=30;
function webGLStart(){var f=document.getElementById("canvas");f.width=window.innerWidth;f.height=window.innerHeight;camera=new createCamera;document.getElementsByName("fnc")[0].checked=!1;for(var e=document.getElementsByName("tessellation"),g=0;g<e.length;g++)e[g].value=0,0==g&&(e[g].value=200),3==g&&(e[g].value=1),9==g&&(e[g].value=1);e=["webgl","experimental-webgl","webkit-3d","mozwebgl"];for(g in e)try{if((gl=f.getContext(e[g],{stencil:!0}))&&"function"==typeof gl.getParameter)break}catch(l){}null==
gl&&alert("could not initialize webGL");Program=getShader("vertex","fragment",!1);Program.a1=gl.getAttribLocation(Program,"pos");Program.a2=gl.getAttribLocation(Program,"normal");Program.projection=gl.getUniformLocation(Program,"projection");Program.model=gl.getUniformLocation(Program,"model");Program.view=gl.getUniformLocation(Program,"view");Program.rotator=gl.getUniformLocation(Program,"rotator");Program.samplerCube=gl.getUniformLocation(Program,"samplerCube");Program.cameraPos=gl.getUniformLocation(Program,
"cameraPos");Program.drawCube=gl.getUniformLocation(Program,"drawCube");Program.frsnratio=gl.getUniformLocation(Program,"frsnratio");Program.brdfrsnratio=gl.getUniformLocation(Program,"brdfrsnratio");Program.refractz=gl.getUniformLocation(Program,"refractz");cubevertices=[-1,1,-1,0,0,0,-1,-1,-1,0,0,0,1,-1,-1,0,0,0,1,-1,-1,0,0,0,1,1,-1,0,0,0,-1,1,-1,0,0,0,-1,-1,1,0,0,0,-1,-1,-1,0,0,0,-1,1,-1,0,0,0,-1,1,-1,0,0,0,-1,1,1,0,0,0,-1,-1,1,0,0,0,1,-1,-1,0,0,0,1,-1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,1,-1,0,
0,0,1,-1,-1,0,0,0,-1,-1,1,0,0,0,-1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,1,-1,1,0,0,0,-1,-1,1,0,0,0,-1,1,-1,0,0,0,1,1,-1,0,0,0,1,1,1,0,0,0,1,1,1,0,0,0,-1,1,1,0,0,0,-1,1,-1,0,0,0,-1,-1,-1,0,0,0,-1,-1,1,0,0,0,1,-1,-1,0,0,0,1,-1,-1,0,0,0,-1,-1,1,0,0,0,1,-1,1,0,0,0];cubeBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cubeBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(cubevertices),gl.STATIC_DRAW);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,
tessellation),gl.STATIC_DRAW);f=Float32Array.BYTES_PER_ELEMENT;gl.enableVertexAttribArray(Program.a1);gl.enableVertexAttribArray(Program.a2);gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,6*f,0);gl.vertexAttribPointer(Program.a2,3,gl.FLOAT,!1,6*f,3*f);cubeMapText=cubeMapTexture();camera.speed=2.8;camera.autoCentered=!0;camera.look=[0,0,-3];camera.radius=5;requestAnimationFrame(draw)}var then=0;
function draw(f){requestAnimationFrame(draw);f*=.001;var e=f-then;then=f;gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);mat4.identity(model);mat4.perspective(projection,zoom,window.innerWidth/window.innerHeight,.1,100);gl.useProgram(Program);mat4.identity(model);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,model);gl.uniformMatrix4fv(Program.view,!1,camera.getViewMatrix(e,.15));
gl.uniform1f(Program.rotator,f);gl.uniform1f(Program.drawCube,15);gl.uniform3fv(Program.cameraPos,camera.pos);cubeMapText&&(gl.activeTexture(gl.TEXTURE0),gl.bindTexture(gl.TEXTURE_CUBE_MAP,cubeMapText),gl.uniform1i(Program.samplerCube,0));gl.bindBuffer(gl.ARRAY_BUFFER,cubeBuffer);var g=Float32Array.BYTES_PER_ELEMENT;gl.enableVertexAttribArray(Program.a1);gl.enableVertexAttribArray(Program.a2);gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,6*g,0);gl.vertexAttribPointer(Program.a2,3,gl.FLOAT,!1,6*
g,3*g);gl.drawArrays(gl.TRIANGLES,0,36);gl.enable(gl.DEPTH_TEST);mat4.identity(model);mat4.translate(model,model,[0,0,-3]);gl.uniformMatrix4fv(Program.projection,!1,projection);gl.uniformMatrix4fv(Program.model,!1,model);gl.uniformMatrix4fv(Program.view,!1,camera.getViewMatrix(e,.15));gl.uniform1f(Program.rotator,f);gl.uniform1f(Program.drawCube,0);gl.uniform3fv(Program.cameraPos,camera.pos);gl.uniform1f(Program.frsnratio,frsnratio);gl.uniform1f(Program.brdfrsnratio,brdfrsnratio);gl.uniform1f(Program.refractz,
refract);cubeMapText&&(gl.activeTexture(gl.TEXTURE0),gl.bindTexture(gl.TEXTURE_CUBE_MAP,cubeMapText),gl.uniform1i(Program.samplerCube,0));f=6*(tessellation*tessellation-2*tessellation);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);g=Float32Array.BYTES_PER_ELEMENT;gl.enableVertexAttribArray(Program.a1);gl.enableVertexAttribArray(Program.a2);gl.vertexAttribPointer(Program.a1,3,gl.FLOAT,!1,6*g,0);gl.vertexAttribPointer(Program.a2,3,gl.FLOAT,!1,6*g,3*g);gl.drawArrays(gl.TRIANGLES,0,f)}
function createsphere(f,e){if(faceNormals)return createspherefn(f,e);for(var g=360/e*degmult,l=[],b=new Float32Array(e*e*6),a=0;a<e;a++)for(var c=0;c<e;c++){var d=0==a%2?0:g/2,n=Math.cos(Math.radians(c*g*vcosmult+d))*f,d=Math.sin(Math.radians(c*g+d))*f,k=a/(e-1)*180-90,m=Math.sin(Math.radians(k*ydegmult))*f,n=n*Math.pow(Math.cos(Math.radians(k*vsinmult)),cosxmultiplier),d=d*Math.pow(Math.cos(Math.radians(k*vsinmult)),coszmultiplier),d=d-0;b[a*e*6+6*c+0]=n;b[a*e*6+6*c+1]=m;b[a*e*6+6*c+2]=d;b[a*e*6+
6*c+3]=1;b[a*e*6+6*c+4]=1;b[a*e*6+6*c+5]=1;l.push([n,m,d,1,1,1])}g=[];for(b=e;b<l.length&&!(b>=l.length-e);b++)0==(b-b%e)/e%2?(a=l[b],c=0==(b+1)%e?l[b-e+1]:l[b+1],n=l[b+e],d=l[b-e]):(a=l[b],c=0==(b+1)%e?l[b-e+1]:l[b+1],n=0==(b+1)%e?l[b+1]:l[b+e+1],d=0==(b+1)%e?l[b-2*e+1]:l[b-e+1]),calcnormal(g,c,a,n),calcnormal(g,a,c,d);if(200>=e){for(b=0;b<g.length;b++)trianglesContainer200[b]=g[b];return trianglesContainer200}if(100>=e){for(b=0;b<g.length;b++)trianglesContainer100[b]=g[b];return trianglesContainer100}if(40>=
e){for(b=0;b<g.length;b++)trianglesContainer40[b]=g[b];return trianglesContainer40}for(b=0;b<g.length;b++)trianglesContainer[b]=g[b];return trianglesContainer}
function createspherefn(f,e){var g=360/e*degmult,l=[];new Float32Array(e*e*6);for(var b=0;b<e;b++)for(var a=0;a<e;a++){var c=0==b%2?0:g/2,d=Math.cos(Math.radians(a*g*vcosmult+c))*f,c=Math.sin(Math.radians(a*g+c))*f,n=b/(e-1)*180-90,k=Math.sin(Math.radians(n*ydegmult))*f,d=d*Math.pow(Math.cos(Math.radians(n*vsinmult)),cosxmultiplier),c=c*Math.pow(Math.cos(Math.radians(n*vsinmult)),coszmultiplier),c=c-0;l.push([d,k,c,0,0,0])}g=[];b=[];for(a=0;a<e*e;a++)b[a]=[];for(a=e;a<l.length&&!(a>=l.length-e);a++)if(0==
(a-a%e)/e%2){var d=l[a],c=0==(a+1)%e?a-e+1:a+1,n=l[c],m=l[a+e],k=l[a-e],m=calcnormalfn(g,n,d,m);b[a].push(m);b[c].push(m);b[a+e].push(m);d=calcnormalfn(g,d,n,k);b[a].push(d);b[c].push(d);b[a-e].push(d)}else{var d=l[a],c=0==(a+1)%e?a-e+1:a+1,h=0==(a+1)%e?a+1:a+e+1,t=0==(a+1)%e?a-2*e+1:a-e+1,n=l[c],m=l[h],k=l[t],m=calcnormalfn(g,n,d,m);b[a].push(m);b[c].push(m);b[h].push(m);d=calcnormalfn(g,d,n,k);b[a].push(d);b[c].push(d);b[t].push(d)}for(a=0;a<b.length;a++){d=[0,0,0];n=b[a].length;for(c=0;c<n;c++)d[0]+=
b[a][c][0],d[1]+=b[a][c][1],d[2]+=b[a][c][2];d[0]/=n;d[1]/=n;d[2]/=n;l[a][3]=d[0];l[a][4]=d[1];l[a][5]=d[2]}for(a=e;a<l.length&&!(a>=l.length-e);a++){0==(a-a%e)/e%2?(d=l[a],c=0==(a+1)%e?a-e+1:a+1,n=l[c],m=l[a+e],k=l[a-e]):(d=l[a],c=0==(a+1)%e?a-e+1:a+1,h=0==(a+1)%e?a+1:a+e+1,t=0==(a+1)%e?a-2*e+1:a-e+1,n=l[c],m=l[h],k=l[t]);for(c=0;6>c;c++)g.push(d[c]);for(c=0;6>c;c++)g.push(n[c]);for(c=0;6>c;c++)g.push(m[c]);for(c=0;6>c;c++)g.push(n[c]);for(c=0;6>c;c++)g.push(d[c]);for(c=0;6>c;c++)g.push(k[c])}if(200>=
e){for(a=0;a<g.length;a++)trianglesContainer200[a]=g[a];return trianglesContainer200}if(100>=e){for(a=0;a<g.length;a++)trianglesContainer100[a]=g[a];return trianglesContainer100}if(40>=e){for(a=0;a<g.length;a++)trianglesContainer40[a]=g[a];return trianglesContainer40}for(a=0;a<g.length;a++)trianglesContainer[a]=g[a];return trianglesContainer}Math.radians=function(f){return f*Math.PI/180};
function calcnormal(f,e,g,l){v1x=g[0]-e[0];v1y=g[1]-e[1];v1z=g[2]-e[2];v2x=l[0]-e[0];v2y=l[1]-e[1];v2z=l[2]-e[2];upnormalx=v1y*v2z-v1z*v2y;upnormaly=v1z*v2x-v1x*v2z;upnormalz=v1x*v2y-v1y*v2x;e[3]=upnormalx;e[4]=upnormaly;e[5]=upnormalz;g[3]=upnormalx;g[4]=upnormaly;g[5]=upnormalz;l[3]=upnormalx;l[4]=upnormaly;l[5]=upnormalz;for(var b=0;6>b;b++)f.push(e[b]);for(b=0;6>b;b++)f.push(g[b]);for(b=0;6>b;b++)f.push(l[b])}
function calcnormalfn(f,e,g,l){v1x=g[0]-e[0];v1y=g[1]-e[1];v1z=g[2]-e[2];v2x=l[0]-e[0];v2y=l[1]-e[1];v2z=l[2]-e[2];upnormalx=v1y*v2z-v1z*v2y;upnormaly=v1z*v2x-v1x*v2z;upnormalz=v1x*v2y-v1y*v2x;return[upnormalx,upnormaly,upnormalz]}
function cubeMapTexture(){var f=gl.createTexture();gl.bindTexture(gl.TEXTURE_CUBE_MAP,f);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_CUBE_MAP,gl.TEXTURE_MAG_FILTER,gl.LINEAR);for(var e=[["posx.jpg",gl.TEXTURE_CUBE_MAP_POSITIVE_X],["negx.jpg",gl.TEXTURE_CUBE_MAP_NEGATIVE_X],["posy.jpg",gl.TEXTURE_CUBE_MAP_POSITIVE_Y],
["negy.jpg",gl.TEXTURE_CUBE_MAP_NEGATIVE_Y],["posz.jpg",gl.TEXTURE_CUBE_MAP_POSITIVE_Z],["negz.jpg",gl.TEXTURE_CUBE_MAP_NEGATIVE_Z]],g=0;g<e.length;g++){var l=e[g][1],b=new Image;b.onload=function(a,b,d){return function(){gl.bindTexture(gl.TEXTURE_CUBE_MAP,a);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,!1);gl.texImage2D(b,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,d)}}(f,l,b);b.src=e[g][0]}return f}
function tessellate(f){f=parseInt(f);f=Math.pow(f/500,3);f=Math.floor(500*f);3>f&&(f=3);200<f&&(f=500);if(500!=f||500!=tessellation)gl.bindBuffer(gl.ARRAY_BUFFER,buffer),gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,f),gl.STATIC_DRAW),tessellation=Math.floor(f)}
function params(f,e){switch(e){case "cosx":cosxmultiplier=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);break;case "cosz":coszmultiplier=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);break;case "degratio":degmult=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);
break;case "ydegratio":ydegmult=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);break;case "vcos":vcosmult=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);break;case "vsin":vsinmult=parseFloat(f);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW);break;case "fresnel":frsnratio=parseFloat(f);
break;case "borderfresnel":brdfrsnratio=parseFloat(f);break;case "refrtorefl":refract=parseFloat(f)}}function refractt(f){f&&(refract=2);f||(refract=0)}function faceNorm(f){f&&(faceNormals=!0,gl.bindBuffer(gl.ARRAY_BUFFER,buffer),gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW));f||(faceNormals=!1,gl.bindBuffer(gl.ARRAY_BUFFER,buffer),gl.bufferData(gl.ARRAY_BUFFER,createsphere(1,tessellation),gl.STATIC_DRAW))};